package signing

import (
	"crypto/ed25519"
	"encoding/hex"
	"fmt"
	"strings"
)

// TrustRoot is the set of public keys a verifier already holds.
//
// docs/VERIFICATION.md:81-83: "Pin the root, not the response. A verifier
// that learns its trust root from the service it is checking has checked
// nothing. That root must ship in this repository, in signed releases, and
// in a separately operated channel, and no relayed response may introduce a
// new one."
//
// So a TrustRoot is CONSTRUCTED, never parsed out of a statement. Verify
// takes one and looks up the statement's key id inside it; an id the root
// does not hold fails, which is the whole control.
type TrustRoot struct {
	// keys is (domain, id) -> public key. Domain is part of the lookup
	// key rather than a field to compare afterwards, so a capabilities
	// key cannot verify a customer acceptance even by id collision.
	keys map[rootKey]ed25519.PublicKey
}

type rootKey struct{ domain, id string }

// NewTrustRoot builds a root from hex-encoded public keys.
//
// It refuses an unknown domain and a malformed key rather than skipping it:
// a root that silently dropped an entry would fail verification later with
// "unknown key id", which reads as a bad statement rather than a bad
// deployment.
func NewTrustRoot(entries []PinnedKey) (TrustRoot, error) {
	root := TrustRoot{keys: make(map[rootKey]ed25519.PublicKey, len(entries))}
	for _, e := range entries {
		if !knownDomain(e.Domain) {
			return TrustRoot{}, fmt.Errorf("%w: %q for key %q", ErrUnknownDomain, e.Domain, e.ID)
		}
		if strings.TrimSpace(e.ID) == "" {
			return TrustRoot{}, fmt.Errorf("%w: key id", ErrIncomplete)
		}
		raw, err := hex.DecodeString(e.PublicKeyHex)
		if err != nil {
			return TrustRoot{}, fmt.Errorf("%w: key %q is not hex: %v", ErrIncomplete, e.ID, err)
		}
		if len(raw) != ed25519.PublicKeySize {
			return TrustRoot{}, fmt.Errorf("%w: an ed25519 public key is %d bytes, key %q has %d",
				ErrIncomplete, ed25519.PublicKeySize, e.ID, len(raw))
		}
		// The id must be the one the material itself produces. Without
		// this a root can pin a key under an id that is not its own, and
		// every signature it should have verified fails as "bad
		// signature" rather than as the misconfiguration it is.
		// The id must be the one the material itself produces. Without
		// this a root can pin a key under an id that is not its own, and
		// every signature it should have verified fails as "bad
		// signature" rather than as the misconfiguration it is.
		if derived := KeyID(ed25519.PublicKey(raw)); derived != e.ID {
			return TrustRoot{}, fmt.Errorf("%w: key pinned as %q but its public half derives %q",
				ErrIncomplete, e.ID, derived)
		}
		k := rootKey{domain: e.Domain, id: e.ID}
		if _, dup := root.keys[k]; dup {
			return TrustRoot{}, fmt.Errorf("%w: key %q appears twice for %s", ErrIncomplete, e.ID, e.Domain)
		}
		root.keys[k] = ed25519.PublicKey(raw)
	}
	return root, nil
}

// PinnedKey is one entry of a trust root, as it appears in source.
type PinnedKey struct {
	ID           string
	Domain       string
	PublicKeyHex string
}

// PublicKey looks up a key by id WITHIN a domain.
func (r TrustRoot) PublicKey(id, domain string) (ed25519.PublicKey, bool) {
	k, ok := r.keys[rootKey{domain: domain, id: id}]
	return k, ok
}

// Len reports how many keys this root holds.
//
// It exists so a deployment can report an EMPTY root rather than behaving as
// though it had one: a root with no keys verifies nothing, and a surface
// claiming verification readiness on top of it would be asserting a capacity
// it does not have.
func (r TrustRoot) Len() int { return len(r.keys) }

// pinnedKeys is the trust root that ships in this repository.
//
// One key, for the billing-evidence domain, provisioned 2026-09-01.
//
// A placeholder here would be worse than nothing: Verify would find an id,
// check a signature no one can produce, and a deployment could report itself
// ready to verify evidence that cannot exist. This is not a placeholder — the
// private half was generated by cmd/signing-keygen and is held in SSM, and the
// id below is DERIVED from these public bytes (NewTrustRoot refuses an entry
// whose id does not match its own key, so a wrong pin fails at startup rather
// than at the first verification).
//
// It is UNEXPORTED. An exported package-level slice is not pinned — any
// package in the tree could append to it at runtime and every later
// Repository() call would return a root containing the added key, which is
// precisely the "a verifier that learns its trust root from elsewhere has
// checked nothing" failure this variable exists to prevent. Adding a key is a
// deliberate edit to this file with a diff attached.
//
// Each entry names the environment it belongs to; the private half lives in
// SSM and never in this repository.
//
// 🔴 PINNING THE PUBLIC HALF IS NOT PROVISIONING THE PRIVATE ONE, and the two
// readinesses are separate:
//
//   - VERIFICATION is ready as soon as a key is pinned here. Repository()
//     returns a root of length one and Verify accepts a signature made with
//     the matching seed.
//   - SIGNING is ready only where Load finds seed material in
//     BILLING_SIGNING_KEY_BILLING_EVIDENCE (loader.go:36). A deployment
//     without it still cannot sign, and an absent variable is deliberately not
//     an error — a deployment that signs nothing is legitimate.
//
// So a deployment that has this pin and no seed can verify evidence someone
// else produced and can produce none itself. That is the correct fail-closed
// direction and it is why the pin lands before, or independently of, the
// secret being placed in any given environment.
var pinnedKeys = []PinnedKey{
	{
		ID:           "7cd37ff8ba25c9d79445918a5eab5d17",
		Domain:       DomainBillingEvidence,
		PublicKeyHex: "d6905a8cd8099ea30eabadee9bc638fdd554e5868b48aa2a9c3daf2fd43e38e4",
	},
}

// Repository returns the trust root that ships in this tree.
//
// It returns an error rather than panicking. A panic here fires on the first
// CALL, which may be deep inside a request, long after startup — so a build
// carrying a malformed pinned key would look healthy until the first customer
// tried to verify something. A caller at startup can refuse to start, which
// is where that decision belongs.
func Repository() (TrustRoot, error) {
	root, err := NewTrustRoot(pinnedKeys)
	if err != nil {
		return TrustRoot{}, fmt.Errorf("the trust root pinned in this repository is malformed: %w", err)
	}
	return root, nil
}

// PinnedKeyCount reports how many keys ship in this tree, for a readiness
// surface that must not claim verification it cannot perform.
func PinnedKeyCount() int { return len(pinnedKeys) }
