// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_transfer.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const appTransferEventByRequest = `-- name: AppTransferEventByRequest :one
SELECT request_id, app_id, from_account, to_account, mode, moved_event_count, at,
       open_period_start, open_period_end, recurring_from
FROM ms_billing.app_transfer_events
WHERE request_id = $1
`

type AppTransferEventByRequestRow struct {
	RequestID       string      `json:"request_id"`
	AppID           string      `json:"app_id"`
	FromAccount     pgtype.UUID `json:"from_account"`
	ToAccount       string      `json:"to_account"`
	Mode            string      `json:"mode"`
	MovedEventCount int64       `json:"moved_event_count"`
	At              time.Time   `json:"at"`
	OpenPeriodStart time.Time   `json:"open_period_start"`
	OpenPeriodEnd   time.Time   `json:"open_period_end"`
	RecurringFrom   time.Time   `json:"recurring_from"`
}

// AppTransferEventByRequest reads the idempotency record for a request_id.
// A hit means this transfer already happened: the caller gets the STORED
// result — every field of it, the window and recurring_from included, so a
// retry that lands after a boundary answers with the same dates the first
// call did — and a different target for the same key is a conflict rather
// than a second transfer.
func (q *Queries) AppTransferEventByRequest(ctx context.Context, requestID string) (AppTransferEventByRequestRow, error) {
	row := q.db.QueryRow(ctx, appTransferEventByRequest, requestID)
	var i AppTransferEventByRequestRow
	err := row.Scan(
		&i.RequestID,
		&i.AppID,
		&i.FromAccount,
		&i.ToAccount,
		&i.Mode,
		&i.MovedEventCount,
		&i.At,
		&i.OpenPeriodStart,
		&i.OpenPeriodEnd,
		&i.RecurringFrom,
	)
	return i, err
}

const appUnresolvedOneTimeCharges = `-- name: AppUnresolvedOneTimeCharges :one
SELECT
    EXISTS (
        SELECT 1 FROM ms_billing.apps a
        WHERE a.app_id = $1::uuid
          AND a.proration_invoice_id IS NULL
          AND a.proration_skipped_at IS NULL
          AND NOT EXISTS (
              SELECT 1 FROM ms_billing.app_combined_proration_attempts att
              WHERE att.app_id = a.app_id
                AND att.resolved_at IS NOT NULL
          )
    )::bool AS proration_pending,
    EXISTS (
        SELECT 1 FROM ms_billing.apps a
        WHERE a.app_id = $1::uuid
          AND a.proration_invoice_id IS NULL
          AND a.proration_skipped_at IS NULL
          AND NOT EXISTS (
              SELECT 1 FROM ms_billing.app_combined_proration_attempts att
              WHERE att.app_id = a.app_id
                AND att.resolved_at IS NOT NULL
          )
          AND (a.proration_attempted_at IS NOT NULL
               OR EXISTS (
                   SELECT 1 FROM ms_billing.app_combined_proration_attempts att
                   WHERE att.app_id = a.app_id
                     AND att.resolved_at IS NULL
               ))
    )::bool AS proration_in_flight,
    (
        SELECT count(*) FROM ms_billing.app_custom_domains d
        WHERE d.app_id = $1::uuid
          AND d.removed_at IS NULL
          AND d.charge_resolved = false
    )::bigint AS domain_pending,
    (
        SELECT count(*) FROM ms_billing.app_custom_domains d
        WHERE d.app_id = $1::uuid
          AND d.removed_at IS NULL
          AND d.charge_resolved = false
          AND d.charge_attempted_at IS NOT NULL
    )::bigint AS domain_in_flight,
    (
        SELECT count(*) FROM ms_billing.app_module_overage_timers m
        WHERE m.app_id = $1::uuid
          AND m.removed_at IS NULL
          AND m.grace_resolved = false
          AND NOT EXISTS (
              SELECT 1 FROM ms_billing.app_combined_proration_attempt_timers owned
              WHERE owned.timer_id = m.id
          )
    )::bigint AS timer_pending,
    (
        SELECT count(*) FROM ms_billing.app_module_overage_timers m
        WHERE m.app_id = $1::uuid
          AND m.removed_at IS NULL
          AND m.grace_resolved = false
          AND m.charge_attempted_at IS NOT NULL
          AND NOT EXISTS (
              SELECT 1 FROM ms_billing.app_combined_proration_attempt_timers owned
              WHERE owned.timer_id = m.id
          )
    )::bigint AS timer_in_flight
`

type AppUnresolvedOneTimeChargesRow struct {
	ProrationPending  bool  `json:"proration_pending"`
	ProrationInFlight bool  `json:"proration_in_flight"`
	DomainPending     int64 `json:"domain_pending"`
	DomainInFlight    int64 `json:"domain_in_flight"`
	TimerPending      int64 `json:"timer_pending"`
	TimerInFlight     int64 `json:"timer_in_flight"`
}

// AppUnresolvedOneTimeCharges classifies every MID-PERIOD ONE-TIME charge
// still owed for this app by whoever owns it now, so the transfer can decide
// between refusing and forfeiting (see 071 and transfer_store.go).
//
// 🔴 THIS IS A MONEY GUARD, NOT A TIDINESS CHECK. All three legs read the
// CURRENT owner off the row at charge time and bill whoever it points at:
// creation proration (apps.sql AppsPendingProration), custom-domain activation
// (domains.sql DomainsPendingCharge) and per-module grace overage
// (module_timers.sql). Re-key an app while one of them is unresolved and the
// NEW account pays for a window it did not own — the exact inverse of the rule
// that keeps prepaid recurring with the old account.
//
// Two readings per leg:
//
//	*_pending    — unresolved, by the leg's own terminal predicate. A creation
//	               proration whose combined attempt is RESOLVED counts as
//	               settled even while apps.proration_invoice_id is NULL: the
//	               attempt was sealed as an intent (MarkCombinedProrationProposed
//	               resolves the header, and only the header), so the intent
//	               rail owns it and nothing here may forfeit or re-bill it. A
//	               timer that a combined attempt owns is that attempt's line
//	               (resolved or not), never a standalone charge of its own.
//	*_in_flight  — a SUBSET of *_pending: unresolved AND already armed at the
//	               provider, or frozen into an unresolved combined attempt.
//	               Money may have moved.
//	               The transfer REFUSES these regardless of whether the old
//	               account could settle: forfeiting a row whose invoice may
//	               already be finalized would leave a collected charge with no
//	               mirror, and the 050 terminal guard raises on the app row
//	               anyway. A refusal is retryable; a forfeit over moved money
//	               is not.
//
// No account_id predicate on the proration leg — an UNBILLED org roster row
// (account_id NULL) owes its creation window just as much, and RekeyAppRoster
// would hand exactly that window to the new owner: the row acquires an
// account, AppsPendingProration selects it, and the D1d check compares only
// activation against the creation period, which a long-activated target
// passes. The NULL-source case is forfeited, never carried.
//
// Evaluated INSIDE the transfer transaction, under the app row lock, so the
// proration sweep (which locks the same row) cannot slip between this read
// and the re-key; the domain and timer sweeps lock only their own rows, and
// the forfeit writers below re-check the arm marker in their WHERE so a
// concurrent arm is observed as a row-count shortfall, never silently
// forfeited.
func (q *Queries) AppUnresolvedOneTimeCharges(ctx context.Context, appID string) (AppUnresolvedOneTimeChargesRow, error) {
	row := q.db.QueryRow(ctx, appUnresolvedOneTimeCharges, appID)
	var i AppUnresolvedOneTimeChargesRow
	err := row.Scan(
		&i.ProrationPending,
		&i.ProrationInFlight,
		&i.DomainPending,
		&i.DomainInFlight,
		&i.TimerPending,
		&i.TimerInFlight,
	)
	return i, err
}

const forfeitAppDomainChargesOnTransfer = `-- name: ForfeitAppDomainChargesOnTransfer :execrows
UPDATE ms_billing.app_custom_domains
SET charge_resolved     = true,
    charge_forfeited_by = $1::uuid
WHERE app_id = $2::uuid
  AND removed_at IS NULL
  AND charge_resolved = false
  AND charge_attempted_at IS NULL
`

type ForfeitAppDomainChargesOnTransferParams struct {
	RequestID string `json:"request_id"`
	AppID     string `json:"app_id"`
}

// ForfeitAppDomainChargesOnTransfer resolves every live, unresolved,
// never-armed activation charge for the app WITHOUT charging it and stamps
// the transfer that did so (071). charge_attempted_at IS NULL is the
// linearization point against a concurrently arming domain sweep: the arm
// statement row-locks and re-checks charge_resolved = false, this one
// row-locks and re-checks charge_attempted_at IS NULL, so whichever commits
// second sees the other's write — an arm that won makes this UPDATE skip the
// row, which the store reads as a count shortfall and aborts on. :execrows.
func (q *Queries) ForfeitAppDomainChargesOnTransfer(ctx context.Context, arg ForfeitAppDomainChargesOnTransferParams) (int64, error) {
	result, err := q.db.Exec(ctx, forfeitAppDomainChargesOnTransfer, arg.RequestID, arg.AppID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const forfeitAppModuleTimersOnTransfer = `-- name: ForfeitAppModuleTimersOnTransfer :execrows
UPDATE ms_billing.app_module_overage_timers timer
SET grace_resolved     = true,
    grace_forfeited_by = $1::uuid
WHERE timer.app_id = $2::uuid
  AND timer.removed_at IS NULL
  AND timer.grace_resolved = false
  AND timer.charge_attempted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM ms_billing.app_combined_proration_attempt_timers owned
      WHERE owned.timer_id = timer.id
  )
`

type ForfeitAppModuleTimersOnTransferParams struct {
	RequestID string `json:"request_id"`
	AppID     string `json:"app_id"`
}

// ForfeitAppModuleTimersOnTransfer is the timer twin. A timer owned by a
// combined creation attempt is excluded (it is that attempt's line, and the
// 050 terminal guard would raise on an unresolved owner anyway); the arm
// marker predicate is the same linearization point as on the domain writer.
// :execrows.
func (q *Queries) ForfeitAppModuleTimersOnTransfer(ctx context.Context, arg ForfeitAppModuleTimersOnTransferParams) (int64, error) {
	result, err := q.db.Exec(ctx, forfeitAppModuleTimersOnTransfer, arg.RequestID, arg.AppID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const forfeitAppProrationOnTransfer = `-- name: ForfeitAppProrationOnTransfer :execrows
UPDATE ms_billing.apps
SET proration_skipped_at = $1::timestamptz
WHERE app_id = $2::uuid
  AND proration_skipped_at IS NULL
  AND proration_invoice_id IS NULL
  AND proration_attempted_at IS NULL
`

type ForfeitAppProrationOnTransferParams struct {
	At    time.Time `json:"at"`
	AppID string    `json:"app_id"`
}

// ForfeitAppProrationOnTransfer arms the PERMANENT skip marker (031) at the
// transfer instant: the creation window is never charged, to anyone. The
// predicates are SetAppProrationSkipped's plus proration_attempted_at IS NULL
// — an attempted proration is in flight and the store refuses before reaching
// here; the predicate makes the writer refuse it too. :execrows so the store
// can assert the marker landed on the one row it read as pending.
func (q *Queries) ForfeitAppProrationOnTransfer(ctx context.Context, arg ForfeitAppProrationOnTransferParams) (int64, error) {
	result, err := q.db.Exec(ctx, forfeitAppProrationOnTransfer, arg.At, arg.AppID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertAppTransferEvent = `-- name: InsertAppTransferEvent :exec
INSERT INTO ms_billing.app_transfer_events (
    request_id, app_id, from_account, to_account, mode, moved_event_count, at,
    open_period_start, open_period_end, recurring_from,
    forfeited_proration, forfeited_domain_count, forfeited_timer_count, forfeit_reason
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type InsertAppTransferEventParams struct {
	RequestID            string      `json:"request_id"`
	AppID                string      `json:"app_id"`
	FromAccount          pgtype.UUID `json:"from_account"`
	ToAccount            string      `json:"to_account"`
	Mode                 string      `json:"mode"`
	MovedEventCount      int64       `json:"moved_event_count"`
	At                   time.Time   `json:"at"`
	OpenPeriodStart      time.Time   `json:"open_period_start"`
	OpenPeriodEnd        time.Time   `json:"open_period_end"`
	RecurringFrom        time.Time   `json:"recurring_from"`
	ForfeitedProration   bool        `json:"forfeited_proration"`
	ForfeitedDomainCount int64       `json:"forfeited_domain_count"`
	ForfeitedTimerCount  int64       `json:"forfeited_timer_count"`
	ForfeitReason        pgtype.Text `json:"forfeit_reason"`
}

// InsertAppTransferEvent records what the transfer did AND what it answered,
// including what it forfeited (the forfeit_* columns; 071 says when a
// transfer forfeits and when it refuses instead). request_id is UNIQUE, so a
// concurrent duplicate loses on the index rather than transferring twice.
func (q *Queries) InsertAppTransferEvent(ctx context.Context, arg InsertAppTransferEventParams) error {
	_, err := q.db.Exec(ctx, insertAppTransferEvent,
		arg.RequestID,
		arg.AppID,
		arg.FromAccount,
		arg.ToAccount,
		arg.Mode,
		arg.MovedEventCount,
		arg.At,
		arg.OpenPeriodStart,
		arg.OpenPeriodEnd,
		arg.RecurringFrom,
		arg.ForfeitedProration,
		arg.ForfeitedDomainCount,
		arg.ForfeitedTimerCount,
		arg.ForfeitReason,
	)
	return err
}

const lockAppForTransfer = `-- name: LockAppForTransfer :one
SELECT app_id, account_id, owner_org_id
FROM ms_billing.apps
WHERE app_id = $1
  AND deleted_at IS NULL
FOR UPDATE
`

type LockAppForTransferRow struct {
	AppID      string      `json:"app_id"`
	AccountID  pgtype.UUID `json:"account_id"`
	OwnerOrgID pgtype.UUID `json:"owner_org_id"`
}

// LockAppForTransfer takes the app's roster row FOR UPDATE and returns its
// current attribution. Everything the transfer decides is read here, under the
// lock, so a concurrent RegisterApp/SyncAppModules or a second TransferApp
// cannot interleave between the read and the writes.
//
// deleted_at IS NULL, as every LIVE-roster read in apps.sql spells it: a
// soft-deleted app has nothing left to transfer — it is already out of every
// future base fee (D1e) — and re-keying its row would hand the NEW account
// whatever the deletion left behind on it. No row ⇒ NOT_FOUND, the same answer
// as an app this service never mirrored, because to the caller both are "no
// billing here to move".
func (q *Queries) LockAppForTransfer(ctx context.Context, appID string) (LockAppForTransferRow, error) {
	row := q.db.QueryRow(ctx, lockAppForTransfer, appID)
	var i LockAppForTransferRow
	err := row.Scan(&i.AppID, &i.AccountID, &i.OwnerOrgID)
	return i, err
}

const moveAppOpenUsage = `-- name: MoveAppOpenUsage :execrows
UPDATE ms_billing.usage_events
SET account_id = $3
WHERE app_id = $1
  AND account_id = $2
  AND COALESCE(billable_at, recorded_at) >= $4::timestamptz
  AND COALESCE(billable_at, recorded_at) <  $5::timestamptz
`

type MoveAppOpenUsageParams struct {
	AppID       string      `json:"app_id"`
	AccountID   pgtype.UUID `json:"account_id"`
	AccountID_2 pgtype.UUID `json:"account_id_2"`
	WindowStart time.Time   `json:"window_start"`
	WindowEnd   time.Time   `json:"window_end"`
}

// MoveAppOpenUsage re-attributes this app's usage events for mode="move".
//
// 🔴 EVERY TERM IN THE WINDOW IS LOAD-BEARING.
//
//	app_id          — this app only; an account's other apps keep their usage.
//	account_id      — only rows still attributed to the OLD account.
//	the WINDOW EXPRESSION is COALESCE(billable_at, recorded_at), which is what
//	                  the ROLLUP itself buckets on (rollup.sql:66-69) and what
//	                  every bill read and the 055 index use. It is NOT
//	                  occurred_at: occurred_at is NULL for every infra.* and
//	                  platform.* event and for every legacy/v1 observation, and
//	                  `NULL >= $1` is NULL, so an occurred_at filter silently
//	                  moves NO infra or platform usage and leaves the OLD
//	                  account invoiced for the app's egress, AI and GPU. Every
//	                  writer keeps billable_at >= occurred_at, so filtering on
//	                  the rollup's own expression does not loosen the INV-011
//	                  bound — it applies it to the rows the bill actually reads.
//	>= window_start — max(old.openStart, new.openStart): an event older than
//	                  the TARGET's open period would be backdated into a period
//	                  it has already closed and billed, which INV-011 forbids.
//	<  window_end   — the transfer instant. Usage after it belongs to the new
//	                  account by ordinary attribution, not by re-attribution.
//
// The rollup reads usage_events.account_id and never joins the app roster, so
// moving these rows is exactly and only what changes which account bills them.
func (q *Queries) MoveAppOpenUsage(ctx context.Context, arg MoveAppOpenUsageParams) (int64, error) {
	result, err := q.db.Exec(ctx, moveAppOpenUsage,
		arg.AppID,
		arg.AccountID,
		arg.AccountID_2,
		arg.WindowStart,
		arg.WindowEnd,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rekeyAppDomains = `-- name: RekeyAppDomains :execrows
UPDATE ms_billing.app_custom_domains
SET account_id = $2
WHERE app_id = $1 AND removed_at IS NULL
`

type RekeyAppDomainsParams struct {
	AppID     string `json:"app_id"`
	AccountID string `json:"account_id"`
}

// RekeyAppDomains follows the roster, same live-only rule.
func (q *Queries) RekeyAppDomains(ctx context.Context, arg RekeyAppDomainsParams) (int64, error) {
	result, err := q.db.Exec(ctx, rekeyAppDomains, arg.AppID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rekeyAppRoster = `-- name: RekeyAppRoster :execrows
UPDATE ms_billing.apps
SET account_id = $2,
    owner_org_id = $3
WHERE app_id = $1
`

type RekeyAppRosterParams struct {
	AppID      string      `json:"app_id"`
	AccountID  pgtype.UUID `json:"account_id"`
	OwnerOrgID pgtype.UUID `json:"owner_org_id"`
}

// RekeyAppRoster moves the app's billing attribution.
//
// 🔴 THERE IS NO owner_user_id ON THIS TABLE, and the contract's wording
// ("owner_user_id/owner_org_id") does not match the schema. ms_billing.apps
// carries account_id plus owner_org_id (041) only; a user owner is identified
// by the ACCOUNT (accounts.owner_kind / owner_user_id), not by the app row. So
// a transfer to a user sets owner_org_id NULL and lets the account carry the
// identity, and a transfer to an org sets it — which is also what the repoint
// sweep needs, since it scopes NULL-account usage_events to an org through
// this column.
//
// Runs FIRST so the deferred attribution triggers see a roster to agree with.
func (q *Queries) RekeyAppRoster(ctx context.Context, arg RekeyAppRosterParams) (int64, error) {
	result, err := q.db.Exec(ctx, rekeyAppRoster, arg.AppID, arg.AccountID, arg.OwnerOrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rekeyAppTimers = `-- name: RekeyAppTimers :execrows
UPDATE ms_billing.app_module_overage_timers
SET account_id = $2
WHERE app_id = $1 AND removed_at IS NULL
`

type RekeyAppTimersParams struct {
	AppID     string `json:"app_id"`
	AccountID string `json:"account_id"`
}

// RekeyAppTimers follows the roster. Only LIVE timers move: a removed timer's
// charge, if any, already resolved against the account that owned it.
func (q *Queries) RekeyAppTimers(ctx context.Context, arg RekeyAppTimersParams) (int64, error) {
	result, err := q.db.Exec(ctx, rekeyAppTimers, arg.AppID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const transferSourceSettlement = `-- name: TransferSourceSettlement :one
SELECT (a.activated_at IS NOT NULL)::bool AS activated,
       (a.usage_billing_mode = 'arrears')::bool AS arrears,
       EXISTS (
           SELECT 1
           FROM ms_billing.payment_methods_mirror payment_method
           WHERE payment_method.account_id = funding_auth.funding_account_id
             AND payment_method.deleted_at IS NULL
             AND (payment_method.exp_year, payment_method.exp_month) >= (
                 EXTRACT(YEAR FROM current_date)::INT,
                 EXTRACT(MONTH FROM current_date)::INT
             )
       )::bool AS has_usable_payment_method
FROM ms_billing.accounts a
LEFT JOIN ms_billing.account_funding_authorizations funding_auth
  ON funding_auth.account_id = a.id
WHERE a.id = $1::uuid
`

type TransferSourceSettlementRow struct {
	Activated              bool `json:"activated"`
	Arrears                bool `json:"arrears"`
	HasUsablePaymentMethod bool `json:"has_usable_payment_method"`
}

// TransferSourceSettlement reads whether the OLD account could settle its
// unresolved one-time charges SOON, which decides refuse-versus-forfeit.
//
// The three facts are exactly the gates the charge legs apply before they
// collect, read from the same rows: activation (the D1d gate,
// ChargeCreationProration / DomainsPendingCharge / ModuleOverageTimersPastGrace
// all skip an unactivated account), collection mode (offSessionChargePermitted:
// a prepaid account is never auto-charged off-session, H10) and a usable
// payment method ON THE FUNDER — the account_funding_authorizations row, which
// is what ArmDomainStripeCharge / ArmModuleTimerStripeCharge /
// StripeFundingAuthorization arm against, with the same not-deleted,
// not-expired card predicate as HasUsableDefaultPM. All three true ⇒ the next
// sweep collects and the transfer refuses; any false ⇒ the sweep would skip
// transiently, on every run, for as long as the account stays so — the
// forever-blocked transfer the bounded rule exists to prevent.
// The LEFT JOIN keeps the row for an account with no authorization row (the
// 052 trigger creates one on every account insert, so this is belt and
// braces): no funder ⇒ no usable card.
func (q *Queries) TransferSourceSettlement(ctx context.Context, accountID string) (TransferSourceSettlementRow, error) {
	row := q.db.QueryRow(ctx, transferSourceSettlement, accountID)
	var i TransferSourceSettlementRow
	err := row.Scan(&i.Activated, &i.Arrears, &i.HasUsablePaymentMethod)
	return i, err
}
