// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: apps.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const appsPendingProration = `-- name: AppsPendingProration :many
SELECT app_id
FROM ms_billing.apps
WHERE created_at <= $1::timestamptz
  AND account_id IS NOT NULL
  AND proration_invoice_id IS NULL
  AND (deleted_at IS NULL
       OR deleted_at >= created_at + make_interval(hours => $2::int))
  AND proration_skipped_at IS NULL
ORDER BY created_at
`

type AppsPendingProrationParams struct {
	CreatedBefore time.Time `json:"created_before"`
	GraceHours    int32     `json:"grace_hours"`
}

// AppsPendingProration is the creation-proration sweep's work list: apps that
// have survived the grace window (@created_before = now() − GraceDays) and were
// never charged their creation-period base. proration_invoice_id IS NULL is the
// one-shot guard (an already-charged app drops out); the deleted_at predicate
// excludes ONLY apps soft-deleted WITHIN their grace (never charged, scenario
// 1) — an app deleted AFTER its grace elapsed SURVIVED it and still owes the
// creation charge (wave 2, D11: grace only delays WHEN the charge fires, and
// the H2 boundary exclusion leaves no other leg as a backstop; pre-fix this
// was a user-timable ~$22 dodge in the grace-elapse→sweep window). Grace in
// HOURS (D5 — session-TZ/DST safety). proration_skipped_at IS NULL excludes
// apps permanently skipped as a would-be retroactive catch-up (migration 031,
// D1d). Ordered by created_at so the oldest pending app charges first.
// account_id IS NOT NULL excludes UNBILLED org roster rows (migration 041) —
// an org app enters this sweep only once RepointOrgUsage attaches it.
func (q *Queries) AppsPendingProration(ctx context.Context, arg AppsPendingProrationParams) ([]string, error) {
	rows, err := q.db.Query(ctx, appsPendingProration, arg.CreatedBefore, arg.GraceHours)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var app_id string
		if err := rows.Scan(&app_id); err != nil {
			return nil, err
		}
		items = append(items, app_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAdvanceBaseSnapshot = `-- name: InsertAdvanceBaseSnapshot :execrows
INSERT INTO ms_billing.app_base_snapshots
    (app_id, period_start, period_end, module_count, base_micros, source)
VALUES ($1, $2, $3, $4, $5, 'advance')
ON CONFLICT (app_id, period_start) DO NOTHING
`

type InsertAdvanceBaseSnapshotParams struct {
	AppID       string    `json:"app_id"`
	PeriodStart time.Time `json:"period_start"`
	PeriodEnd   time.Time `json:"period_end"`
	ModuleCount int32     `json:"module_count"`
	BaseMicros  int64     `json:"base_micros"`
}

// InsertAdvanceBaseSnapshot records what the boundary advance leg billed one
// app for the NEW period (migration 028). ON CONFLICT (app_id, period_start)
// DO NOTHING: an existing row — a proration snapshot, or a prior reclaimed
// attempt's own row — wins, so a re-run never rewrites what was already
// recorded as billed. :execrows so the caller can observe the no-op, though
// both outcomes are success.
func (q *Queries) InsertAdvanceBaseSnapshot(ctx context.Context, arg InsertAdvanceBaseSnapshotParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertAdvanceBaseSnapshot,
		arg.AppID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.ModuleCount,
		arg.BaseMicros,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertAppMirror = `-- name: InsertAppMirror :execrows

INSERT INTO ms_billing.apps (app_id, account_id, module_count, created_module_count, created_at, name, owner_org_id)
VALUES ($1, $2, $3, $3, $4, $5, $6)
ON CONFLICT (app_id) DO NOTHING
`

type InsertAppMirrorParams struct {
	AppID       string      `json:"app_id"`
	AccountID   pgtype.UUID `json:"account_id"`
	ModuleCount int32       `json:"module_count"`
	CreatedAt   time.Time   `json:"created_at"`
	Name        pgtype.Text `json:"name"`
	OwnerOrgID  pgtype.UUID `json:"owner_org_id"`
}

// Queries backing the ms_billing.apps mirror (migration 027) — the base-fee
// roster the RegisterApp / SyncAppModules RPCs write and the charge spine +
// GetAppBill read. Money never lives here; the table carries only existence,
// the installed-module-count snapshot, and the one-shot proration guard.
// InsertAppMirror registers an app row idempotently: ON CONFLICT (app_id) DO
// NOTHING so a RegisterApp retry (or a concurrent double-fire) never rewrites
// created_at / module_count / created_module_count / the proration guard of
// the original insert — the FIRST registration's values are the stable
// proration anchor. created_module_count is stamped from the SAME $3 value as
// module_count and NEVER written again by any other query (migration 030) —
// it is the frozen count ChargeCreationProration prices its historical window
// from, immune to a later SyncAppModules install/uninstall during grace.
// :execrows so the caller can tell a fresh insert (1) from a retry no-op (0),
// though both are success.
// name ($5) is frozen from the FIRST registration like created_at /
// module_count (ON CONFLICT DO NOTHING keeps the first value across retries);
// SyncAppModules updates it while the app is live (SetAppName). account_id
// ($2) is NULL for an org-owned app whose org has not designated funding yet
// (an UNBILLED roster row, migration 041); owner_org_id ($6) is stamped on
// every org-owned registration — funded or not — so the RepointOrgUsage sweep
// can scope the org's NULL-account events through the roster.
func (q *Queries) InsertAppMirror(ctx context.Context, arg InsertAppMirrorParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertAppMirror,
		arg.AppID,
		arg.AccountID,
		arg.ModuleCount,
		arg.CreatedAt,
		arg.Name,
		arg.OwnerOrgID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const liveAppModuleCountsCreatedBefore = `-- name: LiveAppModuleCountsCreatedBefore :many
SELECT app_id, module_count
FROM ms_billing.apps
WHERE account_id = $1::uuid
  AND deleted_at IS NULL
  AND created_at < $2::timestamptz
  AND created_at + make_interval(hours => $3::int) < $2::timestamptz
`

type LiveAppModuleCountsCreatedBeforeParams struct {
	AccountID     string    `json:"account_id"`
	CreatedBefore time.Time `json:"created_before"`
	GraceHours    int32     `json:"grace_hours"`
}

type LiveAppModuleCountsCreatedBeforeRow struct {
	AppID       string `json:"app_id"`
	ModuleCount int32  `json:"module_count"`
}

// LiveAppModuleCountsCreatedBefore returns (app_id, module_count) for every
// LIVE (deleted_at IS NULL) app on the account that has JOINED the advance
// base mechanism by the cutoff — the boundary charge's advance-base input:
// advance base = Σ (BaseFee + Overage × max(0, module_count − included)).
// The cutoff is the NEW period's start (the closed window's period_end). Two
// conditions, mirroring the module-timer coverage contract (review 2026-07-06):
//   - created_at < @created_before — an app created INSIDE the new period is
//     excluded, because RegisterApp's creation-proration leg already charged
//     that app's new-period base (full or prorated) — summing it here would
//     double-bill the same period (same-day cron race, and deterministically
//     on reclaimed skipped_no_pm/failed runs).
//   - created_at + grace < @created_before — an app whose CREATION GRACE had
//     not yet elapsed when the new period opened is excluded: it has not
//     survived grace yet (an app deleted in grace is NEVER charged, scenario
//     1 — precharging its next-period base here would bill a full month for
//     an app that can still be deleted for free), and when it does survive,
//     its creation-proration charge covers through the END of the period its
//     grace elapses into (the straddled period), so this boundary's new
//     period is already that leg's coverage. Spec: apps "join this boundary
//     mechanism starting at the NEXT boundary after their own creation charge
//     fires".
//
// Deleted apps are excluded (D1e); an account with no rows (pre-backfill)
// sums to base 0 and keeps the pre-027 arrears-only invoice. app_id is
// returned so the charge leg can write the per-app-period base snapshot
// (migration 028) it bills. The grace interval is expressed in HOURS, not
// days (wave 2, D5): timestamptz + a day-interval is evaluated in the SESSION
// timezone (DST-shifting), while the Go legs' grace is a fixed GraceDays*24h
// UTC window (moduleGraceExpiry) — a non-UTC session would disagree with them
// by an hour around DST and double-bill or gap a whole period.
func (q *Queries) LiveAppModuleCountsCreatedBefore(ctx context.Context, arg LiveAppModuleCountsCreatedBeforeParams) ([]LiveAppModuleCountsCreatedBeforeRow, error) {
	rows, err := q.db.Query(ctx, liveAppModuleCountsCreatedBefore, arg.AccountID, arg.CreatedBefore, arg.GraceHours)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LiveAppModuleCountsCreatedBeforeRow{}
	for rows.Next() {
		var i LiveAppModuleCountsCreatedBeforeRow
		if err := rows.Scan(&i.AppID, &i.ModuleCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAppDeleted = `-- name: MarkAppDeleted :execrows
UPDATE ms_billing.apps
SET deleted_at = now()
WHERE app_id = $1
  AND deleted_at IS NULL
`

// MarkAppDeleted soft-deletes the roster row out of future advance base fees.
// WHERE deleted_at IS NULL keeps the FIRST deletion instant (idempotent — a
// re-fire affects 0 rows and never moves the timestamp).
func (q *Queries) MarkAppDeleted(ctx context.Context, appID string) (int64, error) {
	result, err := q.db.Exec(ctx, markAppDeleted, appID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markAppProrationAttempted = `-- name: MarkAppProrationAttempted :exec
UPDATE ms_billing.apps
SET proration_attempted_at = $2
WHERE app_id = $1
  AND proration_attempted_at IS NULL
`

type MarkAppProrationAttemptedParams struct {
	AppID                string             `json:"app_id"`
	ProrationAttemptedAt pgtype.Timestamptz `json:"proration_attempted_at"`
}

// MarkAppProrationAttempted stamps the recovery marker (036) BEFORE a
// creation-proration charge attempt's first Stripe call. First-write-wins
// (the FIRST attempt instant is the durable one); never cleared.
func (q *Queries) MarkAppProrationAttempted(ctx context.Context, arg MarkAppProrationAttemptedParams) error {
	_, err := q.db.Exec(ctx, markAppProrationAttempted, arg.AppID, arg.ProrationAttemptedAt)
	return err
}

const mirroredAppIDsOverlappingWindow = `-- name: MirroredAppIDsOverlappingWindow :many
SELECT app_id
FROM ms_billing.apps
WHERE account_id = $1::uuid
  AND created_at < $2::timestamptz
  AND (deleted_at IS NULL OR deleted_at > $3::timestamptz)
ORDER BY app_id
`

type MirroredAppIDsOverlappingWindowParams struct {
	AccountID   string    `json:"account_id"`
	PeriodEnd   time.Time `json:"period_end"`
	PeriodStart time.Time `json:"period_start"`
}

// MirroredAppIDsOverlappingWindow enumerates the account's ms_billing.apps
// roster rows whose existence interval [created_at, deleted_at) overlaps ONE
// period window [@period_start, @period_end) — the mirror half of
// GetAccountBill's app roster (the usage half is AppIDsWithUsage). The overlap
// test is the standard half-open one:
//
//	created_at < period_end AND (deleted_at IS NULL OR deleted_at > period_start)
//
// so a just-created zero-usage app still surfaces its (prorated) base on the
// account bill, an app deleted DURING the period keeps its spent base visible
// (D1e: no refunds), and an app deleted BEFORE the period opened drops out
// (its base for the window is 0 and it can have no NEW usage — any residual
// ledger rows still enumerate through the usage half). Pre-backfill apps have
// no row here at all and are covered by the usage half alone. ORDER BY app_id
// (bytewise) for a deterministic scan; the service re-sorts after the merge.
func (q *Queries) MirroredAppIDsOverlappingWindow(ctx context.Context, arg MirroredAppIDsOverlappingWindowParams) ([]string, error) {
	rows, err := q.db.Query(ctx, mirroredAppIDsOverlappingWindow, arg.AccountID, arg.PeriodEnd, arg.PeriodStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var app_id string
		if err := rows.Scan(&app_id); err != nil {
			return nil, err
		}
		items = append(items, app_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingNewCreationCharges = `-- name: PendingNewCreationCharges :many
SELECT app_id, created_at
FROM ms_billing.apps
WHERE account_id = $1::uuid
  AND created_at >= $2::timestamptz
  AND created_at < $3::timestamptz
  AND proration_invoice_id IS NULL
  AND proration_skipped_at IS NULL
  AND deleted_at IS NULL
  AND created_at > $4::timestamptz
ORDER BY created_at
`

type PendingNewCreationChargesParams struct {
	AccountID   string    `json:"account_id"`
	PeriodStart time.Time `json:"period_start"`
	PeriodEnd   time.Time `json:"period_end"`
	GraceCutoff time.Time `json:"grace_cutoff"`
}

type PendingNewCreationChargesRow struct {
	AppID     string    `json:"app_id"`
	CreatedAt time.Time `json:"created_at"`
}

// PendingNewCreationCharges is the PENDING half of the ListNewCreationCharges read: apps
// CREATED in the resolved window that are STILL IN GRACE — not yet charged
// (proration_invoice_id IS NULL), still live (deleted_at IS NULL), not
// permanently skipped (proration_skipped_at IS NULL, migration 031), and whose
// creation grace has NOT yet elapsed (created_at > @grace_cutoff, the service's
// now − GraceDays, matching AppsPendingProration's cutoff from the other side).
// Only the CURRENT live window can hold in-grace apps (a past period's apps have
// all elapsed grace), so the service issues this query only for the current
// window. No money is derived here — the display shows the charge ETA
// (created_at + GraceDays), not an invented proration amount. Ordered by
// created_at (equivalently by the ETA) for a stable, soonest-first scan.
func (q *Queries) PendingNewCreationCharges(ctx context.Context, arg PendingNewCreationChargesParams) ([]PendingNewCreationChargesRow, error) {
	rows, err := q.db.Query(ctx, pendingNewCreationCharges,
		arg.AccountID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.GraceCutoff,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingNewCreationChargesRow{}
	for rows.Next() {
		var i PendingNewCreationChargesRow
		if err := rows.Scan(&i.AppID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectAppBaseSnapshot = `-- name: SelectAppBaseSnapshot :one
SELECT module_count, base_micros, source
FROM ms_billing.app_base_snapshots
WHERE app_id = $1
  AND period_start = $2
`

type SelectAppBaseSnapshotParams struct {
	AppID       string    `json:"app_id"`
	PeriodStart time.Time `json:"period_start"`
}

type SelectAppBaseSnapshotRow struct {
	ModuleCount int32  `json:"module_count"`
	BaseMicros  int64  `json:"base_micros"`
	Source      string `json:"source"`
}

// SelectAppBaseSnapshot reads the frozen base charge for ONE (app, period) —
// the display read behind GetAppBill's 基本費用 for a charged period. Exact
// period_start match (both writers key on the anchored window start); no row
// means the period was never base-charged and the caller falls back to the
// live-count display estimate.
func (q *Queries) SelectAppBaseSnapshot(ctx context.Context, arg SelectAppBaseSnapshotParams) (SelectAppBaseSnapshotRow, error) {
	row := q.db.QueryRow(ctx, selectAppBaseSnapshot, arg.AppID, arg.PeriodStart)
	var i SelectAppBaseSnapshotRow
	err := row.Scan(&i.ModuleCount, &i.BaseMicros, &i.Source)
	return i, err
}

const selectAppMirror = `-- name: SelectAppMirror :one
SELECT app_id, account_id, module_count, created_module_count, created_at, name,
       proration_invoice_id, proration_skipped_at, proration_attempted_at, deleted_at
FROM ms_billing.apps
WHERE app_id = $1
`

type SelectAppMirrorRow struct {
	AppID                string             `json:"app_id"`
	AccountID            pgtype.UUID        `json:"account_id"`
	ModuleCount          int32              `json:"module_count"`
	CreatedModuleCount   int32              `json:"created_module_count"`
	CreatedAt            time.Time          `json:"created_at"`
	Name                 pgtype.Text        `json:"name"`
	ProrationInvoiceID   pgtype.Text        `json:"proration_invoice_id"`
	ProrationSkippedAt   pgtype.Timestamptz `json:"proration_skipped_at"`
	ProrationAttemptedAt pgtype.Timestamptz `json:"proration_attempted_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
}

// SelectAppMirror reads one roster row (deleted or not — the caller decides
// what deletion means for its path: SyncAppModules no-ops a count update,
// GetAppBill still displays the spent creation-period base).
func (q *Queries) SelectAppMirror(ctx context.Context, appID string) (SelectAppMirrorRow, error) {
	row := q.db.QueryRow(ctx, selectAppMirror, appID)
	var i SelectAppMirrorRow
	err := row.Scan(
		&i.AppID,
		&i.AccountID,
		&i.ModuleCount,
		&i.CreatedModuleCount,
		&i.CreatedAt,
		&i.Name,
		&i.ProrationInvoiceID,
		&i.ProrationSkippedAt,
		&i.ProrationAttemptedAt,
		&i.DeletedAt,
	)
	return i, err
}

const selectAppMirrorForUpdate = `-- name: SelectAppMirrorForUpdate :one
SELECT app_id, account_id, module_count, created_module_count, created_at, name,
       proration_invoice_id, proration_skipped_at, proration_attempted_at, deleted_at
FROM ms_billing.apps
WHERE app_id = $1
FOR UPDATE
`

type SelectAppMirrorForUpdateRow struct {
	AppID                string             `json:"app_id"`
	AccountID            pgtype.UUID        `json:"account_id"`
	ModuleCount          int32              `json:"module_count"`
	CreatedModuleCount   int32              `json:"created_module_count"`
	CreatedAt            time.Time          `json:"created_at"`
	Name                 pgtype.Text        `json:"name"`
	ProrationInvoiceID   pgtype.Text        `json:"proration_invoice_id"`
	ProrationSkippedAt   pgtype.Timestamptz `json:"proration_skipped_at"`
	ProrationAttemptedAt pgtype.Timestamptz `json:"proration_attempted_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
}

// SelectAppMirrorForUpdate reads one roster row under a ROW LOCK (FOR UPDATE) —
// the creation-proration charge's race-safety primitive. The charge locks the
// row here just long enough to re-verify deleted_at IS NULL and
// proration_invoice_id IS NULL and read the frozen created_module_count,
// releasing the lock immediately after (ChargeProrationLocked runs the actual
// Stripe network call OUTSIDE this lock — see store.go); a concurrent
// SyncAppModules soft-delete (MarkAppDeleted) only ever contends for the brief
// read, never for the duration of a Stripe HTTP call.
func (q *Queries) SelectAppMirrorForUpdate(ctx context.Context, appID string) (SelectAppMirrorForUpdateRow, error) {
	row := q.db.QueryRow(ctx, selectAppMirrorForUpdate, appID)
	var i SelectAppMirrorForUpdateRow
	err := row.Scan(
		&i.AppID,
		&i.AccountID,
		&i.ModuleCount,
		&i.CreatedModuleCount,
		&i.CreatedAt,
		&i.Name,
		&i.ProrationInvoiceID,
		&i.ProrationSkippedAt,
		&i.ProrationAttemptedAt,
		&i.DeletedAt,
	)
	return i, err
}

const setAppModuleCount = `-- name: SetAppModuleCount :execrows
UPDATE ms_billing.apps
SET module_count = $2
WHERE app_id = $1
  AND deleted_at IS NULL
`

type SetAppModuleCountParams struct {
	AppID       string `json:"app_id"`
	ModuleCount int32  `json:"module_count"`
}

// SetAppModuleCount snapshots a new installed-module count (SyncAppModules).
// WHERE deleted_at IS NULL makes a count update on a deleted app a no-op
// (D1e — a deleted app accrues no future base, so its count is frozen).
// :execrows; the service resolves 0 rows via the SelectAppMirror existence
// check it already performed (unknown app → NOT_FOUND, deleted app → no-op).
func (q *Queries) SetAppModuleCount(ctx context.Context, arg SetAppModuleCountParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAppModuleCount, arg.AppID, arg.ModuleCount)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAppName = `-- name: SetAppName :execrows
UPDATE ms_billing.apps
SET name = $2
WHERE app_id = $1
  AND deleted_at IS NULL
`

type SetAppNameParams struct {
	AppID string      `json:"app_id"`
	Name  pgtype.Text `json:"name"`
}

// SetAppName updates the frozen display name (SyncAppModules rename path).
// WHERE deleted_at IS NULL freezes the name once deleted — the same
// freeze-on-delete posture as SetAppModuleCount, so a rename after deletion is
// a documented no-op (0 rows), keeping the last-known name for the bill.
func (q *Queries) SetAppName(ctx context.Context, arg SetAppNameParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAppName, arg.AppID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAppProrationInvoice = `-- name: SetAppProrationInvoice :execrows
UPDATE ms_billing.apps
SET proration_invoice_id = $2
WHERE app_id = $1
  AND proration_invoice_id IS NULL
`

type SetAppProrationInvoiceParams struct {
	AppID              string      `json:"app_id"`
	ProrationInvoiceID pgtype.Text `json:"proration_invoice_id"`
}

// SetAppProrationInvoice arms the ONE-SHOT proration guard: it records the
// Stripe invoice id of the creation-proration charge, and the WHERE
// proration_invoice_id IS NULL makes the write first-charge-wins — a retry or
// concurrent double-fire affects 0 rows and the original invoice id survives.
// :execrows so the caller can observe (and tolerate) the already-set case.
func (q *Queries) SetAppProrationInvoice(ctx context.Context, arg SetAppProrationInvoiceParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAppProrationInvoice, arg.AppID, arg.ProrationInvoiceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAppProrationSkipped = `-- name: SetAppProrationSkipped :execrows
UPDATE ms_billing.apps
SET proration_skipped_at = now()
WHERE app_id = $1
  AND proration_skipped_at IS NULL
  AND proration_invoice_id IS NULL
`

// SetAppProrationSkipped arms the PERMANENT skip marker (migration 031, D1d):
// the account only activated at/after this app's anchored creation period had
// already closed, so charging it now would be a retroactive catch-up. The
// WHERE clause makes it idempotent (a re-evaluation, or a concurrent one,
// affects 0 rows once set) and defensively refuses to mark an app that was
// somehow already charged in the meantime. :execrows so the caller can
// observe (and tolerate) the already-set / already-charged cases.
func (q *Queries) SetAppProrationSkipped(ctx context.Context, appID string) (int64, error) {
	result, err := q.db.Exec(ctx, setAppProrationSkipped, appID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const settledNewCreationCharges = `-- name: SettledNewCreationCharges :many
SELECT a.app_id,
       i.id AS invoice_id,
       i.number,
       i.amount_due,
       i.created_at AS recorded_at
FROM ms_billing.apps a
JOIN ms_billing.invoices i ON i.stripe_invoice_id = a.proration_invoice_id
WHERE a.account_id = $1::uuid
  AND a.created_at >= $2::timestamptz
  AND a.created_at < $3::timestamptz
  AND a.proration_invoice_id IS NOT NULL
  AND i.status <> 'void'
  AND i.amount_due > 0
ORDER BY i.created_at DESC, a.app_id
`

type SettledNewCreationChargesParams struct {
	AccountID   string    `json:"account_id"`
	PeriodStart time.Time `json:"period_start"`
	PeriodEnd   time.Time `json:"period_end"`
}

type SettledNewCreationChargesRow struct {
	AppID      string         `json:"app_id"`
	InvoiceID  string         `json:"invoice_id"`
	Number     pgtype.Text    `json:"number"`
	AmountDue  pgtype.Numeric `json:"amount_due"`
	RecordedAt time.Time      `json:"recorded_at"`
}

// SettledNewCreationCharges is the SETTLED half of the ListNewCreationCharges read (the
// web-account bill's 本期新建立 / "new this period" section): every app CREATED
// in the resolved window whose creation-proration leg has already minted its
// one invoice (proration_invoice_id armed, migration 027), joined to that
// invoice in the ms_billing.invoices mirror so the row carries the ACTUAL
// settled total — which may include co-created over-module line items billed on
// the SAME combined invoice (proration.go scenario 3), NOT just a base
// snapshot. Membership is the app's created_at ∈ [@period_start, @period_end);
// the join is 1:1 (stripe_invoice_id is unique in the mirror). The
// amount_due > 0 AND status <> 'void' filters drop a $0 / voided invoice —
// a skipped_period_closed / no_charge proration never arms proration_invoice_id
// at all (the guard stays NULL), so it is excluded by the join gate here rather
// than needing a status predicate. amount_due is NUMERIC whole cents (Stripe
// minor units); the store converts it to int64 micros (×10_000). Ordered by the
// invoice created_at DESC (the display's "recorded at", newest-first), app_id
// breaking ties for a deterministic scan.
func (q *Queries) SettledNewCreationCharges(ctx context.Context, arg SettledNewCreationChargesParams) ([]SettledNewCreationChargesRow, error) {
	rows, err := q.db.Query(ctx, settledNewCreationCharges, arg.AccountID, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SettledNewCreationChargesRow{}
	for rows.Next() {
		var i SettledNewCreationChargesRow
		if err := rows.Scan(
			&i.AppID,
			&i.InvoiceID,
			&i.Number,
			&i.AmountDue,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProrationBaseSnapshot = `-- name: UpsertProrationBaseSnapshot :exec
INSERT INTO ms_billing.app_base_snapshots
    (app_id, period_start, period_end, module_count, base_micros, source)
VALUES ($1, $2, $3, $4, $5, 'proration')
ON CONFLICT (app_id, period_start) DO UPDATE
SET period_end   = EXCLUDED.period_end,
    module_count = EXCLUDED.module_count,
    base_micros  = EXCLUDED.base_micros,
    source       = 'proration'
`

type UpsertProrationBaseSnapshotParams struct {
	AppID       string    `json:"app_id"`
	PeriodStart time.Time `json:"period_start"`
	PeriodEnd   time.Time `json:"period_end"`
	ModuleCount int32     `json:"module_count"`
	BaseMicros  int64     `json:"base_micros"`
}

// UpsertProrationBaseSnapshot records what RegisterApp's creation-proration
// leg billed one app for its creation period (migration 028). Keyed by the
// FULL anchored period_start (the display identity); base_micros is the
// PRORATED amount actually invoiced for the partial [creation-day,
// period_end) window. ON CONFLICT DO UPDATE so a retry is idempotent
// (identical values) and the proration row WINS over an 'advance' row if
// both somehow exist — the proration is the more specific charge for a
// creation period.
func (q *Queries) UpsertProrationBaseSnapshot(ctx context.Context, arg UpsertProrationBaseSnapshotParams) error {
	_, err := q.db.Exec(ctx, upsertProrationBaseSnapshot,
		arg.AppID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.ModuleCount,
		arg.BaseMicros,
	)
	return err
}
