// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: apps.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAppMirror = `-- name: InsertAppMirror :execrows

INSERT INTO ms_billing.apps (app_id, account_id, module_count, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (app_id) DO NOTHING
`

type InsertAppMirrorParams struct {
	AppID       string    `json:"app_id"`
	AccountID   string    `json:"account_id"`
	ModuleCount int32     `json:"module_count"`
	CreatedAt   time.Time `json:"created_at"`
}

// Queries backing the ms_billing.apps mirror (migration 027) — the base-fee
// roster the RegisterApp / SyncAppModules RPCs write and the charge spine +
// GetAppBill read. Money never lives here; the table carries only existence,
// the installed-module-count snapshot, and the one-shot proration guard.
// InsertAppMirror registers an app row idempotently: ON CONFLICT (app_id) DO
// NOTHING so a RegisterApp retry (or a concurrent double-fire) never rewrites
// created_at / module_count / the proration guard of the original insert —
// the FIRST registration's values are the stable proration anchor. :execrows
// so the caller can tell a fresh insert (1) from a retry no-op (0), though
// both are success.
func (q *Queries) InsertAppMirror(ctx context.Context, arg InsertAppMirrorParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertAppMirror,
		arg.AppID,
		arg.AccountID,
		arg.ModuleCount,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const liveAppModuleCounts = `-- name: LiveAppModuleCounts :many
SELECT module_count
FROM ms_billing.apps
WHERE account_id = $1
  AND deleted_at IS NULL
`

// LiveAppModuleCounts returns the module_count of every LIVE (deleted_at IS
// NULL) app on the account — the boundary charge's advance-base input:
// advance base = Σ (BaseFee + Overage × max(0, module_count − included)).
// Deleted apps are excluded (D1e); an account with no rows (pre-backfill)
// sums to base 0 and keeps the pre-027 arrears-only invoice.
func (q *Queries) LiveAppModuleCounts(ctx context.Context, accountID string) ([]int32, error) {
	rows, err := q.db.Query(ctx, liveAppModuleCounts, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var module_count int32
		if err := rows.Scan(&module_count); err != nil {
			return nil, err
		}
		items = append(items, module_count)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAppDeleted = `-- name: MarkAppDeleted :execrows
UPDATE ms_billing.apps
SET deleted_at = now()
WHERE app_id = $1
  AND deleted_at IS NULL
`

// MarkAppDeleted soft-deletes the roster row out of future advance base fees.
// WHERE deleted_at IS NULL keeps the FIRST deletion instant (idempotent — a
// re-fire affects 0 rows and never moves the timestamp).
func (q *Queries) MarkAppDeleted(ctx context.Context, appID string) (int64, error) {
	result, err := q.db.Exec(ctx, markAppDeleted, appID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const selectAppMirror = `-- name: SelectAppMirror :one
SELECT app_id, account_id, module_count, created_at, proration_invoice_id, deleted_at
FROM ms_billing.apps
WHERE app_id = $1
`

type SelectAppMirrorRow struct {
	AppID              string             `json:"app_id"`
	AccountID          string             `json:"account_id"`
	ModuleCount        int32              `json:"module_count"`
	CreatedAt          time.Time          `json:"created_at"`
	ProrationInvoiceID pgtype.Text        `json:"proration_invoice_id"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

// SelectAppMirror reads one roster row (deleted or not — the caller decides
// what deletion means for its path: SyncAppModules no-ops a count update,
// GetAppBill still displays the spent creation-period base).
func (q *Queries) SelectAppMirror(ctx context.Context, appID string) (SelectAppMirrorRow, error) {
	row := q.db.QueryRow(ctx, selectAppMirror, appID)
	var i SelectAppMirrorRow
	err := row.Scan(
		&i.AppID,
		&i.AccountID,
		&i.ModuleCount,
		&i.CreatedAt,
		&i.ProrationInvoiceID,
		&i.DeletedAt,
	)
	return i, err
}

const setAppModuleCount = `-- name: SetAppModuleCount :execrows
UPDATE ms_billing.apps
SET module_count = $2
WHERE app_id = $1
  AND deleted_at IS NULL
`

type SetAppModuleCountParams struct {
	AppID       string `json:"app_id"`
	ModuleCount int32  `json:"module_count"`
}

// SetAppModuleCount snapshots a new installed-module count (SyncAppModules).
// WHERE deleted_at IS NULL makes a count update on a deleted app a no-op
// (D1e — a deleted app accrues no future base, so its count is frozen).
// :execrows; the service resolves 0 rows via the SelectAppMirror existence
// check it already performed (unknown app → NOT_FOUND, deleted app → no-op).
func (q *Queries) SetAppModuleCount(ctx context.Context, arg SetAppModuleCountParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAppModuleCount, arg.AppID, arg.ModuleCount)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAppProrationInvoice = `-- name: SetAppProrationInvoice :execrows
UPDATE ms_billing.apps
SET proration_invoice_id = $2
WHERE app_id = $1
  AND proration_invoice_id IS NULL
`

type SetAppProrationInvoiceParams struct {
	AppID              string      `json:"app_id"`
	ProrationInvoiceID pgtype.Text `json:"proration_invoice_id"`
}

// SetAppProrationInvoice arms the ONE-SHOT proration guard: it records the
// Stripe invoice id of the creation-proration charge, and the WHERE
// proration_invoice_id IS NULL makes the write first-charge-wins — a retry or
// concurrent double-fire affects 0 rows and the original invoice id survives.
// :execrows so the caller can observe (and tolerate) the already-set case.
func (q *Queries) SetAppProrationInvoice(ctx context.Context, arg SetAppProrationInvoiceParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAppProrationInvoice, arg.AppID, arg.ProrationInvoiceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
