// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: billing.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const accountHasUnpaidInvoice = `-- name: AccountHasUnpaidInvoice :one
SELECT EXISTS (
    SELECT 1
    FROM ms_billing.invoices
    WHERE account_id = $1
      AND status IN ('open', 'uncollectible')
) AS has_unpaid
`

// AccountHasUnpaidInvoice is the delinquency predicate for Ensure: true when the
// account has at least one invoice in an unpaid, collection-relevant state.
// 'open' = finalized but payment not yet collected (a payment_failed leaves the
// invoice 'open' for Stripe's smart retries); 'uncollectible' = Stripe gave up.
// 'draft' is excluded (the charge spine hasn't finalized it; no collection
// attempt has been made). 'paid'/'void' are clean. Delinquency is DERIVED from
// invoice state, not a stored flag — the invoice mirror (reconciled by the
// invoice.* webhooks) is the single source of truth. The ENFORCEMENT policy
// (grace/suspend/prepaid) is PR #9; this only surfaces the signal.
func (q *Queries) AccountHasUnpaidInvoice(ctx context.Context, accountID string) (bool, error) {
	row := q.db.QueryRow(ctx, accountHasUnpaidInvoice, accountID)
	var has_unpaid bool
	err := row.Scan(&has_unpaid)
	return has_unpaid, err
}

const accountIDByUser = `-- name: AccountIDByUser :one
SELECT id FROM ms_billing.accounts
WHERE owner_kind = 'user' AND owner_user_id = $1
`

// AccountIDByUser returns just the account id for a user (read-only path
// where a missing row is a normal "missing billing_account" outcome).
func (q *Queries) AccountIDByUser(ctx context.Context, ownerUserID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, accountIDByUser, ownerUserID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const acquireBillingAccountUserLock = `-- name: AcquireBillingAccountUserLock :exec

SELECT pg_advisory_xact_lock($1::int, hashtext($2::text))
`

type AcquireBillingAccountUserLockParams struct {
	Column1 int32  `json:"column_1"`
	Column2 string `json:"column_2"`
}

// Queries backing internal/account/billing.pgxStore (the account-api
// Store interface). All operate on the ms_billing schema.
// AcquireBillingAccountUserLock serializes concurrent EnsureAccount
// calls per user. pg_advisory_xact_lock(namespace, key) is held for the
// enclosing transaction; the Go layer derives namespace + hashtext(key).
func (q *Queries) AcquireBillingAccountUserLock(ctx context.Context, arg AcquireBillingAccountUserLockParams) error {
	_, err := q.db.Exec(ctx, acquireBillingAccountUserLock, arg.Column1, arg.Column2)
	return err
}

const hasUsablePaymentMethod = `-- name: HasUsablePaymentMethod :one
SELECT EXISTS (
    SELECT 1
    FROM ms_billing.payment_methods_mirror
    WHERE account_id = $1
      AND deleted_at IS NULL
      AND (exp_year, exp_month) >= (
          EXTRACT(YEAR  FROM current_date)::INT,
          EXTRACT(MONTH FROM current_date)::INT
      )
) AS has
`

// HasUsablePaymentMethod is the hot-path Ensure predicate: at least one
// active (not soft-deleted) and not-expired mirror row on the account.
func (q *Queries) HasUsablePaymentMethod(ctx context.Context, accountID string) (bool, error) {
	row := q.db.QueryRow(ctx, hasUsablePaymentMethod, accountID)
	var has bool
	err := row.Scan(&has)
	return has, err
}

const insertUserAccount = `-- name: InsertUserAccount :one
INSERT INTO ms_billing.accounts (owner_kind, owner_user_id)
VALUES ('user', $1)
RETURNING id, COALESCE(stripe_customer_id, '')::text AS stripe_customer_id
`

type InsertUserAccountRow struct {
	ID               string `json:"id"`
	StripeCustomerID string `json:"stripe_customer_id"`
}

// InsertUserAccount creates a fresh user-owned account and returns the
// same projection as SelectAccountByUser (stripe_customer_id is ” on a
// fresh insert).
func (q *Queries) InsertUserAccount(ctx context.Context, ownerUserID pgtype.UUID) (InsertUserAccountRow, error) {
	row := q.db.QueryRow(ctx, insertUserAccount, ownerUserID)
	var i InsertUserAccountRow
	err := row.Scan(&i.ID, &i.StripeCustomerID)
	return i, err
}

const listPaymentMethods = `-- name: ListPaymentMethods :many
SELECT id, stripe_payment_method_id, brand, last4, exp_month, exp_year, is_default
FROM ms_billing.payment_methods_mirror
WHERE account_id = $1 AND deleted_at IS NULL
ORDER BY attached_at DESC
`

type ListPaymentMethodsRow struct {
	ID                    string `json:"id"`
	StripePaymentMethodID string `json:"stripe_payment_method_id"`
	Brand                 string `json:"brand"`
	Last4                 string `json:"last4"`
	ExpMonth              int32  `json:"exp_month"`
	ExpYear               int32  `json:"exp_year"`
	IsDefault             bool   `json:"is_default"`
}

// ListPaymentMethods returns active payment methods for an account,
// newest-first.
func (q *Queries) ListPaymentMethods(ctx context.Context, accountID string) ([]ListPaymentMethodsRow, error) {
	rows, err := q.db.Query(ctx, listPaymentMethods, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentMethodsRow{}
	for rows.Next() {
		var i ListPaymentMethodsRow
		if err := rows.Scan(
			&i.ID,
			&i.StripePaymentMethodID,
			&i.Brand,
			&i.Last4,
			&i.ExpMonth,
			&i.ExpYear,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectAccountByUser = `-- name: SelectAccountByUser :one
SELECT id, COALESCE(stripe_customer_id, '')::text AS stripe_customer_id
FROM ms_billing.accounts
WHERE owner_kind = 'user' AND owner_user_id = $1
`

type SelectAccountByUserRow struct {
	ID               string `json:"id"`
	StripeCustomerID string `json:"stripe_customer_id"`
}

// SelectAccountByUser returns the existing account row for a user, with
// a non-null stripe_customer_id projection (COALESCE to ”).
func (q *Queries) SelectAccountByUser(ctx context.Context, ownerUserID pgtype.UUID) (SelectAccountByUserRow, error) {
	row := q.db.QueryRow(ctx, selectAccountByUser, ownerUserID)
	var i SelectAccountByUserRow
	err := row.Scan(&i.ID, &i.StripeCustomerID)
	return i, err
}

const setStripeCustomer = `-- name: SetStripeCustomer :execrows
UPDATE ms_billing.accounts SET stripe_customer_id = $2 WHERE id = $1
`

type SetStripeCustomerParams struct {
	ID               string      `json:"id"`
	StripeCustomerID pgtype.Text `json:"stripe_customer_id"`
}

// SetStripeCustomer associates a Stripe Customer ID with an account.
// :execrows so the caller can map 0 rows to ErrAccountNotFound.
func (q *Queries) SetStripeCustomer(ctx context.Context, arg SetStripeCustomerParams) (int64, error) {
	result, err := q.db.Exec(ctx, setStripeCustomer, arg.ID, arg.StripeCustomerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
