// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: budgets.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const appPeriodSpendMicros = `-- name: AppPeriodSpendMicros :one
SELECT COALESCE(SUM(e.value * COALESCE(md.unit_price_micros, 0)), 0)::numeric AS total_raw_cost_micros
FROM ms_billing.usage_events e
LEFT JOIN ms_billing.metric_definitions md
    ON md.module_id = e.module_id AND md.metric = e.metric
WHERE e.app_id = $1
  AND e.recorded_at >= $2
  AND e.recorded_at <  $3
`

type AppPeriodSpendMicrosParams struct {
	AppID        string    `json:"app_id"`
	RecordedAt   time.Time `json:"recorded_at"`
	RecordedAt_2 time.Time `json:"recorded_at_2"`
}

// AppPeriodSpendMicros sums the app's current-period spend in micro-dollars:
// Σ usage_events.value × metric_definitions.unit_price_micros for the app in
// [period_start, period_end). The LEFT JOIN + COALESCE(...,0) treats an
// undeclared/deleted metric's NULL price as zero contribution (cost-safe).
// Returns a NUMERIC the caller decodes with microsFromNumeric (the same
// single-rounding-point helper CurrentPeriodUsage uses). This is the SAME
// spend window GetUsageSummary shows the user (current calendar month).
func (q *Queries) AppPeriodSpendMicros(ctx context.Context, arg AppPeriodSpendMicrosParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, appPeriodSpendMicros, arg.AppID, arg.RecordedAt, arg.RecordedAt_2)
	var total_raw_cost_micros pgtype.Numeric
	err := row.Scan(&total_raw_cost_micros)
	return total_raw_cost_micros, err
}

const getBudget = `-- name: GetBudget :one
SELECT id, scope, scope_id, account_id, limit_micros, alert_percents, active, created_at, updated_at
FROM ms_billing.budgets
WHERE scope = $1 AND scope_id = $2
`

type GetBudgetParams struct {
	Scope   MsBillingBudgetScope `json:"scope"`
	ScopeID string               `json:"scope_id"`
}

// GetBudget resolves the budget for a (scope, scope_id), or no row when none
// exists. The ingest-path hook uses it to skip evaluation when an app has no
// budget; GetBudgetStatus uses it to read the cap + thresholds.
func (q *Queries) GetBudget(ctx context.Context, arg GetBudgetParams) (MsBillingBudget, error) {
	row := q.db.QueryRow(ctx, getBudget, arg.Scope, arg.ScopeID)
	var i MsBillingBudget
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ScopeID,
		&i.AccountID,
		&i.LimitMicros,
		&i.AlertPercents,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertBudgetAlert = `-- name: InsertBudgetAlert :execrows
INSERT INTO ms_billing.budget_alerts (
    budget_id, period_start, percent, spend_micros, limit_micros
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (budget_id, period_start, percent) DO NOTHING
`

type InsertBudgetAlertParams struct {
	BudgetID    string    `json:"budget_id"`
	PeriodStart time.Time `json:"period_start"`
	Percent     int32     `json:"percent"`
	SpendMicros int64     `json:"spend_micros"`
	LimitMicros int64     `json:"limit_micros"`
}

// InsertBudgetAlert records one threshold crossing, idempotent on
// (budget_id, period_start, percent). ON CONFLICT DO NOTHING makes a
// re-evaluation of the same crossing a no-op. :execrows so the caller can
// tell a fresh crossing (1) from an already-recorded one (0).
func (q *Queries) InsertBudgetAlert(ctx context.Context, arg InsertBudgetAlertParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertBudgetAlert,
		arg.BudgetID,
		arg.PeriodStart,
		arg.Percent,
		arg.SpendMicros,
		arg.LimitMicros,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listBudgetAlerts = `-- name: ListBudgetAlerts :many
SELECT id, budget_id, period_start, percent, spend_micros, limit_micros, fired_at
FROM ms_billing.budget_alerts
WHERE budget_id = $1 AND period_start = $2
ORDER BY percent
`

type ListBudgetAlertsParams struct {
	BudgetID    string    `json:"budget_id"`
	PeriodStart time.Time `json:"period_start"`
}

// ListBudgetAlerts returns a budget's recorded crossings for a period,
// ordered by threshold. Backs GetBudgetAlerts (api-platform in-app display).
func (q *Queries) ListBudgetAlerts(ctx context.Context, arg ListBudgetAlertsParams) ([]MsBillingBudgetAlert, error) {
	rows, err := q.db.Query(ctx, listBudgetAlerts, arg.BudgetID, arg.PeriodStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MsBillingBudgetAlert{}
	for rows.Next() {
		var i MsBillingBudgetAlert
		if err := rows.Scan(
			&i.ID,
			&i.BudgetID,
			&i.PeriodStart,
			&i.Percent,
			&i.SpendMicros,
			&i.LimitMicros,
			&i.FiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBudget = `-- name: UpsertBudget :one

INSERT INTO ms_billing.budgets (
    scope, scope_id, account_id, limit_micros, alert_percents, active
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (scope, scope_id)
DO UPDATE SET
    account_id     = EXCLUDED.account_id,
    limit_micros   = EXCLUDED.limit_micros,
    alert_percents = EXCLUDED.alert_percents,
    active         = EXCLUDED.active
RETURNING id, scope, scope_id, account_id, limit_micros, alert_percents, active, created_at, updated_at
`

type UpsertBudgetParams struct {
	Scope         MsBillingBudgetScope `json:"scope"`
	ScopeID       string               `json:"scope_id"`
	AccountID     pgtype.UUID          `json:"account_id"`
	LimitMicros   int64                `json:"limit_micros"`
	AlertPercents []int32              `json:"alert_percents"`
	Active        bool                 `json:"active"`
}

// Queries backing internal/account/budget.pgxStore (the per-app budget
// engine). All operate on the ms_billing schema (migrations 014 + 015).
//
// billing-engine is CANONICAL for budget config: api-platform writes a
// budget over SetBudget and reads status/alerts back; it never touches
// ms_billing SQL directly (trust boundary). v1 wires scope='app' only; the
// enum carries 'org'/'account' for forward-compat (rejected in Go for now).
// UpsertBudget writes one budget, keyed (scope, scope_id). SetBudget calls
// it; a re-set updates limit/alert_percents/active in place (account_id is
// updated too so a lazy budget backfills its account on conversion). Returns
// the row so the caller can echo the persisted (deduped+sorted) percents.
func (q *Queries) UpsertBudget(ctx context.Context, arg UpsertBudgetParams) (MsBillingBudget, error) {
	row := q.db.QueryRow(ctx, upsertBudget,
		arg.Scope,
		arg.ScopeID,
		arg.AccountID,
		arg.LimitMicros,
		arg.AlertPercents,
		arg.Active,
	)
	var i MsBillingBudget
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ScopeID,
		&i.AccountID,
		&i.LimitMicros,
		&i.AlertPercents,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
