// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: combined_proration_attempts.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const coCreatedOverModuleTimersForAttempt = `-- name: CoCreatedOverModuleTimersForAttempt :many
SELECT id
FROM (
    SELECT id, app_id, installed_at, grace_resolved, charge_attempted_at,
           row_number() OVER (ORDER BY installed_at, id) AS rn
    FROM ms_billing.app_module_overage_timers
    WHERE account_id = $1::uuid
      AND removed_at IS NULL
) ranked
WHERE app_id = $2::uuid
  AND installed_at = $3::timestamptz
  AND grace_resolved = false
  AND charge_attempted_at IS NULL
  AND rn > $4::int
ORDER BY installed_at, id
`

type CoCreatedOverModuleTimersForAttemptParams struct {
	AccountID       string    `json:"account_id"`
	AppID           string    `json:"app_id"`
	CreatedAt       time.Time `json:"created_at"`
	IncludedModules int32     `json:"included_modules"`
}

// CoCreatedOverModuleTimersForAttempt selects the fresh ownership set at one
// MVCC statement boundary. It deliberately excludes a timer whose standalone
// Leg-1 marker already won; the subsequent row-lock/recheck query closes the
// uncommitted-marker/removal race before the header is inserted.
func (q *Queries) CoCreatedOverModuleTimersForAttempt(ctx context.Context, arg CoCreatedOverModuleTimersForAttemptParams) ([]string, error) {
	rows, err := q.db.Query(ctx, coCreatedOverModuleTimersForAttempt,
		arg.AccountID,
		arg.AppID,
		arg.CreatedAt,
		arg.IncludedModules,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const combinedProrationAttemptTimerIDs = `-- name: CombinedProrationAttemptTimerIDs :many
SELECT timer_id
FROM ms_billing.app_combined_proration_attempt_timers
WHERE app_id = $1
ORDER BY timer_id
`

func (q *Queries) CombinedProrationAttemptTimerIDs(ctx context.Context, appID string) ([]string, error) {
	rows, err := q.db.Query(ctx, combinedProrationAttemptTimerIDs, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var timer_id string
		if err := rows.Scan(&timer_id); err != nil {
			return nil, err
		}
		items = append(items, timer_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCombinedProrationAttempt = `-- name: InsertCombinedProrationAttempt :exec
INSERT INTO ms_billing.app_combined_proration_attempts (
    app_id,
    account_id,
    charge_funding_account_id,
    charge_funding_generation,
    attempted_at,
    currency,
    base_charge_micros,
    base_charge_cents,
    module_charge_micros,
    module_charge_cents,
    timer_count,
    coverage_start,
    coverage_end,
    base_description,
    module_description,
    snapshot_period_start,
    snapshot_period_end,
    snapshot_base_micros,
    snapshot_module_count,
    straddle_period_start,
    straddle_period_end,
    straddle_base_micros
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4::uuid,
    $5::timestamptz,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12::timestamptz,
    $13::timestamptz,
    $14,
    $15,
    $16::timestamptz,
    $17::timestamptz,
    $18,
    $19,
    $20,
    $21,
    $22
)
`

type InsertCombinedProrationAttemptParams struct {
	AppID                   string             `json:"app_id"`
	AccountID               string             `json:"account_id"`
	ChargeFundingAccountID  string             `json:"charge_funding_account_id"`
	ChargeFundingGeneration string             `json:"charge_funding_generation"`
	AttemptedAt             time.Time          `json:"attempted_at"`
	Currency                string             `json:"currency"`
	BaseChargeMicros        int64              `json:"base_charge_micros"`
	BaseChargeCents         int64              `json:"base_charge_cents"`
	ModuleChargeMicros      int64              `json:"module_charge_micros"`
	ModuleChargeCents       int64              `json:"module_charge_cents"`
	TimerCount              int32              `json:"timer_count"`
	CoverageStart           time.Time          `json:"coverage_start"`
	CoverageEnd             time.Time          `json:"coverage_end"`
	BaseDescription         string             `json:"base_description"`
	ModuleDescription       string             `json:"module_description"`
	SnapshotPeriodStart     time.Time          `json:"snapshot_period_start"`
	SnapshotPeriodEnd       time.Time          `json:"snapshot_period_end"`
	SnapshotBaseMicros      int64              `json:"snapshot_base_micros"`
	SnapshotModuleCount     int32              `json:"snapshot_module_count"`
	StraddlePeriodStart     pgtype.Timestamptz `json:"straddle_period_start"`
	StraddlePeriodEnd       pgtype.Timestamptz `json:"straddle_period_end"`
	StraddleBaseMicros      pgtype.Int8        `json:"straddle_base_micros"`
}

// InsertCombinedProrationAttempt is called only while the owning app row is
// locked. No ON CONFLICT path is needed: a concurrent freezer must first take
// that same lock, then reads and returns the winning header.
func (q *Queries) InsertCombinedProrationAttempt(ctx context.Context, arg InsertCombinedProrationAttemptParams) error {
	_, err := q.db.Exec(ctx, insertCombinedProrationAttempt,
		arg.AppID,
		arg.AccountID,
		arg.ChargeFundingAccountID,
		arg.ChargeFundingGeneration,
		arg.AttemptedAt,
		arg.Currency,
		arg.BaseChargeMicros,
		arg.BaseChargeCents,
		arg.ModuleChargeMicros,
		arg.ModuleChargeCents,
		arg.TimerCount,
		arg.CoverageStart,
		arg.CoverageEnd,
		arg.BaseDescription,
		arg.ModuleDescription,
		arg.SnapshotPeriodStart,
		arg.SnapshotPeriodEnd,
		arg.SnapshotBaseMicros,
		arg.SnapshotModuleCount,
		arg.StraddlePeriodStart,
		arg.StraddlePeriodEnd,
		arg.StraddleBaseMicros,
	)
	return err
}

const insertCombinedProrationAttemptTimers = `-- name: InsertCombinedProrationAttemptTimers :exec
INSERT INTO ms_billing.app_combined_proration_attempt_timers (app_id, timer_id)
SELECT $1::uuid, selected.timer_id
FROM unnest($2::uuid[]) AS selected(timer_id)
`

type InsertCombinedProrationAttemptTimersParams struct {
	AppID    string   `json:"app_id"`
	TimerIds []string `json:"timer_ids"`
}

// InsertCombinedProrationAttemptTimers freezes all selected timer IDs in one
// statement. An empty array inserts zero rows and is the intentional-empty
// representation paired with the already-inserted header.
func (q *Queries) InsertCombinedProrationAttemptTimers(ctx context.Context, arg InsertCombinedProrationAttemptTimersParams) error {
	_, err := q.db.Exec(ctx, insertCombinedProrationAttemptTimers, arg.AppID, arg.TimerIds)
	return err
}

const lockCombinedProrationCandidateTimers = `-- name: LockCombinedProrationCandidateTimers :many
SELECT id, account_id, app_id, installed_at, removed_at, grace_resolved,
       charge_attempted_at
FROM ms_billing.app_module_overage_timers
WHERE id = ANY($1::uuid[])
ORDER BY id
FOR UPDATE
`

type LockCombinedProrationCandidateTimersRow struct {
	ID                string             `json:"id"`
	AccountID         string             `json:"account_id"`
	AppID             string             `json:"app_id"`
	InstalledAt       time.Time          `json:"installed_at"`
	RemovedAt         pgtype.Timestamptz `json:"removed_at"`
	GraceResolved     bool               `json:"grace_resolved"`
	ChargeAttemptedAt pgtype.Timestamptz `json:"charge_attempted_at"`
}

// LockCombinedProrationCandidateTimers locks every selected row in stable UUID
// order and returns the chargeability facts for a post-lock recheck. A
// standalone marker/removal/resolution that committed after selection is
// therefore observed before the freeze can commit.
func (q *Queries) LockCombinedProrationCandidateTimers(ctx context.Context, timerIds []string) ([]LockCombinedProrationCandidateTimersRow, error) {
	rows, err := q.db.Query(ctx, lockCombinedProrationCandidateTimers, timerIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockCombinedProrationCandidateTimersRow{}
	for rows.Next() {
		var i LockCombinedProrationCandidateTimersRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.AppID,
			&i.InstalledAt,
			&i.RemovedAt,
			&i.GraceResolved,
			&i.ChargeAttemptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAppProrationAttemptedWithFreeze = `-- name: MarkAppProrationAttemptedWithFreeze :execrows
UPDATE ms_billing.apps
SET proration_attempted_at = $1::timestamptz
WHERE app_id = $2::uuid
  AND proration_attempted_at IS NULL
  AND proration_invoice_id IS NULL
  AND proration_skipped_at IS NULL
`

type MarkAppProrationAttemptedWithFreezeParams struct {
	AttemptedAt time.Time `json:"attempted_at"`
	AppID       string    `json:"app_id"`
}

// MarkAppProrationAttemptedWithFreeze stamps the legacy app recovery marker in
// the same transaction as the header + children. The locked row was already
// checked, but the guards make the invariant explicit and rows-affected lets
// the store reject an impossible split state.
func (q *Queries) MarkAppProrationAttemptedWithFreeze(ctx context.Context, arg MarkAppProrationAttemptedWithFreezeParams) (int64, error) {
	result, err := q.db.Exec(ctx, markAppProrationAttemptedWithFreeze, arg.AttemptedAt, arg.AppID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markCombinedProrationTimerCharged = `-- name: MarkCombinedProrationTimerCharged :execrows
UPDATE ms_billing.app_module_overage_timers timer
SET grace_resolved        = true,
    grace_charged_at      = $1::timestamptz,
    grace_invoice_id      = $2,
    grace_invoice_item_id = $3
WHERE timer.id = $4::uuid
  AND timer.grace_resolved = false
  AND EXISTS (
      SELECT 1
      FROM ms_billing.app_combined_proration_attempt_timers owned
      JOIN ms_billing.app_combined_proration_attempts attempt
        ON attempt.app_id = owned.app_id
      WHERE owned.app_id = $5::uuid
        AND owned.timer_id = timer.id
        AND attempt.resolved_invoice_id = $6
        AND attempt.resolved_at IS NOT NULL
  )
`

type MarkCombinedProrationTimerChargedParams struct {
	GraceChargedAt     time.Time   `json:"grace_charged_at"`
	GraceInvoiceID     pgtype.Text `json:"grace_invoice_id"`
	GraceInvoiceItemID pgtype.Text `json:"grace_invoice_item_id"`
	TimerID            string      `json:"timer_id"`
	AppID              string      `json:"app_id"`
	ResolvedInvoiceID  pgtype.Text `json:"resolved_invoice_id"`
}

// MarkCombinedProrationTimerCharged is the only terminal child writer for a
// frozen combined attempt. The header is resolved first in the SAME
// transaction, then this statement proves exact child membership and updates
// one still-unresolved timer. Resolving first is safe because no other
// transaction observes it until commit; it also lets the mixed-version DB
// guard reject legacy timer writers while allowing this owner transaction.
// rows-affected MUST be one for every frozen child or the caller rolls the
// whole header/app/timer terminal transaction back.
func (q *Queries) MarkCombinedProrationTimerCharged(ctx context.Context, arg MarkCombinedProrationTimerChargedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markCombinedProrationTimerCharged,
		arg.GraceChargedAt,
		arg.GraceInvoiceID,
		arg.GraceInvoiceItemID,
		arg.TimerID,
		arg.AppID,
		arg.ResolvedInvoiceID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resolveCombinedProrationAttempt = `-- name: ResolveCombinedProrationAttempt :execrows
UPDATE ms_billing.app_combined_proration_attempts
SET resolved_at = COALESCE(resolved_at, $1::timestamptz),
    resolved_invoice_id = COALESCE(resolved_invoice_id, $2)
WHERE app_id = $3::uuid
  AND (
      resolved_invoice_id IS NULL
      OR resolved_invoice_id = $2
  )
`

type ResolveCombinedProrationAttemptParams struct {
	ResolvedAt        time.Time   `json:"resolved_at"`
	ResolvedInvoiceID pgtype.Text `json:"resolved_invoice_id"`
	AppID             string      `json:"app_id"`
}

// ResolveCombinedProrationAttempt is part of the same transaction that mirrors
// the invoice, arms apps.proration_invoice_id, and marks every frozen timer.
// A retry may reapply the exact same invoice id; a different id is rejected.
func (q *Queries) ResolveCombinedProrationAttempt(ctx context.Context, arg ResolveCombinedProrationAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, resolveCombinedProrationAttempt, arg.ResolvedAt, arg.ResolvedInvoiceID, arg.AppID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const selectCombinedProrationAttempt = `-- name: SelectCombinedProrationAttempt :one

SELECT app_id,
       account_id,
       charge_funding_account_id,
       charge_funding_generation,
       attempted_at,
       currency,
       base_charge_micros,
       base_charge_cents,
       module_charge_micros,
       module_charge_cents,
       timer_count,
       coverage_start,
       coverage_end,
       base_description,
       module_description,
       snapshot_period_start,
       snapshot_period_end,
       snapshot_base_micros,
       snapshot_module_count,
       straddle_period_start,
       straddle_period_end,
       straddle_base_micros,
       resolved_at,
       resolved_invoice_id
FROM ms_billing.app_combined_proration_attempts
WHERE app_id = $1
FOR UPDATE
`

type SelectCombinedProrationAttemptRow struct {
	AppID                   string             `json:"app_id"`
	AccountID               string             `json:"account_id"`
	ChargeFundingAccountID  pgtype.UUID        `json:"charge_funding_account_id"`
	ChargeFundingGeneration pgtype.UUID        `json:"charge_funding_generation"`
	AttemptedAt             time.Time          `json:"attempted_at"`
	Currency                string             `json:"currency"`
	BaseChargeMicros        int64              `json:"base_charge_micros"`
	BaseChargeCents         int64              `json:"base_charge_cents"`
	ModuleChargeMicros      int64              `json:"module_charge_micros"`
	ModuleChargeCents       int64              `json:"module_charge_cents"`
	TimerCount              int32              `json:"timer_count"`
	CoverageStart           time.Time          `json:"coverage_start"`
	CoverageEnd             time.Time          `json:"coverage_end"`
	BaseDescription         string             `json:"base_description"`
	ModuleDescription       string             `json:"module_description"`
	SnapshotPeriodStart     time.Time          `json:"snapshot_period_start"`
	SnapshotPeriodEnd       time.Time          `json:"snapshot_period_end"`
	SnapshotBaseMicros      int64              `json:"snapshot_base_micros"`
	SnapshotModuleCount     int32              `json:"snapshot_module_count"`
	StraddlePeriodStart     pgtype.Timestamptz `json:"straddle_period_start"`
	StraddlePeriodEnd       pgtype.Timestamptz `json:"straddle_period_end"`
	StraddleBaseMicros      pgtype.Int8        `json:"straddle_base_micros"`
	ResolvedAt              pgtype.Timestamptz `json:"resolved_at"`
	ResolvedInvoiceID       pgtype.Text        `json:"resolved_invoice_id"`
}

// Durable ownership for the combined app-creation Stripe charge (migration
// 050). The header is the "known set" bit: zero child rows is an intentionally
// empty timer set, while an app attempt marker without a header is legacy /
// incomplete state and must be rejected by the service.
// SelectCombinedProrationAttempt reads the immutable request/snapshot shape
// plus terminal state. Child IDs are read separately so an empty set remains
// distinguishable from no header.
func (q *Queries) SelectCombinedProrationAttempt(ctx context.Context, appID string) (SelectCombinedProrationAttemptRow, error) {
	row := q.db.QueryRow(ctx, selectCombinedProrationAttempt, appID)
	var i SelectCombinedProrationAttemptRow
	err := row.Scan(
		&i.AppID,
		&i.AccountID,
		&i.ChargeFundingAccountID,
		&i.ChargeFundingGeneration,
		&i.AttemptedAt,
		&i.Currency,
		&i.BaseChargeMicros,
		&i.BaseChargeCents,
		&i.ModuleChargeMicros,
		&i.ModuleChargeCents,
		&i.TimerCount,
		&i.CoverageStart,
		&i.CoverageEnd,
		&i.BaseDescription,
		&i.ModuleDescription,
		&i.SnapshotPeriodStart,
		&i.SnapshotPeriodEnd,
		&i.SnapshotBaseMicros,
		&i.SnapshotModuleCount,
		&i.StraddlePeriodStart,
		&i.StraddlePeriodEnd,
		&i.StraddleBaseMicros,
		&i.ResolvedAt,
		&i.ResolvedInvoiceID,
	)
	return i, err
}

const timerHasUnresolvedCombinedProrationOwner = `-- name: TimerHasUnresolvedCombinedProrationOwner :one
SELECT EXISTS (
    SELECT 1
    FROM ms_billing.app_combined_proration_attempt_timers t
    JOIN ms_billing.app_combined_proration_attempts a
      ON a.app_id = t.app_id
    WHERE t.timer_id = $1
      AND a.resolved_at IS NULL
)::bool
`

// TimerHasUnresolvedCombinedProrationOwner is the durable ownership guard used
// by standalone timer paths before any live-rank or wallet/Stripe claim.
func (q *Queries) TimerHasUnresolvedCombinedProrationOwner(ctx context.Context, timerID string) (bool, error) {
	row := q.db.QueryRow(ctx, timerHasUnresolvedCombinedProrationOwner, timerID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const unresolvedCombinedProrationAttempts = `-- name: UnresolvedCombinedProrationAttempts :many
SELECT a.app_id,
       a.account_id,
       a.base_charge_micros,
       a.module_charge_micros,
       a.timer_count,
       count(t.timer_id)::bigint AS frozen_timer_count
FROM ms_billing.app_combined_proration_attempts a
LEFT JOIN ms_billing.app_combined_proration_attempt_timers t
  ON t.app_id = a.app_id
WHERE a.account_id = $1
  AND a.resolved_at IS NULL
GROUP BY a.app_id,
         a.account_id,
         a.base_charge_micros,
         a.module_charge_micros,
         a.timer_count
ORDER BY a.app_id
`

type UnresolvedCombinedProrationAttemptsRow struct {
	AppID              string `json:"app_id"`
	AccountID          string `json:"account_id"`
	BaseChargeMicros   int64  `json:"base_charge_micros"`
	ModuleChargeMicros int64  `json:"module_charge_micros"`
	TimerCount         int32  `json:"timer_count"`
	FrozenTimerCount   int64  `json:"frozen_timer_count"`
}

// UnresolvedCombinedProrationAttempts exposes exact raw money for the strict
// bill/runtime projection. The service verifies frozen_timer_count equals
// timer_count; a mismatch is corruption and must fail closed, never understate.
func (q *Queries) UnresolvedCombinedProrationAttempts(ctx context.Context, accountID string) ([]UnresolvedCombinedProrationAttemptsRow, error) {
	rows, err := q.db.Query(ctx, unresolvedCombinedProrationAttempts, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnresolvedCombinedProrationAttemptsRow{}
	for rows.Next() {
		var i UnresolvedCombinedProrationAttemptsRow
		if err := rows.Scan(
			&i.AppID,
			&i.AccountID,
			&i.BaseChargeMicros,
			&i.ModuleChargeMicros,
			&i.TimerCount,
			&i.FrozenTimerCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
