// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credit_wallet.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const armPendingCreditPurchase = `-- name: ArmPendingCreditPurchase :one
WITH target AS MATERIALIZED (
    SELECT purchase.id,
           purchase.account_id,
           purchase.charge_funding_account_id,
           purchase.charge_funding_generation,
           purchase.attempt_stripe_customer_id,
           purchase.stripe_invoice_id
    FROM ms_billing.credit_ledger purchase
    WHERE purchase.id = $1::uuid
      AND purchase.account_id = $2::uuid
      AND purchase.type = 'purchase'
      AND purchase.status = 'pending'
      AND NOT purchase.charge_funding_legacy_unresolved
    FOR UPDATE
), funding_authorization AS MATERIALIZED (
    SELECT target.id,
           funding_auth.funding_account_id,
           funding_auth.generation,
           funding.stripe_customer_id
    FROM target
    JOIN ms_billing.account_funding_authorizations funding_auth
      ON funding_auth.account_id = target.account_id
    JOIN ms_billing.accounts funding
      ON funding.id = funding_auth.funding_account_id
    WHERE target.charge_funding_account_id IS NULL
      AND target.charge_funding_generation IS NULL
      AND target.attempt_stripe_customer_id IS NULL
      AND target.stripe_invoice_id IS NULL
      AND NULLIF(BTRIM(funding.stripe_customer_id), '') IS NOT NULL
), claim AS MATERIALIZED (
    SELECT target.id,
           COALESCE(target.charge_funding_account_id,
                    funding_authorization.funding_account_id) AS funding_account_id,
           COALESCE(target.charge_funding_generation,
                    funding_authorization.generation) AS generation,
           COALESCE(target.attempt_stripe_customer_id,
                    funding_authorization.stripe_customer_id) AS stripe_customer_id
    FROM target
    LEFT JOIN funding_authorization
      ON funding_authorization.id = target.id
    WHERE (
        target.charge_funding_account_id IS NOT NULL
        AND target.charge_funding_generation IS NOT NULL
        AND NULLIF(BTRIM(target.attempt_stripe_customer_id), '') IS NOT NULL
    ) OR funding_authorization.id IS NOT NULL
), armed AS (
    UPDATE ms_billing.credit_ledger purchase
    SET charge_funding_account_id = claim.funding_account_id,
        charge_funding_generation = claim.generation,
        attempt_stripe_customer_id = claim.stripe_customer_id
    FROM claim
    WHERE purchase.id = claim.id
    RETURNING purchase.id, purchase.account_id, purchase.amount_micros, purchase.type, purchase.status, purchase.balance_after_micros, purchase.actor, purchase.idempotency_key, purchase.stripe_invoice_id, purchase.receipt_url, purchase.expires_at, purchase.period_id, purchase.source_credit_id, purchase.created_at, purchase.attempt_payment_method_id, purchase.attempt_stripe_payment_method_id, purchase.attempt_stripe_customer_id, purchase.attempt_expires_at, purchase.failure_code, purchase.charge_funding_account_id, purchase.charge_funding_generation, purchase.charge_funding_legacy_unresolved, purchase.proposed_reference
)
SELECT id,
       account_id,
       amount_micros,
       type,
       status,
       balance_after_micros,
       actor,
       COALESCE(idempotency_key, '')::text AS idempotency_key,
       COALESCE(stripe_invoice_id, '')::text AS stripe_invoice_id,
       COALESCE(receipt_url, '')::text AS receipt_url,
       charge_funding_account_id,
       charge_funding_generation,
       COALESCE(attempt_stripe_customer_id, '')::text AS attempt_stripe_customer_id,
       charge_funding_legacy_unresolved,
       created_at
FROM armed
`

type ArmPendingCreditPurchaseParams struct {
	PurchaseID string `json:"purchase_id"`
	AccountID  string `json:"account_id"`
}

type ArmPendingCreditPurchaseRow struct {
	ID                            string      `json:"id"`
	AccountID                     string      `json:"account_id"`
	AmountMicros                  int64       `json:"amount_micros"`
	Type                          string      `json:"type"`
	Status                        string      `json:"status"`
	BalanceAfterMicros            int64       `json:"balance_after_micros"`
	Actor                         string      `json:"actor"`
	IdempotencyKey                string      `json:"idempotency_key"`
	StripeInvoiceID               string      `json:"stripe_invoice_id"`
	ReceiptUrl                    string      `json:"receipt_url"`
	ChargeFundingAccountID        pgtype.UUID `json:"charge_funding_account_id"`
	ChargeFundingGeneration       pgtype.UUID `json:"charge_funding_generation"`
	AttemptStripeCustomerID       string      `json:"attempt_stripe_customer_id"`
	ChargeFundingLegacyUnresolved bool        `json:"charge_funding_legacy_unresolved"`
	CreatedAt                     time.Time   `json:"created_at"`
}

// ArmPendingCreditPurchase is the manual-purchase money boundary. It either
// reuses the row's immutable claim or snapshots the current rotating funding
// authorization plus its Stripe Customer in the same statement. The update
// trigger acquires both customer and funder lifecycle locks before this commit;
// no Stripe request may run until this row is returned.
func (q *Queries) ArmPendingCreditPurchase(ctx context.Context, arg ArmPendingCreditPurchaseParams) (ArmPendingCreditPurchaseRow, error) {
	row := q.db.QueryRow(ctx, armPendingCreditPurchase, arg.PurchaseID, arg.AccountID)
	var i ArmPendingCreditPurchaseRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.AmountMicros,
		&i.Type,
		&i.Status,
		&i.BalanceAfterMicros,
		&i.Actor,
		&i.IdempotencyKey,
		&i.StripeInvoiceID,
		&i.ReceiptUrl,
		&i.ChargeFundingAccountID,
		&i.ChargeFundingGeneration,
		&i.AttemptStripeCustomerID,
		&i.ChargeFundingLegacyUnresolved,
		&i.CreatedAt,
	)
	return i, err
}

const attachCreditPurchaseInvoice = `-- name: AttachCreditPurchaseInvoice :one
UPDATE ms_billing.credit_ledger
SET stripe_invoice_id = $1::text,
    receipt_url = COALESCE(
        NULLIF($2::text, ''),
        receipt_url
    )
WHERE id = $3::uuid
  AND account_id = $4::uuid
  AND type = 'purchase'
  AND status = 'pending'
  AND NOT charge_funding_legacy_unresolved
  AND charge_funding_account_id IS NOT NULL
  AND charge_funding_generation IS NOT NULL
  AND attempt_stripe_customer_id = $5::text
  AND (
      stripe_invoice_id IS NULL
      OR stripe_invoice_id = $1::text
  )
RETURNING
    id,
    account_id,
    amount_micros,
    type,
    status,
    balance_after_micros,
    actor,
    COALESCE(idempotency_key, '')::text AS idempotency_key,
    COALESCE(stripe_invoice_id, '')::text AS stripe_invoice_id,
    COALESCE(receipt_url, '')::text AS receipt_url,
    charge_funding_account_id,
    charge_funding_generation,
    COALESCE(attempt_stripe_customer_id, '')::text AS attempt_stripe_customer_id,
    charge_funding_legacy_unresolved,
    created_at
`

type AttachCreditPurchaseInvoiceParams struct {
	StripeInvoiceID  string `json:"stripe_invoice_id"`
	ReceiptUrl       string `json:"receipt_url"`
	PurchaseID       string `json:"purchase_id"`
	AccountID        string `json:"account_id"`
	StripeCustomerID string `json:"stripe_customer_id"`
}

type AttachCreditPurchaseInvoiceRow struct {
	ID                            string      `json:"id"`
	AccountID                     string      `json:"account_id"`
	AmountMicros                  int64       `json:"amount_micros"`
	Type                          string      `json:"type"`
	Status                        string      `json:"status"`
	BalanceAfterMicros            int64       `json:"balance_after_micros"`
	Actor                         string      `json:"actor"`
	IdempotencyKey                string      `json:"idempotency_key"`
	StripeInvoiceID               string      `json:"stripe_invoice_id"`
	ReceiptUrl                    string      `json:"receipt_url"`
	ChargeFundingAccountID        pgtype.UUID `json:"charge_funding_account_id"`
	ChargeFundingGeneration       pgtype.UUID `json:"charge_funding_generation"`
	AttemptStripeCustomerID       string      `json:"attempt_stripe_customer_id"`
	ChargeFundingLegacyUnresolved bool        `json:"charge_funding_legacy_unresolved"`
	CreatedAt                     time.Time   `json:"created_at"`
}

// AttachCreditPurchaseInvoice records Stripe's durable invoice identity and
// hosted URL without allowing a retry to replace an already-attached invoice.
// The Stripe call uses the same client idempotency key, so a legitimate retry
// resolves the same invoice id.
func (q *Queries) AttachCreditPurchaseInvoice(ctx context.Context, arg AttachCreditPurchaseInvoiceParams) (AttachCreditPurchaseInvoiceRow, error) {
	row := q.db.QueryRow(ctx, attachCreditPurchaseInvoice,
		arg.StripeInvoiceID,
		arg.ReceiptUrl,
		arg.PurchaseID,
		arg.AccountID,
		arg.StripeCustomerID,
	)
	var i AttachCreditPurchaseInvoiceRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.AmountMicros,
		&i.Type,
		&i.Status,
		&i.BalanceAfterMicros,
		&i.Actor,
		&i.IdempotencyKey,
		&i.StripeInvoiceID,
		&i.ReceiptUrl,
		&i.ChargeFundingAccountID,
		&i.ChargeFundingGeneration,
		&i.AttemptStripeCustomerID,
		&i.ChargeFundingLegacyUnresolved,
		&i.CreatedAt,
	)
	return i, err
}

const finalizeCreditPurchase = `-- name: FinalizeCreditPurchase :one
UPDATE ms_billing.credit_ledger
SET status = $1::text,
    balance_after_micros = $2::bigint,
    receipt_url = COALESCE(
        NULLIF($3::text, ''),
        receipt_url
    )
WHERE id = $4::uuid
  AND account_id = $5::uuid
  AND type = 'purchase'
  AND status = 'pending'
  AND $1::text IN ('settled', 'failed')
RETURNING
    id,
    account_id,
    amount_micros,
    type,
    status,
    balance_after_micros,
    actor,
    COALESCE(idempotency_key, '')::text AS idempotency_key,
    COALESCE(stripe_invoice_id, '')::text AS stripe_invoice_id,
    COALESCE(receipt_url, '')::text AS receipt_url,
    charge_funding_account_id,
    charge_funding_generation,
    COALESCE(attempt_stripe_customer_id, '')::text AS attempt_stripe_customer_id,
    charge_funding_legacy_unresolved,
    created_at
`

type FinalizeCreditPurchaseParams struct {
	Status             string `json:"status"`
	BalanceAfterMicros int64  `json:"balance_after_micros"`
	ReceiptUrl         string `json:"receipt_url"`
	PurchaseID         string `json:"purchase_id"`
	AccountID          string `json:"account_id"`
}

type FinalizeCreditPurchaseRow struct {
	ID                            string      `json:"id"`
	AccountID                     string      `json:"account_id"`
	AmountMicros                  int64       `json:"amount_micros"`
	Type                          string      `json:"type"`
	Status                        string      `json:"status"`
	BalanceAfterMicros            int64       `json:"balance_after_micros"`
	Actor                         string      `json:"actor"`
	IdempotencyKey                string      `json:"idempotency_key"`
	StripeInvoiceID               string      `json:"stripe_invoice_id"`
	ReceiptUrl                    string      `json:"receipt_url"`
	ChargeFundingAccountID        pgtype.UUID `json:"charge_funding_account_id"`
	ChargeFundingGeneration       pgtype.UUID `json:"charge_funding_generation"`
	AttemptStripeCustomerID       string      `json:"attempt_stripe_customer_id"`
	ChargeFundingLegacyUnresolved bool        `json:"charge_funding_legacy_unresolved"`
	CreatedAt                     time.Time   `json:"created_at"`
}

// FinalizeCreditPurchase is the sole purchase status transition primitive.
// Only pending rows may move, and the target is constrained to the two terminal
// outcomes accepted by the RPC. Retrying a terminal result is a read through
// GetCreditPurchaseByID, never a second balance mutation.
func (q *Queries) FinalizeCreditPurchase(ctx context.Context, arg FinalizeCreditPurchaseParams) (FinalizeCreditPurchaseRow, error) {
	row := q.db.QueryRow(ctx, finalizeCreditPurchase,
		arg.Status,
		arg.BalanceAfterMicros,
		arg.ReceiptUrl,
		arg.PurchaseID,
		arg.AccountID,
	)
	var i FinalizeCreditPurchaseRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.AmountMicros,
		&i.Type,
		&i.Status,
		&i.BalanceAfterMicros,
		&i.Actor,
		&i.IdempotencyKey,
		&i.StripeInvoiceID,
		&i.ReceiptUrl,
		&i.ChargeFundingAccountID,
		&i.ChargeFundingGeneration,
		&i.AttemptStripeCustomerID,
		&i.ChargeFundingLegacyUnresolved,
		&i.CreatedAt,
	)
	return i, err
}

const getCreditAccountSnapshot = `-- name: GetCreditAccountSnapshot :one
SELECT
    account.id,
    account.owner_user_id,
    account.owner_org_id,
    account.billing_mode,
    account.credit_limit_micros,
    account.activated_at
FROM ms_billing.accounts account
WHERE account.id = $1::uuid
`

type GetCreditAccountSnapshotRow struct {
	ID                string             `json:"id"`
	OwnerUserID       pgtype.UUID        `json:"owner_user_id"`
	OwnerOrgID        pgtype.UUID        `json:"owner_org_id"`
	BillingMode       string             `json:"billing_mode"`
	CreditLimitMicros int64              `json:"credit_limit_micros"`
	ActivatedAt       pgtype.Timestamptz `json:"activated_at"`
}

// GetCreditAccountSnapshot classifies the account before any ledger read.
// A standard account returns from the Go provider after this query, keeping
// credit_ledger completely untouched on that path.
func (q *Queries) GetCreditAccountSnapshot(ctx context.Context, accountID string) (GetCreditAccountSnapshotRow, error) {
	row := q.db.QueryRow(ctx, getCreditAccountSnapshot, accountID)
	var i GetCreditAccountSnapshotRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.OwnerOrgID,
		&i.BillingMode,
		&i.CreditLimitMicros,
		&i.ActivatedAt,
	)
	return i, err
}

const getCreditGateState = `-- name: GetCreditGateState :one
WITH source_lots AS (
    SELECT
        source.id,
        source.expires_at,
        (
            source.amount_micros::numeric
            + COALESCE((
                SELECT SUM(draw.amount_micros)
                FROM ms_billing.credit_ledger draw
                WHERE draw.source_credit_id = source.id
                  AND draw.account_id = source.account_id
                  AND draw.status = 'settled'
                  AND draw.type IN ('usage_draw', 'subscription_draw')
            ), 0)
        ) AS remaining_micros
    FROM ms_billing.credit_ledger source
    WHERE source.account_id = $1::uuid
      AND source.status = 'settled'
      AND source.amount_micros > 0
      AND source.type IN (
          'grant', 'preallocation', 'refund', 'adjustment',
          'purchase', 'auto_topup'
      )
), balances AS (
    SELECT
        COALESCE((
            SELECT SUM(entry.amount_micros)
            FROM ms_billing.credit_ledger entry
            WHERE entry.account_id = $1::uuid
              AND entry.status = 'settled'
        ), 0) AS settled_micros,
        COALESCE((
            SELECT SUM(lot.remaining_micros)
            FROM source_lots lot
            WHERE lot.remaining_micros > 0
              AND (lot.expires_at IS NULL OR lot.expires_at > CURRENT_TIMESTAMP)
        ), 0) AS lot_micros,
        COALESCE((
            SELECT SUM(lot.remaining_micros)
            FROM source_lots lot
            WHERE lot.remaining_micros > 0
              AND lot.expires_at <= CURRENT_TIMESTAMP
        ), 0) AS expired_lot_micros
)
SELECT
    balances.settled_micros::bigint AS settled_balance_micros,
    GREATEST(
        LEAST(
            balances.lot_micros,
            GREATEST(
                balances.settled_micros - balances.expired_lot_micros,
                0
            )
        ),
        0
    )::bigint AS spendable_balance_micros,
    EXISTS (
        SELECT 1
        FROM ms_billing.credit_ledger pending
        WHERE pending.account_id = $1::uuid
          AND pending.type = 'auto_topup'
          AND pending.status = 'pending'
    )::boolean AS auto_topup_attempt_pending,
    EXISTS (
        SELECT 1
        FROM ms_billing.credit_ledger pending
        WHERE pending.account_id = $1::uuid
          AND pending.type = 'auto_topup'
          AND pending.status = 'pending'
          AND pending.attempt_expires_at > CURRENT_TIMESTAMP
    )::boolean AS pending_auto_topup,
    COALESCE(config.enabled, false)::boolean AS auto_topup_enabled,
    COALESCE(config.threshold_micros, 0)::bigint AS auto_topup_threshold_micros
FROM balances
LEFT JOIN ms_billing.credit_auto_topup_configs config
       ON config.account_id = $1::uuid
`

type GetCreditGateStateRow struct {
	SettledBalanceMicros     int64 `json:"settled_balance_micros"`
	SpendableBalanceMicros   int64 `json:"spendable_balance_micros"`
	AutoTopupAttemptPending  bool  `json:"auto_topup_attempt_pending"`
	PendingAutoTopup         bool  `json:"pending_auto_topup"`
	AutoTopupEnabled         bool  `json:"auto_topup_enabled"`
	AutoTopupThresholdMicros int64 `json:"auto_topup_threshold_micros"`
}

// GetCreditGateState mirrors WalletCreditState's spendable-balance predicate:
// active positive lot remainder, capped by posted balance after expired lot
// remainder is removed. Pending manual purchases are neither settled balance
// nor grace; only a durable pending auto_topup suppresses the real-time block.
func (q *Queries) GetCreditGateState(ctx context.Context, accountID string) (GetCreditGateStateRow, error) {
	row := q.db.QueryRow(ctx, getCreditGateState, accountID)
	var i GetCreditGateStateRow
	err := row.Scan(
		&i.SettledBalanceMicros,
		&i.SpendableBalanceMicros,
		&i.AutoTopupAttemptPending,
		&i.PendingAutoTopup,
		&i.AutoTopupEnabled,
		&i.AutoTopupThresholdMicros,
	)
	return i, err
}

const getCreditLedgerEntryByIdempotencyKey = `-- name: GetCreditLedgerEntryByIdempotencyKey :one
SELECT
    id,
    account_id,
    amount_micros,
    type,
    status,
    balance_after_micros,
    actor,
    COALESCE(idempotency_key, '')::text AS idempotency_key,
    COALESCE(stripe_invoice_id, '')::text AS stripe_invoice_id,
    COALESCE(receipt_url, '')::text AS receipt_url,
    charge_funding_account_id,
    charge_funding_generation,
    COALESCE(attempt_stripe_customer_id, '')::text AS attempt_stripe_customer_id,
    charge_funding_legacy_unresolved,
    expires_at,
    created_at
FROM ms_billing.credit_ledger
WHERE idempotency_key = $1::text
`

type GetCreditLedgerEntryByIdempotencyKeyRow struct {
	ID                            string             `json:"id"`
	AccountID                     string             `json:"account_id"`
	AmountMicros                  int64              `json:"amount_micros"`
	Type                          string             `json:"type"`
	Status                        string             `json:"status"`
	BalanceAfterMicros            int64              `json:"balance_after_micros"`
	Actor                         string             `json:"actor"`
	IdempotencyKey                string             `json:"idempotency_key"`
	StripeInvoiceID               string             `json:"stripe_invoice_id"`
	ReceiptUrl                    string             `json:"receipt_url"`
	ChargeFundingAccountID        pgtype.UUID        `json:"charge_funding_account_id"`
	ChargeFundingGeneration       pgtype.UUID        `json:"charge_funding_generation"`
	AttemptStripeCustomerID       string             `json:"attempt_stripe_customer_id"`
	ChargeFundingLegacyUnresolved bool               `json:"charge_funding_legacy_unresolved"`
	ExpiresAt                     pgtype.Timestamptz `json:"expires_at"`
	CreatedAt                     time.Time          `json:"created_at"`
}

// GetCreditLedgerEntryByIdempotencyKey resolves the migration-048 global
// idempotency boundary. It intentionally returns ownership, amount, type,
// actor, and expiry so callers can reject key reuse with different semantics
// without disclosing or mutating the conflicting row.
func (q *Queries) GetCreditLedgerEntryByIdempotencyKey(ctx context.Context, idempotencyKey string) (GetCreditLedgerEntryByIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getCreditLedgerEntryByIdempotencyKey, idempotencyKey)
	var i GetCreditLedgerEntryByIdempotencyKeyRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.AmountMicros,
		&i.Type,
		&i.Status,
		&i.BalanceAfterMicros,
		&i.Actor,
		&i.IdempotencyKey,
		&i.StripeInvoiceID,
		&i.ReceiptUrl,
		&i.ChargeFundingAccountID,
		&i.ChargeFundingGeneration,
		&i.AttemptStripeCustomerID,
		&i.ChargeFundingLegacyUnresolved,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCreditPurchaseByID = `-- name: GetCreditPurchaseByID :one
SELECT
    id,
    account_id,
    amount_micros,
    type,
    status,
    balance_after_micros,
    actor,
    COALESCE(idempotency_key, '')::text AS idempotency_key,
    COALESCE(stripe_invoice_id, '')::text AS stripe_invoice_id,
    COALESCE(receipt_url, '')::text AS receipt_url,
    charge_funding_account_id,
    charge_funding_generation,
    COALESCE(attempt_stripe_customer_id, '')::text AS attempt_stripe_customer_id,
    charge_funding_legacy_unresolved,
    created_at
FROM ms_billing.credit_ledger
WHERE id = $1::uuid
  AND account_id = $2::uuid
  AND type = 'purchase'
FOR UPDATE
`

type GetCreditPurchaseByIDParams struct {
	PurchaseID string `json:"purchase_id"`
	AccountID  string `json:"account_id"`
}

type GetCreditPurchaseByIDRow struct {
	ID                            string      `json:"id"`
	AccountID                     string      `json:"account_id"`
	AmountMicros                  int64       `json:"amount_micros"`
	Type                          string      `json:"type"`
	Status                        string      `json:"status"`
	BalanceAfterMicros            int64       `json:"balance_after_micros"`
	Actor                         string      `json:"actor"`
	IdempotencyKey                string      `json:"idempotency_key"`
	StripeInvoiceID               string      `json:"stripe_invoice_id"`
	ReceiptUrl                    string      `json:"receipt_url"`
	ChargeFundingAccountID        pgtype.UUID `json:"charge_funding_account_id"`
	ChargeFundingGeneration       pgtype.UUID `json:"charge_funding_generation"`
	AttemptStripeCustomerID       string      `json:"attempt_stripe_customer_id"`
	ChargeFundingLegacyUnresolved bool        `json:"charge_funding_legacy_unresolved"`
	CreatedAt                     time.Time   `json:"created_at"`
}

// GetCreditPurchaseByID scopes the Finish RPC handle to its owning account.
// FOR UPDATE stabilizes the pending status and presentment fields through a
// transaction that may post the purchase into the settled balance.
func (q *Queries) GetCreditPurchaseByID(ctx context.Context, arg GetCreditPurchaseByIDParams) (GetCreditPurchaseByIDRow, error) {
	row := q.db.QueryRow(ctx, getCreditPurchaseByID, arg.PurchaseID, arg.AccountID)
	var i GetCreditPurchaseByIDRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.AmountMicros,
		&i.Type,
		&i.Status,
		&i.BalanceAfterMicros,
		&i.Actor,
		&i.IdempotencyKey,
		&i.StripeInvoiceID,
		&i.ReceiptUrl,
		&i.ChargeFundingAccountID,
		&i.ChargeFundingGeneration,
		&i.AttemptStripeCustomerID,
		&i.ChargeFundingLegacyUnresolved,
		&i.CreatedAt,
	)
	return i, err
}

const getCreditStandingSnapshot = `-- name: GetCreditStandingSnapshot :one

SELECT
    account.billing_mode,
    account.credit_limit_micros,
    COALESCE((
        SELECT SUM(entry.amount_micros)
        FROM ms_billing.credit_ledger entry
        WHERE entry.account_id = account.id
          AND entry.status = 'settled'
    ), 0)::bigint AS balance_micros,
    (auto_topup.account_id IS NOT NULL)::boolean AS auto_topup_configured,
    COALESCE(auto_topup.enabled, false)::boolean AS auto_topup_enabled,
    COALESCE(auto_topup.threshold_micros, 0)::bigint AS auto_topup_threshold_micros,
    COALESCE(auto_topup.amount_micros, 0)::bigint AS auto_topup_amount_micros,
    COALESCE(auto_topup.payment_method_id::text, '')::text AS auto_topup_payment_method_id,
    COALESCE(last_attempt.status, '')::text AS auto_topup_last_attempt_status,
    COALESCE(last_attempt.failure_code, '')::text AS auto_topup_last_failure_code,
    last_attempt.attempt_expires_at AS auto_topup_pending_until
FROM ms_billing.accounts account
LEFT JOIN ms_billing.credit_auto_topup_configs auto_topup
       ON auto_topup.account_id = account.id
LEFT JOIN LATERAL (
    SELECT status, failure_code, attempt_expires_at
    FROM ms_billing.credit_ledger
    WHERE account_id = account.id
      AND type = 'auto_topup'
    ORDER BY created_at DESC, id DESC
    LIMIT 1
) last_attempt ON true
WHERE account.id = $1::uuid
`

type GetCreditStandingSnapshotRow struct {
	BillingMode                string             `json:"billing_mode"`
	CreditLimitMicros          int64              `json:"credit_limit_micros"`
	BalanceMicros              int64              `json:"balance_micros"`
	AutoTopupConfigured        bool               `json:"auto_topup_configured"`
	AutoTopupEnabled           bool               `json:"auto_topup_enabled"`
	AutoTopupThresholdMicros   int64              `json:"auto_topup_threshold_micros"`
	AutoTopupAmountMicros      int64              `json:"auto_topup_amount_micros"`
	AutoTopupPaymentMethodID   string             `json:"auto_topup_payment_method_id"`
	AutoTopupLastAttemptStatus string             `json:"auto_topup_last_attempt_status"`
	AutoTopupLastFailureCode   string             `json:"auto_topup_last_failure_code"`
	AutoTopupPendingUntil      pgtype.Timestamptz `json:"auto_topup_pending_until"`
}

// ---------------------------------------------------------------------------
// Credit-wallet RPC reads and writes.
//
// Mutating balance snapshots are serialized through LockCreditAccountBalance.
// The account-row FOR UPDATE lock also conflicts with the KEY SHARE lock taken
// by the credit_ledger account_id FK, so same-account journal INSERTs cannot
// race the balance read. Callers that transition an existing pending purchase
// additionally lock that ledger row through GetCreditPurchaseByID before using
// FinalizeCreditPurchase.
// ---------------------------------------------------------------------------
// GetCreditStandingSnapshot returns the durable wallet policy, authoritative
// posted balance, and optional auto-top-up config in one round-trip. The
// explicit configured bit distinguishes a missing config from a disabled row
// while keeping the remaining generated fields non-null and easy to map onto
// the optional RPC object.
func (q *Queries) GetCreditStandingSnapshot(ctx context.Context, accountID string) (GetCreditStandingSnapshotRow, error) {
	row := q.db.QueryRow(ctx, getCreditStandingSnapshot, accountID)
	var i GetCreditStandingSnapshotRow
	err := row.Scan(
		&i.BillingMode,
		&i.CreditLimitMicros,
		&i.BalanceMicros,
		&i.AutoTopupConfigured,
		&i.AutoTopupEnabled,
		&i.AutoTopupThresholdMicros,
		&i.AutoTopupAmountMicros,
		&i.AutoTopupPaymentMethodID,
		&i.AutoTopupLastAttemptStatus,
		&i.AutoTopupLastFailureCode,
		&i.AutoTopupPendingUntil,
	)
	return i, err
}

const getDistributorCustomerAccount = `-- name: GetDistributorCustomerAccount :one
SELECT customer.id AS account_id
FROM ms_billing.org_billing_designations designation
JOIN ms_billing.accounts distributor
  ON distributor.id = designation.sponsor_account_id
 AND distributor.owner_kind = 'org'
 AND distributor.owner_org_id = $1::uuid
JOIN ms_billing.accounts customer
  ON customer.owner_kind = 'org'
 AND customer.owner_org_id = designation.org_id
WHERE designation.org_id = $2::uuid
  AND designation.funding = 'sponsor'
`

type GetDistributorCustomerAccountParams struct {
	DistributorOrgID string `json:"distributor_org_id"`
	CustomerOrgID    string `json:"customer_org_id"`
}

// GetDistributorCustomerAccount validates the distributor -> customer
// relationship and returns the customer's wallet account in one lookup. A
// distributor is represented by an org-owned account named by the customer's
// sponsor_account_id; personal sponsorship never passes this join.
func (q *Queries) GetDistributorCustomerAccount(ctx context.Context, arg GetDistributorCustomerAccountParams) (string, error) {
	row := q.db.QueryRow(ctx, getDistributorCustomerAccount, arg.DistributorOrgID, arg.CustomerOrgID)
	var account_id string
	err := row.Scan(&account_id)
	return account_id, err
}

const hasUninvoicedBillingRunWalletDraw = `-- name: HasUninvoicedBillingRunWalletDraw :one
SELECT EXISTS (
    SELECT 1
    FROM ms_billing.billing_runs run
    JOIN ms_billing.billing_periods period
      ON period.account_id = run.account_id
     AND period.period_start = run.period_start
     AND period.period_end = run.period_end
    JOIN ms_billing.credit_ledger draw
      ON draw.account_id = run.account_id
     AND draw.period_id = period.id
     AND draw.type IN ('usage_draw', 'subscription_draw')
     AND draw.status = 'settled'
    WHERE run.account_id = $1::uuid
      AND run.status <> 'invoiced'
)::boolean
`

// HasUninvoicedBillingRunWalletDraw protects a boundary that has durably
// consumed wallet credit but has not yet reached the only non-reclaimable run
// state. SetCreditBillingMode calls this only for an actual mode change while
// holding LockWalletAccount's account FOR UPDATE lock. DrawWalletCredits takes
// that same lock before reading billing_mode and inserting period draw rows, so
// either the mode change wins before any draw or this exact durable draw wins
// and keeps its original mode through terminal invoice completion.
func (q *Queries) HasUninvoicedBillingRunWalletDraw(ctx context.Context, accountID string) (bool, error) {
	row := q.db.QueryRow(ctx, hasUninvoicedBillingRunWalletDraw, accountID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const insertCreationWalletDraw = `-- name: InsertCreationWalletDraw :exec
INSERT INTO ms_billing.credit_ledger (
    account_id,
    amount_micros,
    type,
    status,
    balance_after_micros,
    actor,
    idempotency_key,
    source_credit_id
) VALUES (
    $1::uuid,
    -$2::bigint,
    'usage_draw',
    'settled',
    $3::bigint,
    'system',
    $4::text,
    $5::uuid
)
`

type InsertCreationWalletDrawParams struct {
	AccountID          string      `json:"account_id"`
	AmountMicros       int64       `json:"amount_micros"`
	BalanceAfterMicros int64       `json:"balance_after_micros"`
	IdempotencyKey     string      `json:"idempotency_key"`
	SourceCreditID     pgtype.UUID `json:"source_credit_id"`
}

// InsertCreationWalletDraw appends one signed creation-proration draw row.
// Unlike InsertWalletDraw it carries NO period_id (period_id stays NULL): a
// creation-proration charge is keyed per APP, not per billing period, so a
// period-scoped guard would collide with the same period's boundary draw AND
// with sibling apps' creation draws against the same funding lot. Its
// idempotency is therefore the deterministic app-scoped idempotency_key alone
// (migration 048's global idempotency_key unique index), which is what the
// period/source relational guards can not express for a per-app debit. A
// multi-lot draw invokes it once per source; credits mode may append one final
// NULL-source unsecured row.
func (q *Queries) InsertCreationWalletDraw(ctx context.Context, arg InsertCreationWalletDrawParams) error {
	_, err := q.db.Exec(ctx, insertCreationWalletDraw,
		arg.AccountID,
		arg.AmountMicros,
		arg.BalanceAfterMicros,
		arg.IdempotencyKey,
		arg.SourceCreditID,
	)
	return err
}

const insertPendingCreditPurchase = `-- name: InsertPendingCreditPurchase :one
INSERT INTO ms_billing.credit_ledger (
    account_id,
    amount_micros,
    type,
    status,
    balance_after_micros,
    actor,
    idempotency_key
) VALUES (
    $1::uuid,
    $2::bigint,
    'purchase',
    'pending',
    $3::bigint,
    'self',
    $4::text
)
ON CONFLICT (idempotency_key) WHERE idempotency_key IS NOT NULL DO NOTHING
RETURNING
    id,
    account_id,
    amount_micros,
    type,
    status,
    balance_after_micros,
    actor,
    COALESCE(idempotency_key, '')::text AS idempotency_key,
    COALESCE(stripe_invoice_id, '')::text AS stripe_invoice_id,
    COALESCE(receipt_url, '')::text AS receipt_url,
    charge_funding_account_id,
    charge_funding_generation,
    COALESCE(attempt_stripe_customer_id, '')::text AS attempt_stripe_customer_id,
    charge_funding_legacy_unresolved,
    created_at
`

type InsertPendingCreditPurchaseParams struct {
	AccountID          string `json:"account_id"`
	AmountMicros       int64  `json:"amount_micros"`
	BalanceAfterMicros int64  `json:"balance_after_micros"`
	IdempotencyKey     string `json:"idempotency_key"`
}

type InsertPendingCreditPurchaseRow struct {
	ID                            string      `json:"id"`
	AccountID                     string      `json:"account_id"`
	AmountMicros                  int64       `json:"amount_micros"`
	Type                          string      `json:"type"`
	Status                        string      `json:"status"`
	BalanceAfterMicros            int64       `json:"balance_after_micros"`
	Actor                         string      `json:"actor"`
	IdempotencyKey                string      `json:"idempotency_key"`
	StripeInvoiceID               string      `json:"stripe_invoice_id"`
	ReceiptUrl                    string      `json:"receipt_url"`
	ChargeFundingAccountID        pgtype.UUID `json:"charge_funding_account_id"`
	ChargeFundingGeneration       pgtype.UUID `json:"charge_funding_generation"`
	AttemptStripeCustomerID       string      `json:"attempt_stripe_customer_id"`
	ChargeFundingLegacyUnresolved bool        `json:"charge_funding_legacy_unresolved"`
	CreatedAt                     time.Time   `json:"created_at"`
}

// InsertPendingCreditPurchase creates the durable handle before Stripe is
// called. A global idempotency collision returns pgx.ErrNoRows; the caller then
// resolves and validates it through GetCreditLedgerEntryByIdempotencyKey.
func (q *Queries) InsertPendingCreditPurchase(ctx context.Context, arg InsertPendingCreditPurchaseParams) (InsertPendingCreditPurchaseRow, error) {
	row := q.db.QueryRow(ctx, insertPendingCreditPurchase,
		arg.AccountID,
		arg.AmountMicros,
		arg.BalanceAfterMicros,
		arg.IdempotencyKey,
	)
	var i InsertPendingCreditPurchaseRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.AmountMicros,
		&i.Type,
		&i.Status,
		&i.BalanceAfterMicros,
		&i.Actor,
		&i.IdempotencyKey,
		&i.StripeInvoiceID,
		&i.ReceiptUrl,
		&i.ChargeFundingAccountID,
		&i.ChargeFundingGeneration,
		&i.AttemptStripeCustomerID,
		&i.ChargeFundingLegacyUnresolved,
		&i.CreatedAt,
	)
	return i, err
}

const insertSettledCreditGrant = `-- name: InsertSettledCreditGrant :one
INSERT INTO ms_billing.credit_ledger (
    account_id,
    amount_micros,
    type,
    status,
    balance_after_micros,
    actor,
    idempotency_key,
    expires_at
) VALUES (
    $1::uuid,
    $2::bigint,
    'grant',
    'settled',
    $3::bigint,
    $4::text,
    $5::text,
    $6::timestamptz
)
ON CONFLICT (idempotency_key) WHERE idempotency_key IS NOT NULL DO NOTHING
RETURNING id, balance_after_micros
`

type InsertSettledCreditGrantParams struct {
	AccountID          string             `json:"account_id"`
	AmountMicros       int64              `json:"amount_micros"`
	BalanceAfterMicros int64              `json:"balance_after_micros"`
	Actor              string             `json:"actor"`
	IdempotencyKey     string             `json:"idempotency_key"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
}

type InsertSettledCreditGrantRow struct {
	ID                 string `json:"id"`
	BalanceAfterMicros int64  `json:"balance_after_micros"`
}

// InsertSettledCreditGrant appends a posted distributor/system grant. The
// caller holds LockCreditAccountBalance and supplies the resulting snapshot.
// A global idempotency collision returns pgx.ErrNoRows for validation through
// GetCreditLedgerEntryByIdempotencyKey; no existing journal row is rewritten.
func (q *Queries) InsertSettledCreditGrant(ctx context.Context, arg InsertSettledCreditGrantParams) (InsertSettledCreditGrantRow, error) {
	row := q.db.QueryRow(ctx, insertSettledCreditGrant,
		arg.AccountID,
		arg.AmountMicros,
		arg.BalanceAfterMicros,
		arg.Actor,
		arg.IdempotencyKey,
		arg.ExpiresAt,
	)
	var i InsertSettledCreditGrantRow
	err := row.Scan(&i.ID, &i.BalanceAfterMicros)
	return i, err
}

const insertWalletDraw = `-- name: InsertWalletDraw :exec
INSERT INTO ms_billing.credit_ledger (
    account_id,
    amount_micros,
    type,
    status,
    balance_after_micros,
    actor,
    idempotency_key,
    period_id,
    source_credit_id
) VALUES (
    $1::uuid,
    -$2::bigint,
    'usage_draw',
    'settled',
    $3::bigint,
    'system',
    $4::text,
    $5::uuid,
    $6::uuid
)
`

type InsertWalletDrawParams struct {
	AccountID          string      `json:"account_id"`
	AmountMicros       int64       `json:"amount_micros"`
	BalanceAfterMicros int64       `json:"balance_after_micros"`
	IdempotencyKey     string      `json:"idempotency_key"`
	PeriodID           string      `json:"period_id"`
	SourceCreditID     pgtype.UUID `json:"source_credit_id"`
}

// InsertWalletDraw appends one signed allocation row. A multi-lot draw invokes
// it once per source; credits mode may append one final NULL-source unsecured
// row. idempotency_key is deterministic per account/period/type/source, while
// migration 048's period/source indexes provide the matching relational guard.
func (q *Queries) InsertWalletDraw(ctx context.Context, arg InsertWalletDrawParams) error {
	_, err := q.db.Exec(ctx, insertWalletDraw,
		arg.AccountID,
		arg.AmountMicros,
		arg.BalanceAfterMicros,
		arg.IdempotencyKey,
		arg.PeriodID,
		arg.SourceCreditID,
	)
	return err
}

const listCreditLedgerPage = `-- name: ListCreditLedgerPage :many
SELECT
    id,
    amount_micros,
    type,
    status,
    balance_after_micros,
    actor,
    receipt_url,
    expires_at,
    created_at
FROM ms_billing.credit_ledger
WHERE account_id = $1::uuid
  AND (
      (
          $2::timestamptz IS NULL
          AND $3::uuid IS NULL
      )
      OR
      (
          $2::timestamptz IS NOT NULL
          AND $3::uuid IS NOT NULL
          AND (created_at, id) < (
              $2::timestamptz,
              $3::uuid
          )
      )
  )
ORDER BY created_at DESC, id DESC
LIMIT $4::int
`

type ListCreditLedgerPageParams struct {
	AccountID       string             `json:"account_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
}

type ListCreditLedgerPageRow struct {
	ID                 string             `json:"id"`
	AmountMicros       int64              `json:"amount_micros"`
	Type               string             `json:"type"`
	Status             string             `json:"status"`
	BalanceAfterMicros int64              `json:"balance_after_micros"`
	Actor              string             `json:"actor"`
	ReceiptUrl         pgtype.Text        `json:"receipt_url"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	CreatedAt          time.Time          `json:"created_at"`
}

// ListCreditLedgerPage is stable newest-first keyset pagination over the
// migration-048 (account_id, created_at DESC, id DESC) index. A cursor is
// either wholly absent or a complete (created_at,id) pair; a half cursor
// deliberately matches no rows rather than silently restarting page one.
func (q *Queries) ListCreditLedgerPage(ctx context.Context, arg ListCreditLedgerPageParams) ([]ListCreditLedgerPageRow, error) {
	rows, err := q.db.Query(ctx, listCreditLedgerPage,
		arg.AccountID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCreditLedgerPageRow{}
	for rows.Next() {
		var i ListCreditLedgerPageRow
		if err := rows.Scan(
			&i.ID,
			&i.AmountMicros,
			&i.Type,
			&i.Status,
			&i.BalanceAfterMicros,
			&i.Actor,
			&i.ReceiptUrl,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistributorCustomerSnapshots = `-- name: ListDistributorCustomerSnapshots :many
SELECT
    designation.org_id AS customer_org_id,
    customer.id AS account_id,
    customer.billing_mode,
    customer.credit_limit_micros,
    COALESCE(balance.balance_micros, 0)::bigint AS balance_micros,
    (auto_topup.account_id IS NOT NULL)::boolean AS auto_topup_configured,
    COALESCE(auto_topup.enabled, false)::boolean AS auto_topup_enabled,
    COALESCE(auto_topup.threshold_micros, 0)::bigint AS auto_topup_threshold_micros,
    COALESCE(auto_topup.amount_micros, 0)::bigint AS auto_topup_amount_micros,
    COALESCE(auto_topup.payment_method_id::text, '')::text AS auto_topup_payment_method_id
FROM ms_billing.org_billing_designations designation
JOIN ms_billing.accounts distributor
  ON distributor.id = designation.sponsor_account_id
 AND distributor.owner_kind = 'org'
 AND distributor.owner_org_id = $1::uuid
JOIN ms_billing.accounts customer
  ON customer.owner_kind = 'org'
 AND customer.owner_org_id = designation.org_id
LEFT JOIN LATERAL (
    SELECT SUM(entry.amount_micros)::bigint AS balance_micros
    FROM ms_billing.credit_ledger entry
    WHERE entry.account_id = customer.id
      AND entry.status = 'settled'
) balance ON true
LEFT JOIN ms_billing.credit_auto_topup_configs auto_topup
       ON auto_topup.account_id = customer.id
WHERE designation.funding = 'sponsor'
ORDER BY designation.org_id
`

type ListDistributorCustomerSnapshotsRow struct {
	CustomerOrgID            string `json:"customer_org_id"`
	AccountID                string `json:"account_id"`
	BillingMode              string `json:"billing_mode"`
	CreditLimitMicros        int64  `json:"credit_limit_micros"`
	BalanceMicros            int64  `json:"balance_micros"`
	AutoTopupConfigured      bool   `json:"auto_topup_configured"`
	AutoTopupEnabled         bool   `json:"auto_topup_enabled"`
	AutoTopupThresholdMicros int64  `json:"auto_topup_threshold_micros"`
	AutoTopupAmountMicros    int64  `json:"auto_topup_amount_micros"`
	AutoTopupPaymentMethodID string `json:"auto_topup_payment_method_id"`
}

// ListDistributorCustomerSnapshots lists every customer whose designation
// names the distributor's org account, including the wallet fields needed for
// service-side ok/low/blocked classification.
func (q *Queries) ListDistributorCustomerSnapshots(ctx context.Context, distributorOrgID string) ([]ListDistributorCustomerSnapshotsRow, error) {
	rows, err := q.db.Query(ctx, listDistributorCustomerSnapshots, distributorOrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDistributorCustomerSnapshotsRow{}
	for rows.Next() {
		var i ListDistributorCustomerSnapshotsRow
		if err := rows.Scan(
			&i.CustomerOrgID,
			&i.AccountID,
			&i.BillingMode,
			&i.CreditLimitMicros,
			&i.BalanceMicros,
			&i.AutoTopupConfigured,
			&i.AutoTopupEnabled,
			&i.AutoTopupThresholdMicros,
			&i.AutoTopupAmountMicros,
			&i.AutoTopupPaymentMethodID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCreditAccountBalance = `-- name: LockCreditAccountBalance :one
SELECT
    account.billing_mode,
    account.credit_limit_micros,
    COALESCE((
        SELECT SUM(entry.amount_micros)
        FROM ms_billing.credit_ledger entry
        WHERE entry.account_id = account.id
          AND entry.status = 'settled'
    ), 0)::bigint AS balance_micros
FROM ms_billing.accounts account
WHERE account.id = $1::uuid
FOR UPDATE OF account
`

type LockCreditAccountBalanceRow struct {
	BillingMode       string `json:"billing_mode"`
	CreditLimitMicros int64  `json:"credit_limit_micros"`
	BalanceMicros     int64  `json:"balance_micros"`
}

// LockCreditAccountBalance is the RPC write serialization point and the
// authoritative posted balance immediately before inserting or settling a
// journal entry. FOR UPDATE OF account avoids trying to lock aggregate rows.
func (q *Queries) LockCreditAccountBalance(ctx context.Context, accountID string) (LockCreditAccountBalanceRow, error) {
	row := q.db.QueryRow(ctx, lockCreditAccountBalance, accountID)
	var i LockCreditAccountBalanceRow
	err := row.Scan(&i.BillingMode, &i.CreditLimitMicros, &i.BalanceMicros)
	return i, err
}

const lockDistributorCustomerAccountForMutation = `-- name: LockDistributorCustomerAccountForMutation :one
SELECT customer.id AS account_id
FROM ms_billing.org_billing_designations designation
JOIN ms_billing.accounts distributor
  ON distributor.id = designation.sponsor_account_id
 AND distributor.owner_kind = 'org'
 AND distributor.owner_org_id = $1::uuid
JOIN ms_billing.accounts customer
  ON customer.owner_kind = 'org'
 AND customer.owner_org_id = designation.org_id
WHERE designation.org_id = $2::uuid
  AND designation.funding = 'sponsor'
FOR UPDATE OF designation
`

type LockDistributorCustomerAccountForMutationParams struct {
	DistributorOrgID string `json:"distributor_org_id"`
	CustomerOrgID    string `json:"customer_org_id"`
}

// LockDistributorCustomerAccountForMutation repeats the exact authority lookup
// under a row lock. The lock keeps a designation UPDATE/DELETE from revoking or
// redirecting authority after a distributor mutation has re-authorized inside
// its write transaction; the relationship change linearizes after that write.
func (q *Queries) LockDistributorCustomerAccountForMutation(ctx context.Context, arg LockDistributorCustomerAccountForMutationParams) (string, error) {
	row := q.db.QueryRow(ctx, lockDistributorCustomerAccountForMutation, arg.DistributorOrgID, arg.CustomerOrgID)
	var account_id string
	err := row.Scan(&account_id)
	return account_id, err
}

const lockWalletAccount = `-- name: LockWalletAccount :one
SELECT billing_mode
FROM ms_billing.accounts
WHERE id = $1::uuid
FOR UPDATE
`

// LockWalletAccount is the serialization point for a draw. The account FK on
// credit_ledger also makes concurrent ledger inserts wait behind this lock.
func (q *Queries) LockWalletAccount(ctx context.Context, accountID string) (string, error) {
	row := q.db.QueryRow(ctx, lockWalletAccount, accountID)
	var billing_mode string
	err := row.Scan(&billing_mode)
	return billing_mode, err
}

const lockWalletLedgerEntries = `-- name: LockWalletLedgerEntries :many
SELECT id
FROM ms_billing.credit_ledger
WHERE account_id = $1::uuid
ORDER BY id
FOR UPDATE
`

// LockWalletLedgerEntries stabilizes status as well as row contents for the
// allocation transaction. LockWalletAccount blocks concurrent child INSERTs
// through the account FK, while these row locks block the explicitly allowed
// pending-purchase status transition from changing the settled snapshot between
// WalletSettledBalance and WalletSpendableLots.
func (q *Queries) LockWalletLedgerEntries(ctx context.Context, accountID string) ([]string, error) {
	rows, err := q.db.Query(ctx, lockWalletLedgerEntries, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCreditAccountBillingMode = `-- name: SetCreditAccountBillingMode :one
UPDATE ms_billing.accounts
SET billing_mode = $1::text,
    credit_limit_micros = $2::bigint
WHERE id = $3::uuid
  AND (
      billing_mode IS DISTINCT FROM $1::text
      OR credit_limit_micros IS DISTINCT FROM $2::bigint
  )
RETURNING billing_mode, credit_limit_micros
`

type SetCreditAccountBillingModeParams struct {
	BillingMode       string `json:"billing_mode"`
	CreditLimitMicros int64  `json:"credit_limit_micros"`
	AccountID         string `json:"account_id"`
}

type SetCreditAccountBillingModeRow struct {
	BillingMode       string `json:"billing_mode"`
	CreditLimitMicros int64  `json:"credit_limit_micros"`
}

// SetCreditAccountBillingMode applies a service-resolved concrete credit limit.
// In particular, the service resolves an omitted credits-mode value to the
// $5.00 wallet default before calling this query.
func (q *Queries) SetCreditAccountBillingMode(ctx context.Context, arg SetCreditAccountBillingModeParams) (SetCreditAccountBillingModeRow, error) {
	row := q.db.QueryRow(ctx, setCreditAccountBillingMode, arg.BillingMode, arg.CreditLimitMicros, arg.AccountID)
	var i SetCreditAccountBillingModeRow
	err := row.Scan(&i.BillingMode, &i.CreditLimitMicros)
	return i, err
}

const upsertCreditAutoTopUp = `-- name: UpsertCreditAutoTopUp :one
INSERT INTO ms_billing.credit_auto_topup_configs (
    account_id,
    enabled,
    threshold_micros,
    amount_micros,
    payment_method_id
) VALUES (
    $1::uuid,
    $2::boolean,
    $3::bigint,
    $4::bigint,
    NULLIF($5::text, '')::uuid
)
ON CONFLICT (account_id) DO UPDATE SET
    enabled = EXCLUDED.enabled,
    threshold_micros = EXCLUDED.threshold_micros,
    amount_micros = EXCLUDED.amount_micros,
    payment_method_id = EXCLUDED.payment_method_id
RETURNING
    enabled,
    threshold_micros,
    amount_micros,
    COALESCE(payment_method_id::text, '')::text AS payment_method_id
`

type UpsertCreditAutoTopUpParams struct {
	AccountID       string `json:"account_id"`
	Enabled         bool   `json:"enabled"`
	ThresholdMicros int64  `json:"threshold_micros"`
	AmountMicros    int64  `json:"amount_micros"`
	PaymentMethodID string `json:"payment_method_id"`
}

type UpsertCreditAutoTopUpRow struct {
	Enabled         bool   `json:"enabled"`
	ThresholdMicros int64  `json:"threshold_micros"`
	AmountMicros    int64  `json:"amount_micros"`
	PaymentMethodID string `json:"payment_method_id"`
}

// UpsertCreditAutoTopUp owns the one-row-per-account mutable configuration.
// The table CHECK enforces that enabled configs carry a payment method and
// that amount stays within the same $5-$5,000 bounds as manual purchases.
func (q *Queries) UpsertCreditAutoTopUp(ctx context.Context, arg UpsertCreditAutoTopUpParams) (UpsertCreditAutoTopUpRow, error) {
	row := q.db.QueryRow(ctx, upsertCreditAutoTopUp,
		arg.AccountID,
		arg.Enabled,
		arg.ThresholdMicros,
		arg.AmountMicros,
		arg.PaymentMethodID,
	)
	var i UpsertCreditAutoTopUpRow
	err := row.Scan(
		&i.Enabled,
		&i.ThresholdMicros,
		&i.AmountMicros,
		&i.PaymentMethodID,
	)
	return i, err
}

const walletCreditState = `-- name: WalletCreditState :one

WITH source_lots AS (
    SELECT
        source.id,
        source.expires_at,
        (
            source.amount_micros::numeric
            + COALESCE((
                SELECT SUM(draw.amount_micros)
                FROM ms_billing.credit_ledger draw
                WHERE draw.source_credit_id = source.id
                  AND draw.account_id = source.account_id
                  AND draw.status = 'settled'
                  AND draw.type IN ('usage_draw', 'subscription_draw')
            ), 0)
        ) AS remaining_micros
    FROM ms_billing.credit_ledger source
    WHERE source.account_id = $1::uuid
      AND source.status = 'settled'
      AND source.amount_micros > 0
      AND source.type IN (
          'grant', 'preallocation', 'refund', 'adjustment',
          'purchase', 'auto_topup'
      )
), balances AS (
    SELECT
        COALESCE((
            SELECT SUM(entry.amount_micros)
            FROM ms_billing.credit_ledger entry
            WHERE entry.account_id = $1::uuid
              AND entry.status = 'settled'
        ), 0) AS settled_micros,
        COALESCE((
            SELECT SUM(lot.remaining_micros)
            FROM source_lots lot
            WHERE lot.remaining_micros > 0
              AND (lot.expires_at IS NULL OR lot.expires_at > CURRENT_TIMESTAMP)
        ), 0) AS lot_micros,
        COALESCE((
            SELECT SUM(lot.remaining_micros)
            FROM source_lots lot
            WHERE lot.remaining_micros > 0
              AND lot.expires_at <= CURRENT_TIMESTAMP
        ), 0) AS expired_lot_micros,
        COALESCE((
            SELECT -SUM(draw.amount_micros)
            FROM ms_billing.credit_ledger draw
            JOIN ms_billing.billing_periods period ON period.id = draw.period_id
            WHERE draw.account_id = $1::uuid
              AND period.account_id = $1::uuid
              AND period.period_start = $2::timestamptz
              AND period.period_end = $3::timestamptz
              AND draw.status = 'settled'
              AND draw.type IN ('usage_draw', 'subscription_draw')
        ), 0) AS period_drawn_micros
)
SELECT
    account.billing_mode,
    GREATEST(
        LEAST(
            balances.lot_micros,
            GREATEST(
                balances.settled_micros - balances.expired_lot_micros,
                0
            )
        ),
        0
    )::bigint AS spendable_balance_micros,
    balances.period_drawn_micros::bigint AS period_drawn_micros
FROM ms_billing.accounts account
CROSS JOIN balances
WHERE account.id = $1::uuid
`

type WalletCreditStateParams struct {
	AccountID   string    `json:"account_id"`
	PeriodStart time.Time `json:"period_start"`
	PeriodEnd   time.Time `json:"period_end"`
}

type WalletCreditStateRow struct {
	BillingMode            string `json:"billing_mode"`
	SpendableBalanceMicros int64  `json:"spendable_balance_micros"`
	PeriodDrawnMicros      int64  `json:"period_drawn_micros"`
}

// Queries backing the universal credit-wallet draw at the account billing
// boundary (migration 048). Draws are append-only settled ledger rows. The Go
// store holds an account-row lock while using the transactional queries below,
// which serializes same-account allocation and keeps balance_after_micros
// snapshots in ledger order.
// WalletCreditState is the cheap charge-path probe. Spendable credit is the
// lesser of (a) active positive lot remainder and (b) the positive posted
// balance after unused expired grant remainder is removed, so neither expiry
// nor an account-level negative adjustment can be bypassed by allocating an
// otherwise-positive lot. Expired grants remain in the immutable journal
// balance but are excluded from spendable credit. Existing draws of both
// boundary draw types make a reclaimed run re-enter the wallet path.
func (q *Queries) WalletCreditState(ctx context.Context, arg WalletCreditStateParams) (WalletCreditStateRow, error) {
	row := q.db.QueryRow(ctx, walletCreditState, arg.AccountID, arg.PeriodStart, arg.PeriodEnd)
	var i WalletCreditStateRow
	err := row.Scan(&i.BillingMode, &i.SpendableBalanceMicros, &i.PeriodDrawnMicros)
	return i, err
}

const walletExpiredCreditBalance = `-- name: WalletExpiredCreditBalance :one
SELECT COALESCE(SUM(expired.remaining_micros), 0)::bigint AS expired_micros
FROM (
    SELECT
        source.amount_micros::numeric
        + COALESCE((
            SELECT SUM(draw.amount_micros)
            FROM ms_billing.credit_ledger draw
            WHERE draw.source_credit_id = source.id
              AND draw.account_id = source.account_id
              AND draw.status = 'settled'
              AND draw.type IN ('usage_draw', 'subscription_draw')
        ), 0) AS remaining_micros
    FROM ms_billing.credit_ledger source
    WHERE source.account_id = $1::uuid
      AND source.status = 'settled'
      AND source.amount_micros > 0
      AND source.type IN (
          'grant', 'preallocation', 'refund', 'adjustment',
          'purchase', 'auto_topup'
      )
      AND source.expires_at <= CURRENT_TIMESTAMP
) expired
WHERE expired.remaining_micros > 0
`

// WalletExpiredCreditBalance is the unused remainder of grants whose expiry is
// at or before this transaction's current time. It is subtracted from the
// standard-mode posted-balance cap; otherwise an expired grant could offset a
// later negative adjustment and make unrelated active credit look spendable.
func (q *Queries) WalletExpiredCreditBalance(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRow(ctx, walletExpiredCreditBalance, accountID)
	var expired_micros int64
	err := row.Scan(&expired_micros)
	return expired_micros, err
}

const walletPeriodDraw = `-- name: WalletPeriodDraw :one
SELECT
    period.id AS period_id,
    COALESCE(
        -SUM(draw.amount_micros) FILTER (
            WHERE draw.status = 'settled'
              AND draw.type IN ('usage_draw', 'subscription_draw')
        ),
        0
    )::bigint AS drawn_micros
FROM ms_billing.billing_periods period
LEFT JOIN ms_billing.credit_ledger draw
       ON draw.account_id = period.account_id
      AND draw.period_id = period.id
WHERE period.account_id = $1::uuid
  AND period.period_start = $2::timestamptz
  AND period.period_end = $3::timestamptz
GROUP BY period.id
`

type WalletPeriodDrawParams struct {
	AccountID   string    `json:"account_id"`
	PeriodStart time.Time `json:"period_start"`
	PeriodEnd   time.Time `json:"period_end"`
}

type WalletPeriodDrawRow struct {
	PeriodID    string `json:"period_id"`
	DrawnMicros int64  `json:"drawn_micros"`
}

// WalletPeriodDraw resolves the exact first-class period and recovers any
// already-durable boundary draw before the caller considers allowNew. Both draw
// types are included for forward-compatible recovery, although the current
// mixed boundary method emits usage_draw because its input has no category
// split.
func (q *Queries) WalletPeriodDraw(ctx context.Context, arg WalletPeriodDrawParams) (WalletPeriodDrawRow, error) {
	row := q.db.QueryRow(ctx, walletPeriodDraw, arg.AccountID, arg.PeriodStart, arg.PeriodEnd)
	var i WalletPeriodDrawRow
	err := row.Scan(&i.PeriodID, &i.DrawnMicros)
	return i, err
}

const walletSettledBalance = `-- name: WalletSettledBalance :one
SELECT COALESCE(SUM(amount_micros), 0)::bigint AS balance_micros
FROM ms_billing.credit_ledger
WHERE account_id = $1::uuid
  AND status = 'settled'
`

// WalletSettledBalance is the posted balance immediately before a new draw.
// Each inserted row subtracts its allocation from this value to populate the
// next balance_after_micros snapshot.
func (q *Queries) WalletSettledBalance(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRow(ctx, walletSettledBalance, accountID)
	var balance_micros int64
	err := row.Scan(&balance_micros)
	return balance_micros, err
}

const walletSpendableLots = `-- name: WalletSpendableLots :many
SELECT
    source.id,
    remaining.remaining_micros::bigint AS remaining_micros
FROM ms_billing.credit_ledger source
CROSS JOIN LATERAL (
    SELECT
        source.amount_micros::numeric
        + COALESCE(SUM(draw.amount_micros), 0) AS remaining_micros
    FROM ms_billing.credit_ledger draw
    WHERE draw.source_credit_id = source.id
      AND draw.account_id = source.account_id
      AND draw.status = 'settled'
      AND draw.type IN ('usage_draw', 'subscription_draw')
) remaining
WHERE source.account_id = $1::uuid
  AND source.status = 'settled'
  AND source.amount_micros > 0
  AND source.type IN (
      'grant', 'preallocation', 'refund', 'adjustment',
      'purchase', 'auto_topup'
  )
  AND (source.expires_at IS NULL OR source.expires_at > CURRENT_TIMESTAMP)
  AND remaining.remaining_micros > 0
ORDER BY
    CASE
        WHEN source.type = 'grant' AND source.expires_at IS NOT NULL THEN 0
        WHEN source.type IN ('grant', 'preallocation', 'refund', 'adjustment') THEN 1
        ELSE 2
    END,
    source.expires_at ASC NULLS LAST,
    source.created_at ASC,
    source.id ASC
FOR UPDATE OF source
`

type WalletSpendableLotsRow struct {
	ID              string `json:"id"`
	RemainingMicros int64  `json:"remaining_micros"`
}

// WalletSpendableLots returns active settled funding in the owner-decided
// consumption order. A source's remainder is its positive amount plus all
// settled negative draws that reference it. Positive refund/adjustment entries
// share the non-expiring-grant tier, matching their non-purchased credit
// semantics; negative entries affect the posted-balance cap instead.
func (q *Queries) WalletSpendableLots(ctx context.Context, accountID string) ([]WalletSpendableLotsRow, error) {
	rows, err := q.db.Query(ctx, walletSpendableLots, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WalletSpendableLotsRow{}
	for rows.Next() {
		var i WalletSpendableLotsRow
		if err := rows.Scan(&i.ID, &i.RemainingMicros); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
