// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credit_wallet.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertWalletDraw = `-- name: InsertWalletDraw :exec
INSERT INTO ms_billing.credit_ledger (
    account_id,
    amount_micros,
    type,
    status,
    balance_after_micros,
    actor,
    idempotency_key,
    period_id,
    source_credit_id
) VALUES (
    $1::uuid,
    -$2::bigint,
    'usage_draw',
    'settled',
    $3::bigint,
    'system',
    $4::text,
    $5::uuid,
    $6::uuid
)
`

type InsertWalletDrawParams struct {
	AccountID          string      `json:"account_id"`
	AmountMicros       int64       `json:"amount_micros"`
	BalanceAfterMicros int64       `json:"balance_after_micros"`
	IdempotencyKey     string      `json:"idempotency_key"`
	PeriodID           string      `json:"period_id"`
	SourceCreditID     pgtype.UUID `json:"source_credit_id"`
}

// InsertWalletDraw appends one signed allocation row. A multi-lot draw invokes
// it once per source; credits mode may append one final NULL-source unsecured
// row. idempotency_key is deterministic per account/period/type/source, while
// migration 048's period/source indexes provide the matching relational guard.
func (q *Queries) InsertWalletDraw(ctx context.Context, arg InsertWalletDrawParams) error {
	_, err := q.db.Exec(ctx, insertWalletDraw,
		arg.AccountID,
		arg.AmountMicros,
		arg.BalanceAfterMicros,
		arg.IdempotencyKey,
		arg.PeriodID,
		arg.SourceCreditID,
	)
	return err
}

const lockWalletAccount = `-- name: LockWalletAccount :one
SELECT billing_mode
FROM ms_billing.accounts
WHERE id = $1::uuid
FOR UPDATE
`

// LockWalletAccount is the serialization point for a draw. The account FK on
// credit_ledger also makes concurrent ledger inserts wait behind this lock.
func (q *Queries) LockWalletAccount(ctx context.Context, accountID string) (string, error) {
	row := q.db.QueryRow(ctx, lockWalletAccount, accountID)
	var billing_mode string
	err := row.Scan(&billing_mode)
	return billing_mode, err
}

const lockWalletLedgerEntries = `-- name: LockWalletLedgerEntries :many
SELECT id
FROM ms_billing.credit_ledger
WHERE account_id = $1::uuid
ORDER BY id
FOR UPDATE
`

// LockWalletLedgerEntries stabilizes status as well as row contents for the
// allocation transaction. LockWalletAccount blocks concurrent child INSERTs
// through the account FK, while these row locks block the explicitly allowed
// pending-purchase status transition from changing the settled snapshot between
// WalletSettledBalance and WalletSpendableLots.
func (q *Queries) LockWalletLedgerEntries(ctx context.Context, accountID string) ([]string, error) {
	rows, err := q.db.Query(ctx, lockWalletLedgerEntries, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const walletCreditState = `-- name: WalletCreditState :one

WITH source_lots AS (
    SELECT
        source.id,
        source.expires_at,
        (
            source.amount_micros::numeric
            + COALESCE((
                SELECT SUM(draw.amount_micros)
                FROM ms_billing.credit_ledger draw
                WHERE draw.source_credit_id = source.id
                  AND draw.account_id = source.account_id
                  AND draw.status = 'settled'
                  AND draw.type IN ('usage_draw', 'subscription_draw')
            ), 0)
        ) AS remaining_micros
    FROM ms_billing.credit_ledger source
    WHERE source.account_id = $1::uuid
      AND source.status = 'settled'
      AND source.amount_micros > 0
      AND source.type IN (
          'grant', 'preallocation', 'refund', 'adjustment',
          'purchase', 'auto_topup'
      )
), balances AS (
    SELECT
        COALESCE((
            SELECT SUM(entry.amount_micros)
            FROM ms_billing.credit_ledger entry
            WHERE entry.account_id = $1::uuid
              AND entry.status = 'settled'
        ), 0) AS settled_micros,
        COALESCE((
            SELECT SUM(lot.remaining_micros)
            FROM source_lots lot
            WHERE lot.remaining_micros > 0
              AND (lot.expires_at IS NULL OR lot.expires_at > CURRENT_TIMESTAMP)
        ), 0) AS lot_micros,
        COALESCE((
            SELECT SUM(lot.remaining_micros)
            FROM source_lots lot
            WHERE lot.remaining_micros > 0
              AND lot.expires_at <= CURRENT_TIMESTAMP
        ), 0) AS expired_lot_micros,
        COALESCE((
            SELECT -SUM(draw.amount_micros)
            FROM ms_billing.credit_ledger draw
            JOIN ms_billing.billing_periods period ON period.id = draw.period_id
            WHERE draw.account_id = $1::uuid
              AND period.account_id = $1::uuid
              AND period.period_start = $2::timestamptz
              AND period.period_end = $3::timestamptz
              AND draw.status = 'settled'
              AND draw.type IN ('usage_draw', 'subscription_draw')
        ), 0) AS period_drawn_micros
)
SELECT
    account.billing_mode,
    GREATEST(
        LEAST(
            balances.lot_micros,
            GREATEST(
                balances.settled_micros - balances.expired_lot_micros,
                0
            )
        ),
        0
    )::bigint AS spendable_balance_micros,
    balances.period_drawn_micros::bigint AS period_drawn_micros
FROM ms_billing.accounts account
CROSS JOIN balances
WHERE account.id = $1::uuid
`

type WalletCreditStateParams struct {
	AccountID   string    `json:"account_id"`
	PeriodStart time.Time `json:"period_start"`
	PeriodEnd   time.Time `json:"period_end"`
}

type WalletCreditStateRow struct {
	BillingMode            string `json:"billing_mode"`
	SpendableBalanceMicros int64  `json:"spendable_balance_micros"`
	PeriodDrawnMicros      int64  `json:"period_drawn_micros"`
}

// Queries backing the universal credit-wallet draw at the account billing
// boundary (migration 048). Draws are append-only settled ledger rows. The Go
// store holds an account-row lock while using the transactional queries below,
// which serializes same-account allocation and keeps balance_after_micros
// snapshots in ledger order.
// WalletCreditState is the cheap charge-path probe. Spendable credit is the
// lesser of (a) active positive lot remainder and (b) the positive posted
// balance after unused expired grant remainder is removed, so neither expiry
// nor an account-level negative adjustment can be bypassed by allocating an
// otherwise-positive lot. Expired grants remain in the immutable journal
// balance but are excluded from spendable credit. Existing draws of both
// boundary draw types make a reclaimed run re-enter the wallet path.
func (q *Queries) WalletCreditState(ctx context.Context, arg WalletCreditStateParams) (WalletCreditStateRow, error) {
	row := q.db.QueryRow(ctx, walletCreditState, arg.AccountID, arg.PeriodStart, arg.PeriodEnd)
	var i WalletCreditStateRow
	err := row.Scan(&i.BillingMode, &i.SpendableBalanceMicros, &i.PeriodDrawnMicros)
	return i, err
}

const walletExpiredCreditBalance = `-- name: WalletExpiredCreditBalance :one
SELECT COALESCE(SUM(expired.remaining_micros), 0)::bigint AS expired_micros
FROM (
    SELECT
        source.amount_micros::numeric
        + COALESCE((
            SELECT SUM(draw.amount_micros)
            FROM ms_billing.credit_ledger draw
            WHERE draw.source_credit_id = source.id
              AND draw.account_id = source.account_id
              AND draw.status = 'settled'
              AND draw.type IN ('usage_draw', 'subscription_draw')
        ), 0) AS remaining_micros
    FROM ms_billing.credit_ledger source
    WHERE source.account_id = $1::uuid
      AND source.status = 'settled'
      AND source.amount_micros > 0
      AND source.type IN (
          'grant', 'preallocation', 'refund', 'adjustment',
          'purchase', 'auto_topup'
      )
      AND source.expires_at <= CURRENT_TIMESTAMP
) expired
WHERE expired.remaining_micros > 0
`

// WalletExpiredCreditBalance is the unused remainder of grants whose expiry is
// at or before this transaction's current time. It is subtracted from the
// standard-mode posted-balance cap; otherwise an expired grant could offset a
// later negative adjustment and make unrelated active credit look spendable.
func (q *Queries) WalletExpiredCreditBalance(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRow(ctx, walletExpiredCreditBalance, accountID)
	var expired_micros int64
	err := row.Scan(&expired_micros)
	return expired_micros, err
}

const walletPeriodDraw = `-- name: WalletPeriodDraw :one
SELECT
    period.id AS period_id,
    COALESCE(
        -SUM(draw.amount_micros) FILTER (
            WHERE draw.status = 'settled'
              AND draw.type IN ('usage_draw', 'subscription_draw')
        ),
        0
    )::bigint AS drawn_micros
FROM ms_billing.billing_periods period
LEFT JOIN ms_billing.credit_ledger draw
       ON draw.account_id = period.account_id
      AND draw.period_id = period.id
WHERE period.account_id = $1::uuid
  AND period.period_start = $2::timestamptz
  AND period.period_end = $3::timestamptz
GROUP BY period.id
`

type WalletPeriodDrawParams struct {
	AccountID   string    `json:"account_id"`
	PeriodStart time.Time `json:"period_start"`
	PeriodEnd   time.Time `json:"period_end"`
}

type WalletPeriodDrawRow struct {
	PeriodID    string `json:"period_id"`
	DrawnMicros int64  `json:"drawn_micros"`
}

// WalletPeriodDraw resolves the exact first-class period and recovers any
// already-durable boundary draw before the caller considers allowNew. Both draw
// types are included for forward-compatible recovery, although the current
// mixed boundary method emits usage_draw because its input has no category
// split.
func (q *Queries) WalletPeriodDraw(ctx context.Context, arg WalletPeriodDrawParams) (WalletPeriodDrawRow, error) {
	row := q.db.QueryRow(ctx, walletPeriodDraw, arg.AccountID, arg.PeriodStart, arg.PeriodEnd)
	var i WalletPeriodDrawRow
	err := row.Scan(&i.PeriodID, &i.DrawnMicros)
	return i, err
}

const walletSettledBalance = `-- name: WalletSettledBalance :one
SELECT COALESCE(SUM(amount_micros), 0)::bigint AS balance_micros
FROM ms_billing.credit_ledger
WHERE account_id = $1::uuid
  AND status = 'settled'
`

// WalletSettledBalance is the posted balance immediately before a new draw.
// Each inserted row subtracts its allocation from this value to populate the
// next balance_after_micros snapshot.
func (q *Queries) WalletSettledBalance(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRow(ctx, walletSettledBalance, accountID)
	var balance_micros int64
	err := row.Scan(&balance_micros)
	return balance_micros, err
}

const walletSpendableLots = `-- name: WalletSpendableLots :many
SELECT
    source.id,
    remaining.remaining_micros::bigint AS remaining_micros
FROM ms_billing.credit_ledger source
CROSS JOIN LATERAL (
    SELECT
        source.amount_micros::numeric
        + COALESCE(SUM(draw.amount_micros), 0) AS remaining_micros
    FROM ms_billing.credit_ledger draw
    WHERE draw.source_credit_id = source.id
      AND draw.account_id = source.account_id
      AND draw.status = 'settled'
      AND draw.type IN ('usage_draw', 'subscription_draw')
) remaining
WHERE source.account_id = $1::uuid
  AND source.status = 'settled'
  AND source.amount_micros > 0
  AND source.type IN (
      'grant', 'preallocation', 'refund', 'adjustment',
      'purchase', 'auto_topup'
  )
  AND (source.expires_at IS NULL OR source.expires_at > CURRENT_TIMESTAMP)
  AND remaining.remaining_micros > 0
ORDER BY
    CASE
        WHEN source.type = 'grant' AND source.expires_at IS NOT NULL THEN 0
        WHEN source.type IN ('grant', 'preallocation', 'refund', 'adjustment') THEN 1
        ELSE 2
    END,
    source.expires_at ASC NULLS LAST,
    source.created_at ASC,
    source.id ASC
FOR UPDATE OF source
`

type WalletSpendableLotsRow struct {
	ID              string `json:"id"`
	RemainingMicros int64  `json:"remaining_micros"`
}

// WalletSpendableLots returns active settled funding in the owner-decided
// consumption order. A source's remainder is its positive amount plus all
// settled negative draws that reference it. Positive refund/adjustment entries
// share the non-expiring-grant tier, matching their non-purchased credit
// semantics; negative entries affect the posted-balance cap instead.
func (q *Queries) WalletSpendableLots(ctx context.Context, accountID string) ([]WalletSpendableLotsRow, error) {
	rows, err := q.db.Query(ctx, walletSpendableLots, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WalletSpendableLotsRow{}
	for rows.Next() {
		var i WalletSpendableLotsRow
		if err := rows.Scan(&i.ID, &i.RemainingMicros); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
