// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cycle.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const accountCollectionFields = `-- name: AccountCollectionFields :one
SELECT
    usage_billing_mode,
    credit_limit_micros,
    spend_ceiling_micros,
    auto_collect_threshold_micros,
    created_at
FROM ms_billing.accounts
WHERE id = $1
`

type AccountCollectionFieldsRow struct {
	UsageBillingMode           MsBillingUsageBillingMode `json:"usage_billing_mode"`
	CreditLimitMicros          int64                     `json:"credit_limit_micros"`
	SpendCeilingMicros         pgtype.Int8               `json:"spend_ceiling_micros"`
	AutoCollectThresholdMicros pgtype.Int8               `json:"auto_collect_threshold_micros"`
	CreatedAt                  time.Time                 `json:"created_at"`
}

// AccountCollectionFields loads the risk-graded collection controls for the
// charge gate (PR #9): the off-session arrears leg reads these to decide whether
// to charge, skip-prepaid, cap at the spend ceiling, or tighten over the credit
// limit. created_at is returned so the risk-judge can compute account tenure
// WITHOUT a cross-schema read into ms_account (billing-engine never reads
// ms_account tables). spend_ceiling_micros is NULL when no ceiling is set; the
// Go layer carries it as a nullable. auto_collect_threshold_micros (migration
// 031) is NULL when the account uses the platform default; the charge leg
// resolves it to collection.DefaultAutoCollectThresholdMicros AT CHARGE TIME to
// decide the post-hoc large-charge disclosure flag.
func (q *Queries) AccountCollectionFields(ctx context.Context, id string) (AccountCollectionFieldsRow, error) {
	row := q.db.QueryRow(ctx, accountCollectionFields, id)
	var i AccountCollectionFieldsRow
	err := row.Scan(
		&i.UsageBillingMode,
		&i.CreditLimitMicros,
		&i.SpendCeilingMicros,
		&i.AutoCollectThresholdMicros,
		&i.CreatedAt,
	)
	return i, err
}

const accountStripeCustomer = `-- name: AccountStripeCustomer :one
SELECT COALESCE(stripe_customer_id, '')::text AS stripe_customer_id
FROM ms_billing.accounts
WHERE id = $1
`

// AccountStripeCustomer resolves the account's Stripe Customer id for the
// charge. COALESCE to ” so the Go layer distinguishes "no Customer yet" (empty)
// from a real id without a nullable round-trip. A charge never auto-creates a
// Customer — an account reaching the charge leg with no Customer is an
// anomaly the service surfaces, never a silent Stripe Customer create.
func (q *Queries) AccountStripeCustomer(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, accountStripeCustomer, id)
	var stripe_customer_id string
	err := row.Scan(&stripe_customer_id)
	return stripe_customer_id, err
}

const accountsWithUnbilledUsage = `-- name: AccountsWithUnbilledUsage :many
SELECT DISTINCT ua.account_id AS account_id
FROM ms_billing.usage_aggregates ua
JOIN ms_billing.billing_periods bp ON bp.id = ua.period_id
LEFT JOIN ms_billing.billing_runs br
       ON br.account_id   = ua.account_id
      AND br.period_start = bp.period_start
      AND br.period_end   = bp.period_end
WHERE bp.period_start = $1
  AND bp.period_end   = $2
  AND (br.id IS NULL OR br.status <> 'invoiced')
`

type AccountsWithUnbilledUsageParams struct {
	PeriodStart time.Time `json:"period_start"`
	PeriodEnd   time.Time `json:"period_end"`
}

// AccountsWithUnbilledUsage returns the distinct accounts that have at least
// one usage_aggregates row for the EXACT closed window [period_start,
// period_end) and do NOT already have a SUCCESSFUL (invoiced) billing_run for
// it. The window is matched by equality on the billing_periods row (each window
// is one period row), so two adjacent months never both match a single run.
//
// The anti-join surfaces an account when EITHER it has no run row
// (br.id IS NULL) OR its run is non-terminal. 'invoiced' is the ONLY terminal
// (excluding) status; every other status re-surfaces the account so the next
// cycle re-attempts (usage is RETAINED, never abandoned):
//
//	'pending'         a prior run died mid-flight, before MarkBillingRun
//	'failed'          the charge errored
//	'skipped_no_pm'   no usable payment method last cycle
//	'skipped_prepaid' the account was in / tightened to prepaid mode
//	'skipped_ceiling' the arrears breached the per-cycle spend ceiling
//
// InsertBillingRun's ON CONFLICT (WHERE status <> 'invoiced') reclaims the SAME
// non-terminal row, and the deterministic Stripe Idempotency-Keys
// (ii-<run>/inv-<run>, stable per run id) make a pending re-attempt reuse the
// same Stripe objects — no double charge.
//
// RE-CHARGE AFTER RELAX (a deliberate design decision): retained usage is
// DEFERRED, never FORGIVEN. If an account was tightened to prepaid in cycle N
// (its period-N run marked skipped_prepaid) and is later RELAXED back to arrears
// (invoice.paid clears the delinquency — see RelaxCollectionOnPaidInvoice), the
// period-N row is still non-terminal here, so it re-surfaces and the next cycle
// charges that retained period-N usage. That is correct: the customer always owes
// the metered usage; prepaid only postpones the off-session collection, it does
// not waive the debt. Forgiveness would require an explicit credit, which v1 does
// not do.
func (q *Queries) AccountsWithUnbilledUsage(ctx context.Context, arg AccountsWithUnbilledUsageParams) ([]string, error) {
	rows, err := q.db.Query(ctx, accountsWithUnbilledUsage, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var account_id string
		if err := rows.Scan(&account_id); err != nil {
			return nil, err
		}
		items = append(items, account_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accountsWithUsageEvents = `-- name: AccountsWithUsageEvents :many
SELECT DISTINCT account_id::uuid AS account_id
FROM ms_billing.usage_events
WHERE account_id  IS NOT NULL
  AND recorded_at >= $1
  AND recorded_at <  $2
`

type AccountsWithUsageEventsParams struct {
	RecordedAt   time.Time `json:"recorded_at"`
	RecordedAt_2 time.Time `json:"recorded_at_2"`
}

// AccountsWithUsageEvents returns the distinct accounts with at least one raw
// usage_events row in the closed window [period_start, period_end) — the ROLLUP
// (phase 1) work list. cmd/billing-cycle rolls each of these up
// (RollupPeriod → usage_aggregates) BEFORE the charge phase, so the charge
// phase's PeriodChargedTotal reads a populated aggregate set rather than 0.
// account_id is NULLABLE on usage_events (lazy-account metering); IS NOT NULL
// excludes pre-attribution events that have no account to bill. Half-open
// [start, end): recorded_at >= start AND recorded_at < end, matching the rollup
// SELECTs in rollup.sql.
func (q *Queries) AccountsWithUsageEvents(ctx context.Context, arg AccountsWithUsageEventsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, accountsWithUsageEvents, arg.RecordedAt, arg.RecordedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var account_id string
		if err := rows.Scan(&account_id); err != nil {
			return nil, err
		}
		items = append(items, account_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const activatedAccounts = `-- name: ActivatedAccounts :many

SELECT id, activated_at
FROM ms_billing.accounts
WHERE activated_at IS NOT NULL
`

type ActivatedAccountsRow struct {
	ID          string             `json:"id"`
	ActivatedAt pgtype.Timestamptz `json:"activated_at"`
}

// Queries backing the Milestone D PR #6 charge spine (the Stripe charge +
// cmd/billing-cycle binary). All operate on the ms_billing schema.
//
// The rollup/settlement queries (OpenPeriodForAccount, RollupSumKinds, …) live
// in rollup.sql (PR #5); this file ships ONLY the charge-cycle queries:
//
//	AccountsWithUsageEvents    accounts with raw usage_events in a closed period
//	                           window (the ROLLUP-phase work list — phase 1 of
//	                           cmd/billing-cycle)
//	AccountsWithUnbilledUsage  accounts with priced usage in a closed period
//	                           that have no SUCCESSFUL billing_run yet (the
//	                           CHARGE-phase work list — phase 2)
//	PeriodChargedTotal         Σ usage_aggregates.charged_micros per (account,
//	                           period) — the arrears input
//	InsertBillingRun           the idempotency gate (ON CONFLICT reclaiming a
//	                           non-terminal run; only an 'invoiced' run blocks)
//	MarkBillingRun             terminal status + stripe_invoice_id + total
//	UpsertInvoice              the Stripe invoice mirror
//	HasUsableDefaultPM         the no-PM gate (reuses payment_methods_mirror)
//	AccountStripeCustomer      resolve the account's stripe_customer_id for the
//	                           charge (NULL until the first Stripe Customer)
//
// SCOPE (PR #6): the USAGE (arrears) leg only. The advance leg (seats × price
// + apps × $20), the tiers table, and tier-sourced allowance are DEFERRED to a
// dedicated subscription/tier PR — they need tier pricing + per-account
// seat/app counts that do not exist in billing yet. allowanceMicros is an
// INPUT to the Go service (0 for v1), not a column read here.
//
// Money is micro-dollar BIGINT in usage_aggregates; the Go service converts
// micros → whole cents (round-half-up) at the Stripe boundary. The invoice
// mirror stores NUMERIC cents.
// ActivatedAccounts returns every account that has bound a card (activated_at IS
// NOT NULL — migration 025), with its anchor instant, for cmd/billing-cycle's
// per-account close driver. Un-activated accounts (NULL) have no card and nothing
// to bill, so they are excluded. The cycle derives each account's anchor day from
// activated_at and closes THAT account's just-ended anchored period — every close
// day differs, so the batch can no longer share one window.
func (q *Queries) ActivatedAccounts(ctx context.Context) ([]ActivatedAccountsRow, error) {
	rows, err := q.db.Query(ctx, activatedAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivatedAccountsRow{}
	for rows.Next() {
		var i ActivatedAccountsRow
		if err := rows.Scan(&i.ID, &i.ActivatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasUsableDefaultPM = `-- name: HasUsableDefaultPM :one
SELECT EXISTS (
    SELECT 1
    FROM ms_billing.payment_methods_mirror
    WHERE account_id = $1
      AND deleted_at IS NULL
      AND (exp_year, exp_month) >= (
          EXTRACT(YEAR  FROM current_date)::INT,
          EXTRACT(MONTH FROM current_date)::INT
      )
) AS has
`

// HasUsableDefaultPM is the no-PM charge gate: true iff the account has at
// least one active (not soft-deleted), not-expired payment_methods_mirror row.
// Mirrors billing.sql HasUsablePaymentMethod (the authoritative usable-PM
// predicate) so the charge spine and the Ensure hot-path agree. A default flag
// isn't required — Stripe charges the Customer's invoice-settings default PM,
// which the account sets when attaching; "usable PM exists" is the gate.
func (q *Queries) HasUsableDefaultPM(ctx context.Context, accountID string) (bool, error) {
	row := q.db.QueryRow(ctx, hasUsableDefaultPM, accountID)
	var has bool
	err := row.Scan(&has)
	return has, err
}

const insertBillingRun = `-- name: InsertBillingRun :one
INSERT INTO ms_billing.billing_runs (account_id, period_start, period_end, status)
VALUES ($1, $2, $3, 'pending')
ON CONFLICT (account_id, period_start, period_end) DO UPDATE
    SET status            = 'pending',
        stripe_invoice_id = NULL,
        total_amount      = 0
    WHERE ms_billing.billing_runs.status <> 'invoiced'
RETURNING id
`

type InsertBillingRunParams struct {
	AccountID   string    `json:"account_id"`
	PeriodStart time.Time `json:"period_start"`
	PeriodEnd   time.Time `json:"period_end"`
}

// InsertBillingRun is the FIRST idempotency layer: one run row per
// (account, period window). It inserts a 'pending' row; on conflict it RECLAIMS
// the existing row for a fresh attempt — but ONLY when that row is non-terminal
// ('pending' from a run that died mid-flight, 'skipped_no_pm', or 'failed'). The
// DO UPDATE resets the reclaimed row to 'pending' (clearing any stale invoice
// id / total) and RETURNING fires, so the Go store sees shouldCharge=true.
//
// When the existing row is 'invoiced' (terminal success) the DO UPDATE's WHERE
// excludes it: no row is updated, RETURNING yields nothing, and the store maps
// pgx.ErrNoRows to shouldCharge=false — the account was already charged for this
// window, so the cycle does NOT re-charge.
//
// Reclaiming the SAME row (not inserting a new one) preserves the run id, so the
// deterministic Stripe Idempotency-Keys (ii-<run>/inv-<run>) stay identical
// across attempts: a 'pending' re-attempt whose prior run already created the
// Stripe invoice reuses that exact invoice (no double charge), and UpsertInvoice
// is idempotent on stripe_invoice_id. UNIQUE(account, period) still holds —
// there is never more than one run row per window.
func (q *Queries) InsertBillingRun(ctx context.Context, arg InsertBillingRunParams) (string, error) {
	row := q.db.QueryRow(ctx, insertBillingRun, arg.AccountID, arg.PeriodStart, arg.PeriodEnd)
	var id string
	err := row.Scan(&id)
	return id, err
}

const latestClosedPeriodEnd = `-- name: LatestClosedPeriodEnd :one
SELECT period_end
FROM ms_billing.billing_periods
WHERE account_id = $1
ORDER BY period_end DESC
LIMIT 1
`

// LatestClosedPeriodEnd returns the newest billing_periods.period_end for an
// account; pgx.ErrNoRows when it has no period yet (the Go store maps that to
// "none"). cmd/billing-cycle uses it to STRADDLE-CLAMP the first anchored run at
// cutover: if a computed anchored window starts before the last calendar-month
// period already ended, the run starts at that end instead, producing one clean
// bridge period (calendar → anchor) with no overlap, gap, or duplicate
// (account_id, period_start) key. ORDER BY … LIMIT 1 (not MAX) so the result
// keeps the NOT NULL period_end column type instead of a nullable aggregate.
func (q *Queries) LatestClosedPeriodEnd(ctx context.Context, accountID string) (time.Time, error) {
	row := q.db.QueryRow(ctx, latestClosedPeriodEnd, accountID)
	var period_end time.Time
	err := row.Scan(&period_end)
	return period_end, err
}

const markBillingRun = `-- name: MarkBillingRun :exec
UPDATE ms_billing.billing_runs
SET status            = $2,
    stripe_invoice_id = $3,
    total_amount      = $4
WHERE id = $1
`

type MarkBillingRunParams struct {
	ID              string         `json:"id"`
	Status          string         `json:"status"`
	StripeInvoiceID pgtype.Text    `json:"stripe_invoice_id"`
	TotalAmount     pgtype.Numeric `json:"total_amount"`
}

// MarkBillingRun sets a run's terminal status, the Stripe invoice id (NULL for
// zero-arrears / skipped runs), and the charged total. Scoped to the run id so
// only the row this cycle inserted is updated.
func (q *Queries) MarkBillingRun(ctx context.Context, arg MarkBillingRunParams) error {
	_, err := q.db.Exec(ctx, markBillingRun,
		arg.ID,
		arg.Status,
		arg.StripeInvoiceID,
		arg.TotalAmount,
	)
	return err
}

const periodChargedTotal = `-- name: PeriodChargedTotal :one
SELECT COALESCE(SUM(ua.charged_micros), 0)::bigint AS total_micros
FROM ms_billing.usage_aggregates ua
JOIN ms_billing.billing_periods bp ON bp.id = ua.period_id
WHERE ua.account_id   = $1
  AND bp.period_start = $2
  AND bp.period_end   = $3
`

type PeriodChargedTotalParams struct {
	AccountID   string    `json:"account_id"`
	PeriodStart time.Time `json:"period_start"`
	PeriodEnd   time.Time `json:"period_end"`
}

// PeriodChargedTotal sums charged_micros across an account's usage_aggregates
// for a period window — the customer-billable arrears total (before
// allowance-netting, which the Go service applies). Joins billing_periods so
// the window is matched on the period row, not a raw usage_aggregates column.
func (q *Queries) PeriodChargedTotal(ctx context.Context, arg PeriodChargedTotalParams) (int64, error) {
	row := q.db.QueryRow(ctx, periodChargedTotal, arg.AccountID, arg.PeriodStart, arg.PeriodEnd)
	var total_micros int64
	err := row.Scan(&total_micros)
	return total_micros, err
}

const updateAccountCollection = `-- name: UpdateAccountCollection :execrows
UPDATE ms_billing.accounts
SET usage_billing_mode   = $2,
    credit_limit_micros  = $3,
    spend_ceiling_micros = $4
WHERE id = $1
`

type UpdateAccountCollectionParams struct {
	ID                 string                    `json:"id"`
	UsageBillingMode   MsBillingUsageBillingMode `json:"usage_billing_mode"`
	CreditLimitMicros  int64                     `json:"credit_limit_micros"`
	SpendCeilingMicros pgtype.Int8               `json:"spend_ceiling_micros"`
}

// UpdateAccountCollection persists a risk-judge mode transition (and, when the
// trust-ramp recomputes, the credit limit + spend ceiling). :execrows so the Go
// store maps RowsAffected == 0 to "account not found". updated_at is bumped by
// the accounts_set_updated_at trigger automatically.
func (q *Queries) UpdateAccountCollection(ctx context.Context, arg UpdateAccountCollectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAccountCollection,
		arg.ID,
		arg.UsageBillingMode,
		arg.CreditLimitMicros,
		arg.SpendCeilingMicros,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertInvoice = `-- name: UpsertInvoice :exec
INSERT INTO ms_billing.invoices (
    account_id, stripe_invoice_id, status,
    amount_due, amount_paid, currency,
    period_start, period_end, is_large_auto_collect
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (stripe_invoice_id)
DO UPDATE SET
    status                = EXCLUDED.status,
    amount_due            = EXCLUDED.amount_due,
    amount_paid           = EXCLUDED.amount_paid,
    currency              = EXCLUDED.currency,
    period_start          = EXCLUDED.period_start,
    period_end            = EXCLUDED.period_end,
    is_large_auto_collect = EXCLUDED.is_large_auto_collect
`

type UpsertInvoiceParams struct {
	AccountID          string             `json:"account_id"`
	StripeInvoiceID    string             `json:"stripe_invoice_id"`
	Status             string             `json:"status"`
	AmountDue          pgtype.Numeric     `json:"amount_due"`
	AmountPaid         pgtype.Numeric     `json:"amount_paid"`
	Currency           string             `json:"currency"`
	PeriodStart        pgtype.Timestamptz `json:"period_start"`
	PeriodEnd          pgtype.Timestamptz `json:"period_end"`
	IsLargeAutoCollect bool               `json:"is_large_auto_collect"`
}

// UpsertInvoice mirrors a Stripe invoice into ms_billing.invoices, keyed on the
// UNIQUE stripe_invoice_id so a re-run (deterministic Stripe Idempotency-Key
// returns the same invoice) upserts the same row rather than duplicating it.
// Webhook reconciliation (PR #7) later updates status + amount_paid in place.
// is_large_auto_collect (migration 034) is the server-computed post-hoc
// disclosure flag, frozen at invoice-create time from the amount charged vs the
// account threshold that applied WHEN THE CHARGE FIRED. A deterministic re-run
// (same Stripe idem key → same invoice, same charged amount) re-computes the same
// value, so carrying it through EXCLUDED on conflict is a no-op refresh.
func (q *Queries) UpsertInvoice(ctx context.Context, arg UpsertInvoiceParams) error {
	_, err := q.db.Exec(ctx, upsertInvoice,
		arg.AccountID,
		arg.StripeInvoiceID,
		arg.Status,
		arg.AmountDue,
		arg.AmountPaid,
		arg.Currency,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.IsLargeAutoCollect,
	)
	return err
}
