// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: freeze_snapshot.sql

package db

import (
	"context"
	"time"
)

const billingRunFreezeLineDrift = `-- name: BillingRunFreezeLineDrift :many
WITH frozen AS (
    SELECT l.app_id, l.module_id, l.metric, l.model, l.module_version,
           COALESCE(l.aggregation_key, '') AS aggregation_key,
           l.billable_quantity, l.unit_price_micros,
           l.customer_markup_num, l.customer_markup_den, l.charged_micros
    FROM ms_billing.billing_run_freeze_snapshot_lines l
    WHERE l.run_id = $1::uuid
),
live AS (
    SELECT ua.app_id, ua.module_id, ua.metric, ua.model, ua.module_version,
           COALESCE(ua.aggregation_key, '') AS aggregation_key,
           ua.billable_quantity, ua.unit_price_micros,
           ua.customer_markup_num, ua.customer_markup_den, ua.charged_micros
    FROM ms_billing.billing_runs r
    JOIN ms_billing.usage_aggregates ua ON ua.account_id = r.account_id
    JOIN ms_billing.billing_periods bp ON bp.id = ua.period_id
    WHERE r.id = $1::uuid
      AND bp.period_start = r.period_start
      AND bp.period_end   = r.period_end
      AND ua.dev_served   = false
)
SELECT COALESCE(f.app_id, l.app_id)::uuid                   AS app_id,
       COALESCE(f.module_id, l.module_id)::uuid             AS module_id,
       COALESCE(f.metric, l.metric)::text                   AS metric,
       COALESCE(f.model, l.model)::text                     AS model,
       COALESCE(f.module_version, l.module_version)::text   AS module_version,
       COALESCE(f.aggregation_key, l.aggregation_key)::text AS aggregation_key,
       (f.app_id IS NOT NULL)::boolean                      AS in_frozen,
       (l.app_id IS NOT NULL)::boolean                      AS in_live,
       COALESCE(f.billable_quantity, 0)::text               AS frozen_quantity,
       COALESCE(l.billable_quantity, 0)::text               AS live_quantity,
       COALESCE(f.unit_price_micros, 0)::bigint             AS frozen_unit_price_micros,
       COALESCE(l.unit_price_micros, 0)::bigint             AS live_unit_price_micros,
       COALESCE(f.customer_markup_num, 0)::integer          AS frozen_markup_num,
       COALESCE(f.customer_markup_den, 0)::integer          AS frozen_markup_den,
       COALESCE(l.customer_markup_num, 0)::integer          AS live_markup_num,
       COALESCE(l.customer_markup_den, 0)::integer          AS live_markup_den,
       COALESCE(f.charged_micros, 0)::bigint                AS frozen_charged_micros,
       COALESCE(l.charged_micros, 0)::bigint                AS live_charged_micros
FROM frozen f
FULL OUTER JOIN live l
  ON  l.app_id          = f.app_id
  AND l.module_id       = f.module_id
  AND l.metric          = f.metric
  AND l.model           = f.model
  AND l.module_version  = f.module_version
  AND l.aggregation_key = f.aggregation_key
WHERE f.app_id IS NULL
   OR l.app_id IS NULL
   OR f.billable_quantity   <> l.billable_quantity
   OR f.unit_price_micros   <> l.unit_price_micros
   OR f.customer_markup_num <> l.customer_markup_num
   OR f.customer_markup_den <> l.customer_markup_den
   OR f.charged_micros      <> l.charged_micros
ORDER BY 3, 2, 1, 4, 5, 6
`

type BillingRunFreezeLineDriftRow struct {
	AppID                 string `json:"app_id"`
	ModuleID              string `json:"module_id"`
	Metric                string `json:"metric"`
	Model                 string `json:"model"`
	ModuleVersion         string `json:"module_version"`
	AggregationKey        string `json:"aggregation_key"`
	InFrozen              bool   `json:"in_frozen"`
	InLive                bool   `json:"in_live"`
	FrozenQuantity        string `json:"frozen_quantity"`
	LiveQuantity          string `json:"live_quantity"`
	FrozenUnitPriceMicros int64  `json:"frozen_unit_price_micros"`
	LiveUnitPriceMicros   int64  `json:"live_unit_price_micros"`
	FrozenMarkupNum       int32  `json:"frozen_markup_num"`
	FrozenMarkupDen       int32  `json:"frozen_markup_den"`
	LiveMarkupNum         int32  `json:"live_markup_num"`
	LiveMarkupDen         int32  `json:"live_markup_den"`
	FrozenChargedMicros   int64  `json:"frozen_charged_micros"`
	LiveChargedMicros     int64  `json:"live_charged_micros"`
}

// BillingRunFreezeLineDrift is the line-level diff between a run's frozen
// derivation and the live aggregates (same row set as PeriodChargedTotal),
// joined on the aggregate key. Only lines that differ come back: one present
// on a single side, or one whose quantity, unit price, markup or charged
// figure moved. Empty for a run with no snapshot — the caller reads the header
// first to tell "no drift" from "nothing to compare against".
func (q *Queries) BillingRunFreezeLineDrift(ctx context.Context, runID string) ([]BillingRunFreezeLineDriftRow, error) {
	rows, err := q.db.Query(ctx, billingRunFreezeLineDrift, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingRunFreezeLineDriftRow{}
	for rows.Next() {
		var i BillingRunFreezeLineDriftRow
		if err := rows.Scan(
			&i.AppID,
			&i.ModuleID,
			&i.Metric,
			&i.Model,
			&i.ModuleVersion,
			&i.AggregationKey,
			&i.InFrozen,
			&i.InLive,
			&i.FrozenQuantity,
			&i.LiveQuantity,
			&i.FrozenUnitPriceMicros,
			&i.LiveUnitPriceMicros,
			&i.FrozenMarkupNum,
			&i.FrozenMarkupDen,
			&i.LiveMarkupNum,
			&i.LiveMarkupDen,
			&i.FrozenChargedMicros,
			&i.LiveChargedMicros,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const billingRunFreezeSnapshot = `-- name: BillingRunFreezeSnapshot :one
SELECT frozen_cents, usage_charged_micros, allowance_micros, arrears_micros,
       advance_base_micros, advance_overage_micros, advance_domains_micros,
       members_micros, wallet_drawn_micros, snapshotted_at
FROM ms_billing.billing_run_freeze_snapshots
WHERE run_id = $1::uuid
`

type BillingRunFreezeSnapshotRow struct {
	FrozenCents          int64     `json:"frozen_cents"`
	UsageChargedMicros   int64     `json:"usage_charged_micros"`
	AllowanceMicros      int64     `json:"allowance_micros"`
	ArrearsMicros        int64     `json:"arrears_micros"`
	AdvanceBaseMicros    int64     `json:"advance_base_micros"`
	AdvanceOverageMicros int64     `json:"advance_overage_micros"`
	AdvanceDomainsMicros int64     `json:"advance_domains_micros"`
	MembersMicros        int64     `json:"members_micros"`
	WalletDrawnMicros    int64     `json:"wallet_drawn_micros"`
	SnapshottedAt        time.Time `json:"snapshotted_at"`
}

func (q *Queries) BillingRunFreezeSnapshot(ctx context.Context, runID string) (BillingRunFreezeSnapshotRow, error) {
	row := q.db.QueryRow(ctx, billingRunFreezeSnapshot, runID)
	var i BillingRunFreezeSnapshotRow
	err := row.Scan(
		&i.FrozenCents,
		&i.UsageChargedMicros,
		&i.AllowanceMicros,
		&i.ArrearsMicros,
		&i.AdvanceBaseMicros,
		&i.AdvanceOverageMicros,
		&i.AdvanceDomainsMicros,
		&i.MembersMicros,
		&i.WalletDrawnMicros,
		&i.SnapshottedAt,
	)
	return i, err
}

const insertBillingRunFreezeSnapshot = `-- name: InsertBillingRunFreezeSnapshot :execrows

INSERT INTO ms_billing.billing_run_freeze_snapshots (
    run_id, frozen_cents, usage_charged_micros, allowance_micros, arrears_micros,
    advance_base_micros, advance_overage_micros, advance_domains_micros,
    members_micros, wallet_drawn_micros
)
SELECT r.id, $1::bigint,
       $2::bigint, $3::bigint, $4::bigint,
       $5::bigint, $6::bigint, $7::bigint,
       $8::bigint, $9::bigint
FROM ms_billing.billing_runs r
WHERE r.id = $10::uuid
  AND r.frozen_charge_cents = $1::bigint
ON CONFLICT (run_id) DO NOTHING
`

type InsertBillingRunFreezeSnapshotParams struct {
	FrozenCents          int64  `json:"frozen_cents"`
	UsageChargedMicros   int64  `json:"usage_charged_micros"`
	AllowanceMicros      int64  `json:"allowance_micros"`
	ArrearsMicros        int64  `json:"arrears_micros"`
	AdvanceBaseMicros    int64  `json:"advance_base_micros"`
	AdvanceOverageMicros int64  `json:"advance_overage_micros"`
	AdvanceDomainsMicros int64  `json:"advance_domains_micros"`
	MembersMicros        int64  `json:"members_micros"`
	WalletDrawnMicros    int64  `json:"wallet_drawn_micros"`
	RunID                string `json:"run_id"`
}

// Freeze snapshots (migration 087, billing-engine#218): the derivation a
// boundary freeze was taken from, written once per run and sealed, so a
// reclaim that re-derives a different figure can say WHICH line moved.
//
// Nothing here moves money or feeds a money reader. The cycle writes the
// snapshot best-effort right after a fresh freeze wins, and reads it only to
// log the line-level drift.
//
//	InsertBillingRunFreezeSnapshot       the header, bound to the run's frozen cents
//	InsertBillingRunFreezeSnapshotLines  the collectable aggregate lines
//	BillingRunFreezeSnapshot             read the header back
//	BillingRunFreezeLineDrift            frozen lines vs live aggregates, changed only
//
// InsertBillingRunFreezeSnapshot writes the header ONLY while the run still
// holds the figure being described: the INSERT … SELECT matches the run row on
// frozen_charge_cents, so a snapshot can never describe a freeze a concurrent
// daemon won with a different figure, or one a re-freeze has since moved.
// First-write-wins on run_id: 0 rows means another attempt already recorded
// the first derivation (or the run no longer holds these cents), and the
// caller writes no lines.
func (q *Queries) InsertBillingRunFreezeSnapshot(ctx context.Context, arg InsertBillingRunFreezeSnapshotParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertBillingRunFreezeSnapshot,
		arg.FrozenCents,
		arg.UsageChargedMicros,
		arg.AllowanceMicros,
		arg.ArrearsMicros,
		arg.AdvanceBaseMicros,
		arg.AdvanceOverageMicros,
		arg.AdvanceDomainsMicros,
		arg.MembersMicros,
		arg.WalletDrawnMicros,
		arg.RunID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertBillingRunFreezeSnapshotLines = `-- name: InsertBillingRunFreezeSnapshotLines :one
WITH inserted AS (
    INSERT INTO ms_billing.billing_run_freeze_snapshot_lines (
        run_id, app_id, module_id, metric, model, module_version, kind,
        aggregation_key, billable_quantity, unit_price_micros,
        customer_markup_num, customer_markup_den,
        raw_cost_micros, charged_micros, active_seconds, period_days, rolled_up_at
    )
    SELECT r.id, ua.app_id, ua.module_id, ua.metric, ua.model, ua.module_version, ua.kind,
           ua.aggregation_key, ua.billable_quantity, ua.unit_price_micros,
           ua.customer_markup_num, ua.customer_markup_den,
           ua.raw_cost_micros, ua.charged_micros, ua.active_seconds, ua.period_days, ua.rolled_up_at
    FROM ms_billing.billing_runs r
    JOIN ms_billing.usage_aggregates ua ON ua.account_id = r.account_id
    JOIN ms_billing.billing_periods bp ON bp.id = ua.period_id
    WHERE r.id = $1::uuid
      AND bp.period_start = r.period_start
      AND bp.period_end   = r.period_end
      AND ua.dev_served   = false
    RETURNING charged_micros
)
SELECT COUNT(*)::bigint AS lines,
       COALESCE(SUM(charged_micros), 0)::bigint AS charged_micros
FROM inserted
`

type InsertBillingRunFreezeSnapshotLinesRow struct {
	Lines         int64 `json:"lines"`
	ChargedMicros int64 `json:"charged_micros"`
}

// InsertBillingRunFreezeSnapshotLines copies the run's collectable aggregate
// lines — the exact row set PeriodChargedTotal (cycle.sql) sums: this account,
// this period window, dev_served = false — and returns what it copied, so the
// caller can refuse a snapshot whose Σ is not the total the freeze was
// derived from (a rollup that moved between the two reads).
func (q *Queries) InsertBillingRunFreezeSnapshotLines(ctx context.Context, runID string) (InsertBillingRunFreezeSnapshotLinesRow, error) {
	row := q.db.QueryRow(ctx, insertBillingRunFreezeSnapshotLines, runID)
	var i InsertBillingRunFreezeSnapshotLinesRow
	err := row.Scan(&i.Lines, &i.ChargedMicros)
	return i, err
}
