// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invoices.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const listInvoicesForAccount = `-- name: ListInvoicesForAccount :many

SELECT id, stripe_invoice_id, number, status,
       amount_due, amount_paid, currency,
       period_start, period_end, created_at,
       hosted_invoice_url, invoice_pdf, is_large_auto_collect
FROM ms_billing.invoices
WHERE account_id = $1::uuid
  AND status <> 'draft'
  AND (NOT $2::boolean
       OR (created_at, id) < ($3::timestamptz, $4::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $5::int
`

type ListInvoicesForAccountParams struct {
	AccountID       string    `json:"account_id"`
	HasCursor       bool      `json:"has_cursor"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        string    `json:"cursor_id"`
	RowLimit        int32     `json:"row_limit"`
}

type ListInvoicesForAccountRow struct {
	ID                 string             `json:"id"`
	StripeInvoiceID    string             `json:"stripe_invoice_id"`
	Number             pgtype.Text        `json:"number"`
	Status             string             `json:"status"`
	AmountDue          pgtype.Numeric     `json:"amount_due"`
	AmountPaid         pgtype.Numeric     `json:"amount_paid"`
	Currency           string             `json:"currency"`
	PeriodStart        pgtype.Timestamptz `json:"period_start"`
	PeriodEnd          pgtype.Timestamptz `json:"period_end"`
	CreatedAt          time.Time          `json:"created_at"`
	HostedInvoiceUrl   pgtype.Text        `json:"hosted_invoice_url"`
	InvoicePdf         pgtype.Text        `json:"invoice_pdf"`
	IsLargeAutoCollect bool               `json:"is_large_auto_collect"`
}

// Account-scoped READS over the ms_billing.invoices Stripe mirror (011 + 026)
// — the customer-facing invoice history behind the web-account billing page.
// billing-engine stays the SOLE writer of the mirror (the charge spine's
// UpsertInvoice + the webhook's ApplyInvoiceStatus); this file is read-only
// presentation and never touches Stripe.
// ListInvoicesForAccount is the keyset page read behind the ListInvoices RPC:
// one page of an account's mirrored Stripe invoices newest-first, EXCLUDING
// status='draft' rows — a draft is a not-yet-final Stripe artifact the
// customer was never billed for (it can still mutate or be deleted
// Stripe-side), so it never renders in the customer's invoice history.
//
// Pagination is KEYSET on (created_at, id) DESC: id (the UUID PK) breaks
// created_at ties so the ordering is total, which makes a page boundary
// unable to skip or duplicate a row — unlike OFFSET, which drifts whenever a
// new invoice lands between two requests. @has_cursor::boolean short-circuits
// the OR on the FIRST page, so the cursor params are inert well-formed
// placeholders there (the same gate pattern as VersionBreakdownForAccount);
// with a cursor, the row-tuple comparison resumes strictly AFTER the previous
// page's last row in DESC order. @row_limit arrives service-clamped
// (default/cap) as page+1 so the service detects a further page without a
// COUNT. The invoices_account_idx (011) covers the account filter; per-account
// invoice counts are one-per-period small, so no composite keyset index is
// warranted yet.
//
// Money columns are NUMERIC whole cents (Stripe minor units, 011); the Go
// store converts cents → int64 micro-dollars (×10_000) so micros stay the only
// money unit above the store boundary. number / hosted_invoice_url /
// invoice_pdf are NULL until the finalization webhook enriches the row (026).
func (q *Queries) ListInvoicesForAccount(ctx context.Context, arg ListInvoicesForAccountParams) ([]ListInvoicesForAccountRow, error) {
	rows, err := q.db.Query(ctx, listInvoicesForAccount,
		arg.AccountID,
		arg.HasCursor,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoicesForAccountRow{}
	for rows.Next() {
		var i ListInvoicesForAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.StripeInvoiceID,
			&i.Number,
			&i.Status,
			&i.AmountDue,
			&i.AmountPaid,
			&i.Currency,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.CreatedAt,
			&i.HostedInvoiceUrl,
			&i.InvoicePdf,
			&i.IsLargeAutoCollect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
