// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invoices.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnpaidInvoicesForAccount = `-- name: CountUnpaidInvoicesForAccount :one

SELECT COUNT(*)::int AS unpaid_count
FROM ms_billing.invoices
WHERE account_id = $1
  AND status IN ('open', 'uncollectible')
  AND amount_due > 0
`

// The UNPAID predicate (funding-gates design, DECIDED 2026-07-11) shared by
// the two queries below: still-collectible-but-not-collected mirror rows —
// status 'open' (finalized, Stripe smart-retrying) or 'uncollectible' (Stripe
// gave up, the account still owes) — with amount_due > 0 (a zero-total
// invoice was never money owed). 'draft' (never finalized), 'paid' and 'void'
// (debt forgiven) are clean. Narrower than AccountHasUnpaidInvoice
// (billing.sql) only by the amount_due > 0 term: standing and the Pay flow
// must never block on / offer to pay a zero-amount row.
// CountUnpaidInvoicesForAccount feeds GetServiceStatus's unpaid gate
// (eligibility gate 4: >= 2 unpaid → blocked).
func (q *Queries) CountUnpaidInvoicesForAccount(ctx context.Context, accountID string) (int32, error) {
	row := q.db.QueryRow(ctx, countUnpaidInvoicesForAccount, accountID)
	var unpaid_count int32
	err := row.Scan(&unpaid_count)
	return unpaid_count, err
}

const invoiceForPayment = `-- name: InvoiceForPayment :one
SELECT stripe_invoice_id, status
FROM ms_billing.invoices
WHERE id = $1
  AND account_id = $2
`

type InvoiceForPaymentParams struct {
	ID        string `json:"id"`
	AccountID string `json:"account_id"`
}

type InvoiceForPaymentRow struct {
	StripeInvoiceID string `json:"stripe_invoice_id"`
	Status          string `json:"status"`
}

// InvoiceForPayment resolves a mirror invoice by (id, account) for the
// PayInvoice RPC — the account scope IS the ownership check (a foreign or
// unknown id returns no row → NOT_FOUND, never leaking existence). Status
// rides along so the service can short-circuit an already-paid row and
// reject non-payable states before touching Stripe.
func (q *Queries) InvoiceForPayment(ctx context.Context, arg InvoiceForPaymentParams) (InvoiceForPaymentRow, error) {
	row := q.db.QueryRow(ctx, invoiceForPayment, arg.ID, arg.AccountID)
	var i InvoiceForPaymentRow
	err := row.Scan(&i.StripeInvoiceID, &i.Status)
	return i, err
}

const listInvoicesForAccount = `-- name: ListInvoicesForAccount :many

SELECT id, stripe_invoice_id, number, status,
       amount_due, amount_paid, currency,
       period_start, period_end, created_at,
       hosted_invoice_url, invoice_pdf, is_large_auto_collect, ever_failed
FROM ms_billing.invoices
WHERE account_id = $1::uuid
  AND status <> 'draft'
  AND (NOT $2::boolean
       OR (created_at, id) < ($3::timestamptz, $4::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $5::int
`

type ListInvoicesForAccountParams struct {
	AccountID       string    `json:"account_id"`
	HasCursor       bool      `json:"has_cursor"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        string    `json:"cursor_id"`
	RowLimit        int32     `json:"row_limit"`
}

type ListInvoicesForAccountRow struct {
	ID                 string             `json:"id"`
	StripeInvoiceID    string             `json:"stripe_invoice_id"`
	Number             pgtype.Text        `json:"number"`
	Status             string             `json:"status"`
	AmountDue          pgtype.Numeric     `json:"amount_due"`
	AmountPaid         pgtype.Numeric     `json:"amount_paid"`
	Currency           string             `json:"currency"`
	PeriodStart        pgtype.Timestamptz `json:"period_start"`
	PeriodEnd          pgtype.Timestamptz `json:"period_end"`
	CreatedAt          time.Time          `json:"created_at"`
	HostedInvoiceUrl   pgtype.Text        `json:"hosted_invoice_url"`
	InvoicePdf         pgtype.Text        `json:"invoice_pdf"`
	IsLargeAutoCollect bool               `json:"is_large_auto_collect"`
	EverFailed         bool               `json:"ever_failed"`
}

// Account-scoped READS over the ms_billing.invoices Stripe mirror (011 + 026)
// — the customer-facing invoice history behind the web-account billing page.
// billing-engine stays the SOLE writer of the mirror (the charge spine's
// UpsertInvoice + the webhook's ApplyInvoiceStatus); this file is read-only
// presentation and never touches Stripe.
// ListInvoicesForAccount is the keyset page read behind the ListInvoices RPC:
// one page of an account's mirrored Stripe invoices newest-first, EXCLUDING
// status='draft' rows — a draft is a not-yet-final Stripe artifact the
// customer was never billed for (it can still mutate or be deleted
// Stripe-side), so it never renders in the customer's invoice history.
//
// Pagination is KEYSET on (created_at, id) DESC: id (the UUID PK) breaks
// created_at ties so the ordering is total, which makes a page boundary
// unable to skip or duplicate a row — unlike OFFSET, which drifts whenever a
// new invoice lands between two requests. @has_cursor::boolean short-circuits
// the OR on the FIRST page, so the cursor params are inert well-formed
// placeholders there (the same gate pattern as VersionBreakdownForAccount);
// with a cursor, the row-tuple comparison resumes strictly AFTER the previous
// page's last row in DESC order. @row_limit arrives service-clamped
// (default/cap) as page+1 so the service detects a further page without a
// COUNT. The invoices_account_idx (011) covers the account filter; per-account
// invoice counts are one-per-period small, so no composite keyset index is
// warranted yet.
//
// Money columns are NUMERIC whole cents (Stripe minor units, 011); the Go
// store converts cents → int64 micro-dollars (×10_000) so micros stay the only
// money unit above the store boundary. number / hosted_invoice_url /
// invoice_pdf are NULL until the finalization webhook enriches the row (026).
func (q *Queries) ListInvoicesForAccount(ctx context.Context, arg ListInvoicesForAccountParams) ([]ListInvoicesForAccountRow, error) {
	rows, err := q.db.Query(ctx, listInvoicesForAccount,
		arg.AccountID,
		arg.HasCursor,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoicesForAccountRow{}
	for rows.Next() {
		var i ListInvoicesForAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.StripeInvoiceID,
			&i.Number,
			&i.Status,
			&i.AmountDue,
			&i.AmountPaid,
			&i.Currency,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.CreatedAt,
			&i.HostedInvoiceUrl,
			&i.InvoicePdf,
			&i.IsLargeAutoCollect,
			&i.EverFailed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnpaidInvoicesForAccount = `-- name: ListUnpaidInvoicesForAccount :many
SELECT id, COALESCE(number, '')::text AS number, amount_due, created_at
FROM ms_billing.invoices
WHERE account_id = $1
  AND status IN ('open', 'uncollectible')
  AND amount_due > 0
ORDER BY created_at ASC, id ASC
`

type ListUnpaidInvoicesForAccountRow struct {
	ID        string         `json:"id"`
	Number    string         `json:"number"`
	AmountDue pgtype.Numeric `json:"amount_due"`
	CreatedAt time.Time      `json:"created_at"`
}

// ListUnpaidInvoicesForAccount is the read behind the ListUnpaidInvoices RPC
// (the post-card-bind "pay N unpaid invoices?" prompt + the invoices table's
// Pay affordance). Oldest-first so a sequential pay-all settles the oldest
// debt first. Unpaid counts are gate-bounded small (the serving gate blocks
// at 2), so no pagination.
func (q *Queries) ListUnpaidInvoicesForAccount(ctx context.Context, accountID string) ([]ListUnpaidInvoicesForAccountRow, error) {
	rows, err := q.db.Query(ctx, listUnpaidInvoicesForAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnpaidInvoicesForAccountRow{}
	for rows.Next() {
		var i ListUnpaidInvoicesForAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.AmountDue,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
