// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type MsBillingAddCardRequestStatus string

const (
	MsBillingAddCardRequestStatusPending   MsBillingAddCardRequestStatus = "pending"
	MsBillingAddCardRequestStatusCompleted MsBillingAddCardRequestStatus = "completed"
	MsBillingAddCardRequestStatusDuplicate MsBillingAddCardRequestStatus = "duplicate"
	MsBillingAddCardRequestStatusFailed    MsBillingAddCardRequestStatus = "failed"
)

func (e *MsBillingAddCardRequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MsBillingAddCardRequestStatus(s)
	case string:
		*e = MsBillingAddCardRequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MsBillingAddCardRequestStatus: %T", src)
	}
	return nil
}

type NullMsBillingAddCardRequestStatus struct {
	MsBillingAddCardRequestStatus MsBillingAddCardRequestStatus `json:"ms_billing_add_card_request_status"`
	Valid                         bool                          `json:"valid"` // Valid is true if MsBillingAddCardRequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMsBillingAddCardRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MsBillingAddCardRequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MsBillingAddCardRequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMsBillingAddCardRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MsBillingAddCardRequestStatus), nil
}

type MsBillingAccount struct {
	ID               string      `json:"id"`
	OwnerKind        string      `json:"owner_kind"`
	OwnerUserID      pgtype.UUID `json:"owner_user_id"`
	OwnerOrgID       pgtype.UUID `json:"owner_org_id"`
	StripeCustomerID pgtype.Text `json:"stripe_customer_id"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
}

type MsBillingAddCardRequest struct {
	ID              string                        `json:"id"`
	AccountID       string                        `json:"account_id"`
	SetupIntentID   pgtype.Text                   `json:"setup_intent_id"`
	StripePmID      pgtype.Text                   `json:"stripe_pm_id"`
	Status          MsBillingAddCardRequestStatus `json:"status"`
	PaymentMethodID pgtype.UUID                   `json:"payment_method_id"`
	CreatedAt       time.Time                     `json:"created_at"`
	ResolvedAt      pgtype.Timestamptz            `json:"resolved_at"`
}

type MsBillingPaymentMethodsMirror struct {
	ID                    string             `json:"id"`
	AccountID             string             `json:"account_id"`
	StripePaymentMethodID string             `json:"stripe_payment_method_id"`
	Brand                 string             `json:"brand"`
	Last4                 string             `json:"last4"`
	ExpMonth              int32              `json:"exp_month"`
	ExpYear               int32              `json:"exp_year"`
	IsDefault             bool               `json:"is_default"`
	AttachedAt            time.Time          `json:"attached_at"`
	DeletedAt             pgtype.Timestamptz `json:"deleted_at"`
	Fingerprint           pgtype.Text        `json:"fingerprint"`
}

type MsBillingWebhookEventsProcessed struct {
	EventID     string    `json:"event_id"`
	EventType   string    `json:"event_type"`
	ProcessedAt time.Time `json:"processed_at"`
}
