// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type MsBillingAddCardRequestStatus string

const (
	MsBillingAddCardRequestStatusPending   MsBillingAddCardRequestStatus = "pending"
	MsBillingAddCardRequestStatusCompleted MsBillingAddCardRequestStatus = "completed"
	MsBillingAddCardRequestStatusDuplicate MsBillingAddCardRequestStatus = "duplicate"
	MsBillingAddCardRequestStatusFailed    MsBillingAddCardRequestStatus = "failed"
)

func (e *MsBillingAddCardRequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MsBillingAddCardRequestStatus(s)
	case string:
		*e = MsBillingAddCardRequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MsBillingAddCardRequestStatus: %T", src)
	}
	return nil
}

type NullMsBillingAddCardRequestStatus struct {
	MsBillingAddCardRequestStatus MsBillingAddCardRequestStatus `json:"ms_billing_add_card_request_status"`
	Valid                         bool                          `json:"valid"` // Valid is true if MsBillingAddCardRequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMsBillingAddCardRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MsBillingAddCardRequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MsBillingAddCardRequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMsBillingAddCardRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MsBillingAddCardRequestStatus), nil
}

type MsBillingBillingPeriodStatus string

const (
	MsBillingBillingPeriodStatusOpen     MsBillingBillingPeriodStatus = "open"
	MsBillingBillingPeriodStatusClosing  MsBillingBillingPeriodStatus = "closing"
	MsBillingBillingPeriodStatusInvoiced MsBillingBillingPeriodStatus = "invoiced"
)

func (e *MsBillingBillingPeriodStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MsBillingBillingPeriodStatus(s)
	case string:
		*e = MsBillingBillingPeriodStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MsBillingBillingPeriodStatus: %T", src)
	}
	return nil
}

type NullMsBillingBillingPeriodStatus struct {
	MsBillingBillingPeriodStatus MsBillingBillingPeriodStatus `json:"ms_billing_billing_period_status"`
	Valid                        bool                         `json:"valid"` // Valid is true if MsBillingBillingPeriodStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMsBillingBillingPeriodStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MsBillingBillingPeriodStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MsBillingBillingPeriodStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMsBillingBillingPeriodStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MsBillingBillingPeriodStatus), nil
}

type MsBillingBudgetScope string

const (
	MsBillingBudgetScopeApp     MsBillingBudgetScope = "app"
	MsBillingBudgetScopeOrg     MsBillingBudgetScope = "org"
	MsBillingBudgetScopeAccount MsBillingBudgetScope = "account"
)

func (e *MsBillingBudgetScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MsBillingBudgetScope(s)
	case string:
		*e = MsBillingBudgetScope(s)
	default:
		return fmt.Errorf("unsupported scan type for MsBillingBudgetScope: %T", src)
	}
	return nil
}

type NullMsBillingBudgetScope struct {
	MsBillingBudgetScope MsBillingBudgetScope `json:"ms_billing_budget_scope"`
	Valid                bool                 `json:"valid"` // Valid is true if MsBillingBudgetScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMsBillingBudgetScope) Scan(value interface{}) error {
	if value == nil {
		ns.MsBillingBudgetScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MsBillingBudgetScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMsBillingBudgetScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MsBillingBudgetScope), nil
}

type MsBillingMarginShareClass string

const (
	MsBillingMarginShareClassPrivate   MsBillingMarginShareClass = "private"
	MsBillingMarginShareClassPublished MsBillingMarginShareClass = "published"
)

func (e *MsBillingMarginShareClass) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MsBillingMarginShareClass(s)
	case string:
		*e = MsBillingMarginShareClass(s)
	default:
		return fmt.Errorf("unsupported scan type for MsBillingMarginShareClass: %T", src)
	}
	return nil
}

type NullMsBillingMarginShareClass struct {
	MsBillingMarginShareClass MsBillingMarginShareClass `json:"ms_billing_margin_share_class"`
	Valid                     bool                      `json:"valid"` // Valid is true if MsBillingMarginShareClass is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMsBillingMarginShareClass) Scan(value interface{}) error {
	if value == nil {
		ns.MsBillingMarginShareClass, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MsBillingMarginShareClass.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMsBillingMarginShareClass) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MsBillingMarginShareClass), nil
}

type MsBillingMetricKind string

const (
	MsBillingMetricKindCount        MsBillingMetricKind = "count"
	MsBillingMetricKindSum          MsBillingMetricKind = "sum"
	MsBillingMetricKindPeak         MsBillingMetricKind = "peak"
	MsBillingMetricKindTimeWeighted MsBillingMetricKind = "time_weighted"
)

func (e *MsBillingMetricKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MsBillingMetricKind(s)
	case string:
		*e = MsBillingMetricKind(s)
	default:
		return fmt.Errorf("unsupported scan type for MsBillingMetricKind: %T", src)
	}
	return nil
}

type NullMsBillingMetricKind struct {
	MsBillingMetricKind MsBillingMetricKind `json:"ms_billing_metric_kind"`
	Valid               bool                `json:"valid"` // Valid is true if MsBillingMetricKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMsBillingMetricKind) Scan(value interface{}) error {
	if value == nil {
		ns.MsBillingMetricKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MsBillingMetricKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMsBillingMetricKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MsBillingMetricKind), nil
}

type MsBillingUsageBillingMode string

const (
	MsBillingUsageBillingModeArrears MsBillingUsageBillingMode = "arrears"
	MsBillingUsageBillingModePrepaid MsBillingUsageBillingMode = "prepaid"
)

func (e *MsBillingUsageBillingMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MsBillingUsageBillingMode(s)
	case string:
		*e = MsBillingUsageBillingMode(s)
	default:
		return fmt.Errorf("unsupported scan type for MsBillingUsageBillingMode: %T", src)
	}
	return nil
}

type NullMsBillingUsageBillingMode struct {
	MsBillingUsageBillingMode MsBillingUsageBillingMode `json:"ms_billing_usage_billing_mode"`
	Valid                     bool                      `json:"valid"` // Valid is true if MsBillingUsageBillingMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMsBillingUsageBillingMode) Scan(value interface{}) error {
	if value == nil {
		ns.MsBillingUsageBillingMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MsBillingUsageBillingMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMsBillingUsageBillingMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MsBillingUsageBillingMode), nil
}

type MsBillingAccount struct {
	ID                 string                    `json:"id"`
	OwnerKind          string                    `json:"owner_kind"`
	OwnerUserID        pgtype.UUID               `json:"owner_user_id"`
	OwnerOrgID         pgtype.UUID               `json:"owner_org_id"`
	StripeCustomerID   pgtype.Text               `json:"stripe_customer_id"`
	CreatedAt          time.Time                 `json:"created_at"`
	UpdatedAt          time.Time                 `json:"updated_at"`
	UsageBillingMode   MsBillingUsageBillingMode `json:"usage_billing_mode"`
	CreditLimitMicros  int64                     `json:"credit_limit_micros"`
	SpendCeilingMicros pgtype.Int8               `json:"spend_ceiling_micros"`
}

type MsBillingAddCardRequest struct {
	ID              string                        `json:"id"`
	AccountID       string                        `json:"account_id"`
	SetupIntentID   pgtype.Text                   `json:"setup_intent_id"`
	StripePmID      pgtype.Text                   `json:"stripe_pm_id"`
	Status          MsBillingAddCardRequestStatus `json:"status"`
	PaymentMethodID pgtype.UUID                   `json:"payment_method_id"`
	CreatedAt       time.Time                     `json:"created_at"`
	ResolvedAt      pgtype.Timestamptz            `json:"resolved_at"`
}

type MsBillingBillingPeriod struct {
	ID          string                       `json:"id"`
	AccountID   string                       `json:"account_id"`
	PeriodStart time.Time                    `json:"period_start"`
	PeriodEnd   time.Time                    `json:"period_end"`
	Status      MsBillingBillingPeriodStatus `json:"status"`
	CreatedAt   time.Time                    `json:"created_at"`
}

type MsBillingBillingRun struct {
	ID              string         `json:"id"`
	AccountID       string         `json:"account_id"`
	PeriodStart     time.Time      `json:"period_start"`
	PeriodEnd       time.Time      `json:"period_end"`
	Status          string         `json:"status"`
	StripeInvoiceID pgtype.Text    `json:"stripe_invoice_id"`
	TotalAmount     pgtype.Numeric `json:"total_amount"`
	CreatedAt       time.Time      `json:"created_at"`
}

type MsBillingBudget struct {
	ID            string               `json:"id"`
	Scope         MsBillingBudgetScope `json:"scope"`
	ScopeID       string               `json:"scope_id"`
	AccountID     pgtype.UUID          `json:"account_id"`
	LimitMicros   int64                `json:"limit_micros"`
	AlertPercents []int32              `json:"alert_percents"`
	Active        bool                 `json:"active"`
	CreatedAt     time.Time            `json:"created_at"`
	UpdatedAt     time.Time            `json:"updated_at"`
}

type MsBillingBudgetAlert struct {
	ID          string    `json:"id"`
	BudgetID    string    `json:"budget_id"`
	PeriodStart time.Time `json:"period_start"`
	Percent     int32     `json:"percent"`
	SpendMicros int64     `json:"spend_micros"`
	LimitMicros int64     `json:"limit_micros"`
	FiredAt     time.Time `json:"fired_at"`
}

type MsBillingDeveloperSettlement struct {
	ID                  string                    `json:"id"`
	PeriodID            string                    `json:"period_id"`
	AccountID           string                    `json:"account_id"`
	ModuleID            string                    `json:"module_id"`
	DeveloperID         pgtype.UUID               `json:"developer_id"`
	IncomeMicros        int64                     `json:"income_micros"`
	InfraMicros         int64                     `json:"infra_micros"`
	MarginShareClass    MsBillingMarginShareClass `json:"margin_share_class"`
	PlatformTakeMicros  int64                     `json:"platform_take_micros"`
	DeveloperOwedMicros int64                     `json:"developer_owed_micros"`
	Status              string                    `json:"status"`
	CreatedAt           time.Time                 `json:"created_at"`
}

type MsBillingInvoice struct {
	ID              string             `json:"id"`
	AccountID       string             `json:"account_id"`
	StripeInvoiceID string             `json:"stripe_invoice_id"`
	Status          string             `json:"status"`
	AmountDue       pgtype.Numeric     `json:"amount_due"`
	AmountPaid      pgtype.Numeric     `json:"amount_paid"`
	Currency        string             `json:"currency"`
	PeriodStart     pgtype.Timestamptz `json:"period_start"`
	PeriodEnd       pgtype.Timestamptz `json:"period_end"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

type MsBillingMetricDefinition struct {
	ID              string              `json:"id"`
	ModuleID        string              `json:"module_id"`
	Metric          string              `json:"metric"`
	Kind            MsBillingMetricKind `json:"kind"`
	Unit            string              `json:"unit"`
	UnitPriceMicros pgtype.Int8         `json:"unit_price_micros"`
	Active          bool                `json:"active"`
	CreatedAt       time.Time           `json:"created_at"`
	UpdatedAt       time.Time           `json:"updated_at"`
}

type MsBillingModuleVisibility struct {
	ModuleID   string                    `json:"module_id"`
	Visibility MsBillingMarginShareClass `json:"visibility"`
	UpdatedAt  time.Time                 `json:"updated_at"`
}

type MsBillingPaymentMethodsMirror struct {
	ID                    string             `json:"id"`
	AccountID             string             `json:"account_id"`
	StripePaymentMethodID string             `json:"stripe_payment_method_id"`
	Brand                 string             `json:"brand"`
	Last4                 string             `json:"last4"`
	ExpMonth              int32              `json:"exp_month"`
	ExpYear               int32              `json:"exp_year"`
	IsDefault             bool               `json:"is_default"`
	AttachedAt            time.Time          `json:"attached_at"`
	DeletedAt             pgtype.Timestamptz `json:"deleted_at"`
	Fingerprint           pgtype.Text        `json:"fingerprint"`
}

type MsBillingUsageAggregate struct {
	ID                string              `json:"id"`
	PeriodID          string              `json:"period_id"`
	AccountID         string              `json:"account_id"`
	AppID             string              `json:"app_id"`
	ModuleID          string              `json:"module_id"`
	Metric            string              `json:"metric"`
	Kind              MsBillingMetricKind `json:"kind"`
	BillableQuantity  pgtype.Numeric      `json:"billable_quantity"`
	UnitPriceMicros   int64               `json:"unit_price_micros"`
	CustomerMarkupNum int32               `json:"customer_markup_num"`
	CustomerMarkupDen int32               `json:"customer_markup_den"`
	RawCostMicros     int64               `json:"raw_cost_micros"`
	ChargedMicros     int64               `json:"charged_micros"`
	RolledUpAt        time.Time           `json:"rolled_up_at"`
}

type MsBillingUsageEvent struct {
	EventID    string              `json:"event_id"`
	AccountID  pgtype.UUID         `json:"account_id"`
	AppID      string              `json:"app_id"`
	ModuleID   string              `json:"module_id"`
	Metric     string              `json:"metric"`
	Kind       MsBillingMetricKind `json:"kind"`
	Value      pgtype.Numeric      `json:"value"`
	RecordedAt time.Time           `json:"recorded_at"`
	IngestedAt time.Time           `json:"ingested_at"`
}

type MsBillingWebhookEventsProcessed struct {
	EventID     string    `json:"event_id"`
	EventType   string    `json:"event_type"`
	ProcessedAt time.Time `json:"processed_at"`
}
