// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: module_timers.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const coCreatedOverModuleTimers = `-- name: CoCreatedOverModuleTimers :many
SELECT id
FROM (
    SELECT id, app_id, installed_at, grace_resolved,
           row_number() OVER (ORDER BY installed_at, id) AS rn
    FROM ms_billing.app_module_overage_timers
    WHERE account_id = $1::uuid
      AND removed_at IS NULL
) ranked
WHERE app_id = $2::uuid
  AND installed_at = $3::timestamptz
  AND grace_resolved = false
  AND rn > $4::int
ORDER BY installed_at, id
`

type CoCreatedOverModuleTimersParams struct {
	AccountID       string    `json:"account_id"`
	AppID           string    `json:"app_id"`
	CreatedAt       time.Time `json:"created_at"`
	IncludedModules int32     `json:"included_modules"`
}

// CoCreatedOverModuleTimers backs the scenario-3 combined creation invoice: the
// ids of the app's live, unresolved install timers whose install instant IS the
// app's created_at (co-created at app creation) AND that are "over" (live-FIFO
// rank >= included). Their grace elapses at the SAME instant as the app's own
// creation grace, so the creation-proration charge folds them onto ONE invoice.
// The rank window spans ALL the account's live timers (an included module still
// occupies a FIFO slot), so rn > @included_modules is the 0-based rank >= included
// "over" predicate; the outer filter keeps only this app's co-created, still-
// unresolved rows. Ordered (installed_at, id) for a deterministic charge order.
func (q *Queries) CoCreatedOverModuleTimers(ctx context.Context, arg CoCreatedOverModuleTimersParams) ([]string, error) {
	rows, err := q.db.Query(ctx, coCreatedOverModuleTimers,
		arg.AccountID,
		arg.AppID,
		arg.CreatedAt,
		arg.IncludedModules,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countLiveModuleTimersForAccount = `-- name: CountLiveModuleTimersForAccount :one
SELECT COALESCE(count(*), 0)::bigint AS live_count
FROM ms_billing.app_module_overage_timers
WHERE account_id = $1
  AND removed_at IS NULL
`

// CountLiveModuleTimersForAccount returns the account's currently-live
// (removed_at IS NULL) install-timer count — the DISPLAY read behind
// GetAccountBill's account-overage line under the per-module-instance model
// (migration 033). The steady-state estimate $3 × max(0, live − included) counts
// the live "over" rows (the FIFO tail past the included 5); reading the timer
// table (the overage model's source of truth) rather than SUM(apps.module_count)
// keeps the shown overage tied to the rows the charge legs actually tier on.
// ::bigint keeps the aggregate a non-nullable scalar.
func (q *Queries) CountLiveModuleTimersForAccount(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveModuleTimersForAccount, accountID)
	var live_count int64
	err := row.Scan(&live_count)
	return live_count, err
}

const countOngoingOverModuleTimers = `-- name: CountOngoingOverModuleTimers :one
SELECT COALESCE(count(*), 0)::bigint AS over_count
FROM (
    SELECT installed_at, grace_expires_at,
           row_number() OVER (ORDER BY installed_at, id) AS rn
    FROM ms_billing.app_module_overage_timers
    WHERE account_id = $1::uuid
      AND removed_at IS NULL
) ranked
WHERE rn > $2::int
  AND installed_at < $3::timestamptz
  AND grace_expires_at < $3::timestamptz
`

type CountOngoingOverModuleTimersParams struct {
	AccountID       string    `json:"account_id"`
	IncludedModules int32     `json:"included_modules"`
	PeriodEnd       time.Time `json:"period_end"`
}

// CountOngoingOverModuleTimers is Leg 2's boundary-precharge input (scenario 6):
// the count of the account's currently-live install timers that are "over"
// (live-FIFO rank >= included) AND owed a FULL $3 precharge for the NEW period
// [@period_end, next boundary) — ongoing over-modules continuing into it.
// row_number() over the whole live set gives every live timer its 1-based FIFO
// rank; rn > @included_modules is exactly the 0-based rank >= included ("over")
// predicate. "over" is re-derived LIVE, so a charged timer that has since flipped
// to "included" (an earlier install removed) is not counted.
//
// The coverage contract with the grace legs (review 2026-07-06, tightened in
// wave 2 D1) — a timer is "ongoing" for the new period iff BOTH of:
//   - installed_at < @period_end — it existed before the new period opened. A
//     module installed INSIDE the new period had that period covered by its OWN
//     grace charge (Leg 1 / scenario 3), exactly the same cutoff the advance-base
//     leg applies via LiveAppsCreatedBefore; without it a reclaimed
//     skipped_no_pm/failed boundary run double-bills the period.
//   - grace_expires_at < @period_end — its grace elapsed BEFORE the new period
//     opened. Every grace charge covers install → the END of the period its grace
//     elapses into, so a boundary-straddling timer's new period belongs to Leg 1,
//     not this precharge (counting it would double-bill; skipping the NEXT
//     boundary would leave a gap — this predicate does neither).
//
// DELIBERATELY NOT a condition: grace_resolved (wave 2, D1). Resolution state
// is MUTABLE and set only by the sweeps, so keying on it made the precharge
// depend on cron ordering: a timer whose grace expired in the ~24h before the
// boundary was still unresolved when the boundary run executed, got excluded,
// and its post-boundary period was then billed by NO leg (Leg 1's coverage is
// derived from immutable timestamps and stops at the boundary). Both cutoffs
// above are immutable, so the precharge decision is identical whenever the run
// (or its reclaim) executes. An expired-unresolved timer counted here is
// charged its own install-period coverage by Leg 1 later — disjoint windows,
// never a double-bill. D1d resolved-uncharged rows count too (only the
// pre-activation install period is forgiven). Residual edge (accepted,
// verdict-at-boundary-time semantics): a timer whose live rank improves
// over→included between this run and its own sweep keeps the one precharge —
// no refund (D1e); the next boundary excludes it by rank.
func (q *Queries) CountOngoingOverModuleTimers(ctx context.Context, arg CountOngoingOverModuleTimersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOngoingOverModuleTimers, arg.AccountID, arg.IncludedModules, arg.PeriodEnd)
	var over_count int64
	err := row.Scan(&over_count)
	return over_count, err
}

const insertModuleOverageTimers = `-- name: InsertModuleOverageTimers :exec
INSERT INTO ms_billing.app_module_overage_timers
    (account_id, app_id, installed_at, grace_expires_at)
SELECT $1::uuid, $2::uuid, $3::timestamptz, $4::timestamptz
FROM generate_series(1, $5::int)
`

type InsertModuleOverageTimersParams struct {
	AccountID      string    `json:"account_id"`
	AppID          string    `json:"app_id"`
	InstalledAt    time.Time `json:"installed_at"`
	GraceExpiresAt time.Time `json:"grace_expires_at"`
	Count          int32     `json:"count"`
}

// InsertModuleOverageTimers inserts N identical install timers for one app, all
// anchored at the SAME installed_at / grace_expires_at (RegisterApp's K
// co-created modules share created_at; a SyncAppModules grow shares now()).
// generate_series(1, @count) with @count <= 0 yields no rows — a safe no-op.
func (q *Queries) InsertModuleOverageTimers(ctx context.Context, arg InsertModuleOverageTimersParams) error {
	_, err := q.db.Exec(ctx, insertModuleOverageTimers,
		arg.AccountID,
		arg.AppID,
		arg.InstalledAt,
		arg.GraceExpiresAt,
		arg.Count,
	)
	return err
}

const liveModuleTimerCountForApp = `-- name: LiveModuleTimerCountForApp :one

SELECT COALESCE(count(*), 0)::bigint AS live_count
FROM ms_billing.app_module_overage_timers
WHERE app_id = $1
  AND removed_at IS NULL
`

// Queries backing the per-module-instance overage timers (migration 033,
// DESIGN.md "Base fee — v2"). One row per module INSTALL EVENT; the charge
// layer (cycle/overage.go) synthesizes instances (the RPC carries only an
// integer module_count), determines included-vs-over LIVE by FIFO, and charges
// the over rows once their own grace elapses.
// LiveModuleTimerCountForApp counts an app's currently-live (removed_at IS NULL)
// install timers — the reconciliation input RegisterApp / SyncAppModules use to
// decide how many rows to insert or LIFO-remove so the live-timer set matches the
// app's module_count idempotently across fire-and-forget retries. ::bigint keeps
// it a non-nullable scalar.
func (q *Queries) LiveModuleTimerCountForApp(ctx context.Context, appID string) (int64, error) {
	row := q.db.QueryRow(ctx, liveModuleTimerCountForApp, appID)
	var live_count int64
	err := row.Scan(&live_count)
	return live_count, err
}

const liveModuleTimerRankBefore = `-- name: LiveModuleTimerRankBefore :one
SELECT COALESCE(count(*), 0)::bigint AS rank
FROM ms_billing.app_module_overage_timers
WHERE account_id = $1::uuid
  AND removed_at IS NULL
  AND (installed_at < $2::timestamptz
       OR (installed_at = $2::timestamptz AND id < $3::uuid))
`

type LiveModuleTimerRankBeforeParams struct {
	AccountID   string    `json:"account_id"`
	InstalledAt time.Time `json:"installed_at"`
	TimerID     string    `json:"timer_id"`
}

// LiveModuleTimerRankBefore returns how many of the account's currently-live
// install timers order STRICTLY BEFORE a given (installed_at, id) under the FIFO
// ordering (installed_at ASC, id ASC) — i.e. the target's 0-based FIFO rank.
// rank < IncludedModules ⇒ "included"; rank >= IncludedModules ⇒ "over".
// Computed fresh at every grace-check (never cached). Backed by
// app_module_overage_timers_live_fifo_idx.
func (q *Queries) LiveModuleTimerRankBefore(ctx context.Context, arg LiveModuleTimerRankBeforeParams) (int64, error) {
	row := q.db.QueryRow(ctx, liveModuleTimerRankBefore, arg.AccountID, arg.InstalledAt, arg.TimerID)
	var rank int64
	err := row.Scan(&rank)
	return rank, err
}

const markModuleTimerChargeAttempted = `-- name: MarkModuleTimerChargeAttempted :exec
UPDATE ms_billing.app_module_overage_timers
SET charge_attempted_at = $2
WHERE id = $1
  AND charge_attempted_at IS NULL
`

type MarkModuleTimerChargeAttemptedParams struct {
	ID                string             `json:"id"`
	ChargeAttemptedAt pgtype.Timestamptz `json:"charge_attempted_at"`
}

// MarkModuleTimerChargeAttempted stamps the recovery marker (036) BEFORE a
// charge attempt's first Stripe call. First-write-wins (the FIRST attempt
// instant is the durable one); never cleared.
func (q *Queries) MarkModuleTimerChargeAttempted(ctx context.Context, arg MarkModuleTimerChargeAttemptedParams) error {
	_, err := q.db.Exec(ctx, markModuleTimerChargeAttempted, arg.ID, arg.ChargeAttemptedAt)
	return err
}

const markModuleTimerCharged = `-- name: MarkModuleTimerCharged :exec
UPDATE ms_billing.app_module_overage_timers
SET grace_resolved        = true,
    grace_charged_at      = $1::timestamptz,
    grace_invoice_id      = $2,
    grace_invoice_item_id = $3
WHERE id = $4::uuid
  AND grace_resolved = false
`

type MarkModuleTimerChargedParams struct {
	GraceChargedAt     time.Time   `json:"grace_charged_at"`
	GraceInvoiceID     pgtype.Text `json:"grace_invoice_id"`
	GraceInvoiceItemID pgtype.Text `json:"grace_invoice_item_id"`
	TimerID            string      `json:"timer_id"`
}

// MarkModuleTimerCharged stamps the TERMINAL "over and charged" verdict once
// Leg 1's Stripe charge succeeded: grace_charged_at + grace_resolved = true and
// the GENUINE Stripe invoice / invoice-item ids (never idempotency-key strings).
// WHERE grace_resolved = false keeps a crash-retry idempotent (the deterministic
// per-timer Stripe keys already dedupe the charge itself).
func (q *Queries) MarkModuleTimerCharged(ctx context.Context, arg MarkModuleTimerChargedParams) error {
	_, err := q.db.Exec(ctx, markModuleTimerCharged,
		arg.GraceChargedAt,
		arg.GraceInvoiceID,
		arg.GraceInvoiceItemID,
		arg.TimerID,
	)
	return err
}

const markModuleTimerIncluded = `-- name: MarkModuleTimerIncluded :exec
UPDATE ms_billing.app_module_overage_timers
SET grace_resolved = true
WHERE id = $1
  AND grace_resolved = false
`

// MarkModuleTimerIncluded stamps a TERMINAL "included" verdict (grace_resolved =
// true, no charge) on a timer the grace-check found within the included 5.
// WHERE grace_resolved = false is first-write-wins (a concurrent sweep that
// already resolved it affects 0 rows). Monotonicity makes this verdict permanent
// — the row is never re-checked.
func (q *Queries) MarkModuleTimerIncluded(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markModuleTimerIncluded, id)
	return err
}

const moduleOverageTimersPastGrace = `-- name: ModuleOverageTimersPastGrace :many
SELECT t.id, t.account_id, t.app_id, t.installed_at, t.grace_expires_at,
       t.charge_attempted_at, a.activated_at
FROM ms_billing.app_module_overage_timers t
JOIN ms_billing.accounts a ON a.id = t.account_id
WHERE t.removed_at IS NULL
  AND t.grace_resolved = false
  AND t.grace_expires_at <= $1
  AND a.activated_at IS NOT NULL
ORDER BY t.installed_at, t.id
`

type ModuleOverageTimersPastGraceRow struct {
	ID                string             `json:"id"`
	AccountID         string             `json:"account_id"`
	AppID             string             `json:"app_id"`
	InstalledAt       time.Time          `json:"installed_at"`
	GraceExpiresAt    time.Time          `json:"grace_expires_at"`
	ChargeAttemptedAt pgtype.Timestamptz `json:"charge_attempted_at"`
	ActivatedAt       pgtype.Timestamptz `json:"activated_at"`
}

// ModuleOverageTimersPastGrace is Leg 1's work list: live, unresolved install
// timers whose grace window has elapsed as of $1, on accounts that are chargeable
// (activated_at IS NOT NULL — the same activation gate as the spine + proration
// leg). Each row carries the account's activation anchor so the sweep can resolve
// the install's period window without a second read, and the charge_attempted_at
// recovery marker (036) so a retried candidate reconciles against Stripe first.
// Ordered (installed_at, id) so the oldest install charges first (matches the
// FIFO ordering). Backed by app_module_overage_timers_sweep_idx.
func (q *Queries) ModuleOverageTimersPastGrace(ctx context.Context, graceExpiresAt time.Time) ([]ModuleOverageTimersPastGraceRow, error) {
	rows, err := q.db.Query(ctx, moduleOverageTimersPastGrace, graceExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModuleOverageTimersPastGraceRow{}
	for rows.Next() {
		var i ModuleOverageTimersPastGraceRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.AppID,
			&i.InstalledAt,
			&i.GraceExpiresAt,
			&i.ChargeAttemptedAt,
			&i.ActivatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moduleTimerStillPending = `-- name: ModuleTimerStillPending :one
SELECT (removed_at IS NULL AND grace_resolved = false)::bool AS pending
FROM ms_billing.app_module_overage_timers
WHERE id = $1
`

// ModuleTimerStillPending is the charge-time re-verification read (review
// 2026-07-06, M2): the sweep's work list is read ONCE and can be minutes stale
// by the time a late candidate is processed — re-check live + unresolved
// immediately before acting so a module removed (or resolved by a concurrent
// sweep) mid-batch is not charged.
func (q *Queries) ModuleTimerStillPending(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, moduleTimerStillPending, id)
	var pending bool
	err := row.Scan(&pending)
	return pending, err
}

const pendingAddonModuleCharges = `-- name: PendingAddonModuleCharges :many
SELECT ranked.app_id,
       a.name,
       count(*)::bigint AS addon_count,
       min(ranked.grace_expires_at)::timestamptz AS charge_eta
FROM (
    SELECT id, app_id, installed_at, grace_expires_at, grace_resolved,
           row_number() OVER (ORDER BY installed_at, id) AS rn
    FROM ms_billing.app_module_overage_timers
    WHERE account_id = $1::uuid
      AND removed_at IS NULL
) ranked
JOIN ms_billing.apps a ON a.app_id = ranked.app_id
WHERE ranked.rn > $2::int
  AND ranked.grace_resolved = false
  AND ranked.grace_expires_at > $3::timestamptz
  AND ranked.installed_at <> a.created_at
GROUP BY ranked.app_id, a.name
ORDER BY min(ranked.grace_expires_at), ranked.app_id
`

type PendingAddonModuleChargesParams struct {
	AccountID       string    `json:"account_id"`
	IncludedModules int32     `json:"included_modules"`
	Now             time.Time `json:"now"`
}

type PendingAddonModuleChargesRow struct {
	AppID      string      `json:"app_id"`
	Name       pgtype.Text `json:"name"`
	AddonCount int64       `json:"addon_count"`
	ChargeEta  time.Time   `json:"charge_eta"`
}

// PendingAddonModuleCharges is the pending ADD-ON half of the ListNewCreationCharges
// read (本期新建立): the account's live, unresolved install timers still INSIDE
// their own grace window as of @now — add-on charges that WILL fire (Leg 1 /
// cycle/overage.go) but haven't yet — grouped per app. Only timers "over" per
// the live FIFO rank (rn > @included_modules) are add-on charges at all.
// Co-created timers (installed_at = the app's created_at) are EXCLUDED: their
// pending charge is already represented by the app's own pending creation row
// (the scenario-3 combined invoice bills them together), and a co-created timer
// is in grace iff its app is — listing both would double-show one upcoming
// charge. Deleted apps cannot appear (deletion soft-removes every timer).
// One row per app: the frozen name, the count of pending add-on timers, and the
// EARLIEST grace expiry as the charge ETA. Ordered soonest-first, app_id
// breaking ties for a deterministic scan.
func (q *Queries) PendingAddonModuleCharges(ctx context.Context, arg PendingAddonModuleChargesParams) ([]PendingAddonModuleChargesRow, error) {
	rows, err := q.db.Query(ctx, pendingAddonModuleCharges, arg.AccountID, arg.IncludedModules, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingAddonModuleChargesRow{}
	for rows.Next() {
		var i PendingAddonModuleChargesRow
		if err := rows.Scan(
			&i.AppID,
			&i.Name,
			&i.AddonCount,
			&i.ChargeEta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softRemoveAllModuleTimersForApp = `-- name: SoftRemoveAllModuleTimersForApp :exec
UPDATE ms_billing.app_module_overage_timers
SET removed_at = $2
WHERE app_id = $1
  AND removed_at IS NULL
`

type SoftRemoveAllModuleTimersForAppParams struct {
	AppID     string             `json:"app_id"`
	RemovedAt pgtype.Timestamptz `json:"removed_at"`
}

// SoftRemoveAllModuleTimersForApp soft-removes EVERY still-live install timer for
// an app — the app-deletion path. Idempotent: a re-fire affects the rows already
// removed 0 times (WHERE removed_at IS NULL).
func (q *Queries) SoftRemoveAllModuleTimersForApp(ctx context.Context, arg SoftRemoveAllModuleTimersForAppParams) error {
	_, err := q.db.Exec(ctx, softRemoveAllModuleTimersForApp, arg.AppID, arg.RemovedAt)
	return err
}

const softRemoveNewestModuleTimers = `-- name: SoftRemoveNewestModuleTimers :exec
UPDATE ms_billing.app_module_overage_timers
SET removed_at = $1::timestamptz
WHERE id IN (
    SELECT id
    FROM ms_billing.app_module_overage_timers
    WHERE app_id = $2::uuid
      AND removed_at IS NULL
    ORDER BY installed_at DESC, id DESC
    LIMIT $3::int
)
`

type SoftRemoveNewestModuleTimersParams struct {
	RemovedAt  time.Time `json:"removed_at"`
	AppID      string    `json:"app_id"`
	LimitCount int32     `json:"limit_count"`
}

// SoftRemoveNewestModuleTimers LIFO-soft-removes the N NEWEST currently-live
// install timers for one app (a SyncAppModules shrink removes what was added most
// recently). Ordered (installed_at DESC, id DESC) — the reverse of the FIFO
// ordering. Sets removed_at = @removed_at on exactly those rows.
func (q *Queries) SoftRemoveNewestModuleTimers(ctx context.Context, arg SoftRemoveNewestModuleTimersParams) error {
	_, err := q.db.Exec(ctx, softRemoveNewestModuleTimers, arg.RemovedAt, arg.AppID, arg.LimitCount)
	return err
}
