// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: overage.sql

package db

import (
	"context"
)

const sumLiveModuleCount = `-- name: SumLiveModuleCount :one

SELECT COALESCE(SUM(module_count), 0)::bigint AS pooled_count
FROM ms_billing.apps
WHERE account_id = $1
  AND deleted_at IS NULL
`

// Queries backing the account-wide module-count SUM (migration 027/030). Under
// the per-module-instance overage model (migration 033) this is no longer a
// charge input — the charge legs tier on per-install timers (module_timers.sql).
// It survives only as the DISPLAY read: GetAccountBill's account-overage line
// shows the steady-state monthly estimate $3 × max(0, pooled − IncludedModules)
// (usage.AccountOverageMicros) from the CURRENT live pool. Money never lives on
// the apps mirror; the pool is derived on read.
// SumLiveModuleCount returns the account-wide installed-module count:
// SUM(module_count) over the account's LIVE (deleted_at IS NULL) apps —
// the display's steady-state overage estimate input. COALESCE to 0 so an
// account with no live apps sums to 0. ::bigint keeps the aggregate a
// non-nullable scalar.
func (q *Queries) SumLiveModuleCount(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRow(ctx, sumLiveModuleCount, accountID)
	var pooled_count int64
	err := row.Scan(&pooled_count)
	return pooled_count, err
}
