// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: overage.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const accountsInOverageGrace = `-- name: AccountsInOverageGrace :many
SELECT id, overage_since, activated_at
FROM ms_billing.accounts
WHERE overage_since IS NOT NULL
  AND overage_since <= $1
  AND activated_at  IS NOT NULL
`

type AccountsInOverageGraceRow struct {
	ID           string             `json:"id"`
	OverageSince pgtype.Timestamptz `json:"overage_since"`
	ActivatedAt  pgtype.Timestamptz `json:"activated_at"`
}

// AccountsInOverageGrace returns every account whose grace timer has EXPIRED as
// of the cutoff (overage_since <= $1 = now − 3 days) and that can be charged
// (activated_at IS NOT NULL — same activation gate as the spine). The
// mid-period sweep iterates these, derives each account's current anchored
// period from activated_at, and charges the pooled overage once per period
// (guarded by account_overage_snapshots). overage_since is returned so the
// sweep prorates from grace-end (overage_since + 3d) to the period end.
func (q *Queries) AccountsInOverageGrace(ctx context.Context, overageSince pgtype.Timestamptz) ([]AccountsInOverageGraceRow, error) {
	rows, err := q.db.Query(ctx, accountsInOverageGrace, overageSince)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountsInOverageGraceRow{}
	for rows.Next() {
		var i AccountsInOverageGraceRow
		if err := rows.Scan(&i.ID, &i.OverageSince, &i.ActivatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearAccountOverage = `-- name: ClearAccountOverage :execrows
UPDATE ms_billing.accounts
SET overage_since = NULL
WHERE id = $1
  AND overage_since IS NOT NULL
`

// ClearAccountOverage disarms the timer when the pool drops back to ≤5:
// overage_since → NULL. WHERE overage_since IS NOT NULL keeps it idempotent (a
// recompute on an already-under account affects 0 rows). No refund is issued
// (D1e) — clearing only stops FUTURE accrual; overage already charged this
// period stays billed via its account_overage_snapshots row.
func (q *Queries) ClearAccountOverage(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, clearAccountOverage, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertAccountOverageSnapshot = `-- name: InsertAccountOverageSnapshot :execrows
INSERT INTO ms_billing.account_overage_snapshots
    (account_id, period_start, period_end, over_count, charged_micros, source, invoice_item_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (account_id, period_start) DO NOTHING
`

type InsertAccountOverageSnapshotParams struct {
	AccountID     string      `json:"account_id"`
	PeriodStart   time.Time   `json:"period_start"`
	PeriodEnd     time.Time   `json:"period_end"`
	OverCount     int32       `json:"over_count"`
	ChargedMicros int64       `json:"charged_micros"`
	Source        string      `json:"source"`
	InvoiceItemID pgtype.Text `json:"invoice_item_id"`
}

// InsertAccountOverageSnapshot records what a charge leg billed the account for
// one period's pooled overage (migration 030). ON CONFLICT (account_id,
// period_start) DO NOTHING: an existing row — a prior grace charge, or a prior
// reclaimed boundary attempt's own row — wins, so a re-run never rewrites what
// was already recorded as billed. :execrows so the caller can observe the no-op,
// though both outcomes are success (the Stripe idempotency key on the same
// (account, period) already deduped the money).
func (q *Queries) InsertAccountOverageSnapshot(ctx context.Context, arg InsertAccountOverageSnapshotParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertAccountOverageSnapshot,
		arg.AccountID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.OverCount,
		arg.ChargedMicros,
		arg.Source,
		arg.InvoiceItemID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const selectAccountOverageSnapshot = `-- name: SelectAccountOverageSnapshot :one
SELECT over_count, charged_micros, source
FROM ms_billing.account_overage_snapshots
WHERE account_id  = $1
  AND period_start = $2
`

type SelectAccountOverageSnapshotParams struct {
	AccountID   string    `json:"account_id"`
	PeriodStart time.Time `json:"period_start"`
}

type SelectAccountOverageSnapshotRow struct {
	OverCount     int32  `json:"over_count"`
	ChargedMicros int64  `json:"charged_micros"`
	Source        string `json:"source"`
}

// SelectAccountOverageSnapshot reads the frozen pooled overage a charge leg
// billed for ONE (account, period) — the double-charge guard for the charge
// side (a row means "this period's pooled overage was already billed, skip it")
// AND the authoritative display value for GetAccountBill's pooled-overage line.
// Exact period_start match (both the grace sweep and the boundary leg key on the
// anchored window start); no row → never charged → the caller skips (charge
// side) or falls back to the live pooled estimate (display side).
func (q *Queries) SelectAccountOverageSnapshot(ctx context.Context, arg SelectAccountOverageSnapshotParams) (SelectAccountOverageSnapshotRow, error) {
	row := q.db.QueryRow(ctx, selectAccountOverageSnapshot, arg.AccountID, arg.PeriodStart)
	var i SelectAccountOverageSnapshotRow
	err := row.Scan(&i.OverCount, &i.ChargedMicros, &i.Source)
	return i, err
}

const startAccountOverage = `-- name: StartAccountOverage :execrows
UPDATE ms_billing.accounts
SET overage_since = $2
WHERE id = $1
  AND overage_since IS NULL
`

type StartAccountOverageParams struct {
	ID           string             `json:"id"`
	OverageSince pgtype.Timestamptz `json:"overage_since"`
}

// StartAccountOverage arms the account's grace timer: it stamps overage_since
// the FIRST time the pool crosses 5. WHERE overage_since IS NULL makes it
// first-crossing-wins (idempotent — a later recompute that finds the pool still
// over affects 0 rows and never moves the anchor), exactly like activated_at's
// first-bind-wins. :execrows so the caller can observe (and tolerate) the
// already-armed no-op.
func (q *Queries) StartAccountOverage(ctx context.Context, arg StartAccountOverageParams) (int64, error) {
	result, err := q.db.Exec(ctx, startAccountOverage, arg.ID, arg.OverageSince)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sumLiveModuleCount = `-- name: SumLiveModuleCount :one

SELECT COALESCE(SUM(module_count), 0)::bigint AS pooled_count
FROM ms_billing.apps
WHERE account_id = $1
  AND deleted_at IS NULL
`

// Queries backing the account-wide POOLED module overage (migration 030, owner
// spec 2026-07-05). The pool is SUM(module_count) over the account's LIVE apps;
// overage = $3 × max(0, pool − 5), charged once per account per period through
// the account_overage_snapshots ledger (the double-charge guard). These queries
// serve BOTH the charge side (cycle package: the recompute + the mid-period
// grace sweep + the boundary leg) and the display side (usage package:
// GetAccountBill's pooled-overage line). Money never lives on the apps mirror;
// the pool is derived on read.
// SumLiveModuleCount returns the account-wide POOLED installed-module count:
// SUM(module_count) over the account's LIVE (deleted_at IS NULL) apps. This is
// the single source of the pool both the overage timer recompute and the charge
// legs tier on: overage applies to max(0, this − IncludedModules). COALESCE to 0
// so an account with no live apps sums to 0 (never over). ::bigint keeps the
// aggregate a non-nullable scalar.
func (q *Queries) SumLiveModuleCount(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRow(ctx, sumLiveModuleCount, accountID)
	var pooled_count int64
	err := row.Scan(&pooled_count)
	return pooled_count, err
}
