// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plan_changes.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelPlanChangeByID = `-- name: CancelPlanChangeByID :execrows
UPDATE ms_billing.app_plan_changes
SET status     = 'cancelled',
    settled_at = $1::timestamptz
WHERE id = $2::uuid
  AND status = 'scheduled'
`

type CancelPlanChangeByIDParams struct {
	CancelledAt time.Time `json:"cancelled_at"`
	ID          string    `json:"id"`
}

// CancelPlanChangeByID withdraws one scheduled downgrade by id — the apply's
// refusal when the destination plan's cap is full at the boundary.
func (q *Queries) CancelPlanChangeByID(ctx context.Context, arg CancelPlanChangeByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelPlanChangeByID, arg.CancelledAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cancelScheduledPlanChange = `-- name: CancelScheduledPlanChange :execrows
UPDATE ms_billing.app_plan_changes
SET status     = 'cancelled',
    settled_at = $1::timestamptz
WHERE app_id = $2::uuid
  AND status = 'scheduled'
`

type CancelScheduledPlanChangeParams struct {
	CancelledAt time.Time `json:"cancelled_at"`
	AppID       string    `json:"app_id"`
}

// CancelScheduledPlanChange withdraws the app's scheduled downgrade (the owner
// upgraded back before the boundary, or asked for the current plan again).
// No money moves: a downgrade never charged anything. 0 rows = nothing was
// scheduled, which the service reports as a plain no-op.
func (q *Queries) CancelScheduledPlanChange(ctx context.Context, arg CancelScheduledPlanChangeParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelScheduledPlanChange, arg.CancelledAt, arg.AppID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const decidePlanChangeWallet = `-- name: DecidePlanChangeWallet :execrows
UPDATE ms_billing.app_plan_changes
SET wallet_micros     = $1::bigint,
    wallet_decided_at = $2::timestamptz,
    status            = CASE WHEN $1::bigint >= amount_micros THEN 'settled' ELSE status END,
    settled_at        = CASE WHEN $1::bigint >= amount_micros THEN $2::timestamptz ELSE settled_at END
WHERE id = $3::uuid
  AND status = 'pending'
  AND wallet_decided_at IS NULL
`

type DecidePlanChangeWalletParams struct {
	WalletMicros int64     `json:"wallet_micros"`
	DecidedAt    time.Time `json:"decided_at"`
	ID           string    `json:"id"`
}

// DecidePlanChangeWallet records the wallet decision ONCE: what the wallet
// drew (0 when it held nothing, or the account is not in credits mode) and
// the instant it was decided. When the draw covers the whole amount the row
// settles here — there is no card leg to wait for. First-write-wins on
// wallet_decided_at IS NULL: a retry that lost the race affects 0 rows and
// the caller re-reads the surviving decision.
func (q *Queries) DecidePlanChangeWallet(ctx context.Context, arg DecidePlanChangeWalletParams) (int64, error) {
	result, err := q.db.Exec(ctx, decidePlanChangeWallet, arg.WalletMicros, arg.DecidedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const duePlanChangesAll = `-- name: DuePlanChangesAll :many
SELECT id, app_id, account_id, from_plan, to_plan, kind, requested_at, effective_at, period_start, period_end, folded_into_creation, amount_micros, wallet_micros, card_micros, wallet_decided_at, card_ref, card_window_start, status, settled_at, created_at
FROM ms_billing.app_plan_changes
WHERE status = 'scheduled'
  AND effective_at <= $1::timestamptz
ORDER BY effective_at, id
FOR UPDATE
`

// DuePlanChangesAll is the driver's global apply list: every scheduled
// downgrade whose boundary has arrived, on any account, under a row lock.
func (q *Queries) DuePlanChangesAll(ctx context.Context, dueAt time.Time) ([]MsBillingAppPlanChange, error) {
	rows, err := q.db.Query(ctx, duePlanChangesAll, dueAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MsBillingAppPlanChange{}
	for rows.Next() {
		var i MsBillingAppPlanChange
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.AccountID,
			&i.FromPlan,
			&i.ToPlan,
			&i.Kind,
			&i.RequestedAt,
			&i.EffectiveAt,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.FoldedIntoCreation,
			&i.AmountMicros,
			&i.WalletMicros,
			&i.CardMicros,
			&i.WalletDecidedAt,
			&i.CardRef,
			&i.CardWindowStart,
			&i.Status,
			&i.SettledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const duePlanChangesForAccount = `-- name: DuePlanChangesForAccount :many
SELECT id, app_id, account_id, from_plan, to_plan, kind, requested_at, effective_at, period_start, period_end, folded_into_creation, amount_micros, wallet_micros, card_micros, wallet_decided_at, card_ref, card_window_start, status, settled_at, created_at
FROM ms_billing.app_plan_changes
WHERE account_id = $1::uuid
  AND status = 'scheduled'
  AND effective_at <= $2::timestamptz
ORDER BY effective_at, id
FOR UPDATE
`

type DuePlanChangesForAccountParams struct {
	AccountID string    `json:"account_id"`
	DueAt     time.Time `json:"due_at"`
}

// DuePlanChangesForAccount lists the account's scheduled downgrades whose
// boundary has arrived, under a row lock, for ApplyDuePlanChanges.
func (q *Queries) DuePlanChangesForAccount(ctx context.Context, arg DuePlanChangesForAccountParams) ([]MsBillingAppPlanChange, error) {
	rows, err := q.db.Query(ctx, duePlanChangesForAccount, arg.AccountID, arg.DueAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MsBillingAppPlanChange{}
	for rows.Next() {
		var i MsBillingAppPlanChange
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.AccountID,
			&i.FromPlan,
			&i.ToPlan,
			&i.Kind,
			&i.RequestedAt,
			&i.EffectiveAt,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.FoldedIntoCreation,
			&i.AmountMicros,
			&i.WalletMicros,
			&i.CardMicros,
			&i.WalletDecidedAt,
			&i.CardRef,
			&i.CardWindowStart,
			&i.Status,
			&i.SettledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const effectivePlanChangesForApp = `-- name: EffectivePlanChangesForApp :many
SELECT id, app_id, account_id, from_plan, to_plan, kind, requested_at, effective_at, period_start, period_end, folded_into_creation, amount_micros, wallet_micros, card_micros, wallet_decided_at, card_ref, card_window_start, status, settled_at, created_at
FROM ms_billing.app_plan_changes
WHERE app_id = $1
  AND status IN ('pending', 'settled', 'applied')
ORDER BY effective_at, id
`

// EffectivePlanChangesForApp lists every change that has TAKEN EFFECT on the
// app — settled upgrades (folded or charged) and applied downgrades — in
// effect order: the segments the creation charge prices by day
// (usage.SegmentedProratedBaseMicros), chained from apps.created_plan.
// Pending upgrades are in force too (the plan flipped with the row) and are
// included; scheduled and cancelled downgrades never moved the plan and are
// not.
func (q *Queries) EffectivePlanChangesForApp(ctx context.Context, appID string) ([]MsBillingAppPlanChange, error) {
	rows, err := q.db.Query(ctx, effectivePlanChangesForApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MsBillingAppPlanChange{}
	for rows.Next() {
		var i MsBillingAppPlanChange
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.AccountID,
			&i.FromPlan,
			&i.ToPlan,
			&i.Kind,
			&i.RequestedAt,
			&i.EffectiveAt,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.FoldedIntoCreation,
			&i.AmountMicros,
			&i.WalletMicros,
			&i.CardMicros,
			&i.WalletDecidedAt,
			&i.CardRef,
			&i.CardWindowStart,
			&i.Status,
			&i.SettledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPlanChange = `-- name: InsertPlanChange :one

INSERT INTO ms_billing.app_plan_changes (
    app_id, account_id, from_plan, to_plan, kind,
    requested_at, effective_at, period_start, period_end,
    folded_into_creation, amount_micros, wallet_micros, card_micros,
    wallet_decided_at, status, settled_at
) VALUES (
    $1::uuid, $2::uuid, $3::text, $4::text, $5::text,
    $6::timestamptz, $7::timestamptz, $8::timestamptz, $9::timestamptz,
    $10::boolean, $11::bigint, 0, 0,
    $12::timestamptz, $13::text, $14::timestamptz
)
RETURNING id, app_id, account_id, from_plan, to_plan, kind, requested_at, effective_at, period_start, period_end, folded_into_creation, amount_micros, wallet_micros, card_micros, wallet_decided_at, card_ref, card_window_start, status, settled_at, created_at
`

type InsertPlanChangeParams struct {
	AppID              string             `json:"app_id"`
	AccountID          string             `json:"account_id"`
	FromPlan           string             `json:"from_plan"`
	ToPlan             string             `json:"to_plan"`
	Kind               string             `json:"kind"`
	RequestedAt        time.Time          `json:"requested_at"`
	EffectiveAt        time.Time          `json:"effective_at"`
	PeriodStart        time.Time          `json:"period_start"`
	PeriodEnd          time.Time          `json:"period_end"`
	FoldedIntoCreation bool               `json:"folded_into_creation"`
	AmountMicros       int64              `json:"amount_micros"`
	WalletDecidedAt    pgtype.Timestamptz `json:"wallet_decided_at"`
	Status             string             `json:"status"`
	SettledAt          pgtype.Timestamptz `json:"settled_at"`
}

// Queries backing ms_billing.app_plan_changes (migration 076): the plan-change
// ledger cycle.SetAppPlan writes and the reconciler / boundary apply read. The
// row is the idempotency key of every money step of a change — see the
// migration header.
// InsertPlanChange opens one change. The service inserts it inside the same
// transaction that flips apps.plan for an upgrade (OpenPlanChange in
// store.go), under the app row lock, so the plan in force and the row that
// says what it cost can never disagree. The partial unique index refuses a
// second open row for the app; the store turns that into "resume the open
// one" rather than an error.
func (q *Queries) InsertPlanChange(ctx context.Context, arg InsertPlanChangeParams) (MsBillingAppPlanChange, error) {
	row := q.db.QueryRow(ctx, insertPlanChange,
		arg.AppID,
		arg.AccountID,
		arg.FromPlan,
		arg.ToPlan,
		arg.Kind,
		arg.RequestedAt,
		arg.EffectiveAt,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.FoldedIntoCreation,
		arg.AmountMicros,
		arg.WalletDecidedAt,
		arg.Status,
		arg.SettledAt,
	)
	var i MsBillingAppPlanChange
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.AccountID,
		&i.FromPlan,
		&i.ToPlan,
		&i.Kind,
		&i.RequestedAt,
		&i.EffectiveAt,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.FoldedIntoCreation,
		&i.AmountMicros,
		&i.WalletMicros,
		&i.CardMicros,
		&i.WalletDecidedAt,
		&i.CardRef,
		&i.CardWindowStart,
		&i.Status,
		&i.SettledAt,
		&i.CreatedAt,
	)
	return i, err
}

const lockPlanChange = `-- name: LockPlanChange :one
SELECT id, app_id, account_id, from_plan, to_plan, kind, requested_at, effective_at, period_start, period_end, folded_into_creation, amount_micros, wallet_micros, card_micros, wallet_decided_at, card_ref, card_window_start, status, settled_at, created_at
FROM ms_billing.app_plan_changes
WHERE id = $1
FOR UPDATE
`

// LockPlanChange reads one row under a ROW LOCK so a wallet decision and a
// card settlement serialize against a concurrent retry of the same change.
func (q *Queries) LockPlanChange(ctx context.Context, id string) (MsBillingAppPlanChange, error) {
	row := q.db.QueryRow(ctx, lockPlanChange, id)
	var i MsBillingAppPlanChange
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.AccountID,
		&i.FromPlan,
		&i.ToPlan,
		&i.Kind,
		&i.RequestedAt,
		&i.EffectiveAt,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.FoldedIntoCreation,
		&i.AmountMicros,
		&i.WalletMicros,
		&i.CardMicros,
		&i.WalletDecidedAt,
		&i.CardRef,
		&i.CardWindowStart,
		&i.Status,
		&i.SettledAt,
		&i.CreatedAt,
	)
	return i, err
}

const markPlanChangeApplied = `-- name: MarkPlanChangeApplied :execrows
UPDATE ms_billing.app_plan_changes
SET status     = 'applied',
    settled_at = $1::timestamptz
WHERE id = $2::uuid
  AND status = 'scheduled'
`

type MarkPlanChangeAppliedParams struct {
	AppliedAt time.Time `json:"applied_at"`
	ID        string    `json:"id"`
}

// MarkPlanChangeApplied closes a due downgrade after apps.plan moved.
func (q *Queries) MarkPlanChangeApplied(ctx context.Context, arg MarkPlanChangeAppliedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markPlanChangeApplied, arg.AppliedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const openPlanChangeForApp = `-- name: OpenPlanChangeForApp :one
SELECT id, app_id, account_id, from_plan, to_plan, kind, requested_at, effective_at, period_start, period_end, folded_into_creation, amount_micros, wallet_micros, card_micros, wallet_decided_at, card_ref, card_window_start, status, settled_at, created_at
FROM ms_billing.app_plan_changes
WHERE app_id = $1
  AND status IN ('pending', 'scheduled')
`

// OpenPlanChangeForApp reads the app's one open change (a pending upgrade or
// a scheduled downgrade), if any.
func (q *Queries) OpenPlanChangeForApp(ctx context.Context, appID string) (MsBillingAppPlanChange, error) {
	row := q.db.QueryRow(ctx, openPlanChangeForApp, appID)
	var i MsBillingAppPlanChange
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.AccountID,
		&i.FromPlan,
		&i.ToPlan,
		&i.Kind,
		&i.RequestedAt,
		&i.EffectiveAt,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.FoldedIntoCreation,
		&i.AmountMicros,
		&i.WalletMicros,
		&i.CardMicros,
		&i.WalletDecidedAt,
		&i.CardRef,
		&i.CardWindowStart,
		&i.Status,
		&i.SettledAt,
		&i.CreatedAt,
	)
	return i, err
}

const pendingPlanChanges = `-- name: PendingPlanChanges :many
SELECT id, app_id, account_id, from_plan, to_plan, kind, requested_at, effective_at, period_start, period_end, folded_into_creation, amount_micros, wallet_micros, card_micros, wallet_decided_at, card_ref, card_window_start, status, settled_at, created_at
FROM ms_billing.app_plan_changes
WHERE status = 'pending'
  AND requested_at <= $1::timestamptz
ORDER BY requested_at, id
`

// PendingPlanChanges is the reconciler's work list (SweepPendingPlanChanges):
// upgrades whose money steps did not all commit, oldest first.
func (q *Queries) PendingPlanChanges(ctx context.Context, requestedBefore time.Time) ([]MsBillingAppPlanChange, error) {
	rows, err := q.db.Query(ctx, pendingPlanChanges, requestedBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MsBillingAppPlanChange{}
	for rows.Next() {
		var i MsBillingAppPlanChange
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.AccountID,
			&i.FromPlan,
			&i.ToPlan,
			&i.Kind,
			&i.RequestedAt,
			&i.EffectiveAt,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.FoldedIntoCreation,
			&i.AmountMicros,
			&i.WalletMicros,
			&i.CardMicros,
			&i.WalletDecidedAt,
			&i.CardRef,
			&i.CardWindowStart,
			&i.Status,
			&i.SettledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const planChangeByID = `-- name: PlanChangeByID :one
SELECT id, app_id, account_id, from_plan, to_plan, kind, requested_at, effective_at, period_start, period_end, folded_into_creation, amount_micros, wallet_micros, card_micros, wallet_decided_at, card_ref, card_window_start, status, settled_at, created_at
FROM ms_billing.app_plan_changes
WHERE id = $1
`

// PlanChangeByID reads one row by id.
func (q *Queries) PlanChangeByID(ctx context.Context, id string) (MsBillingAppPlanChange, error) {
	row := q.db.QueryRow(ctx, planChangeByID, id)
	var i MsBillingAppPlanChange
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.AccountID,
		&i.FromPlan,
		&i.ToPlan,
		&i.Kind,
		&i.RequestedAt,
		&i.EffectiveAt,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.FoldedIntoCreation,
		&i.AmountMicros,
		&i.WalletMicros,
		&i.CardMicros,
		&i.WalletDecidedAt,
		&i.CardRef,
		&i.CardWindowStart,
		&i.Status,
		&i.SettledAt,
		&i.CreatedAt,
	)
	return i, err
}

const setPlanChangeCardWindow = `-- name: SetPlanChangeCardWindow :one
UPDATE ms_billing.app_plan_changes
SET card_window_start = CASE
    WHEN card_window_start IS NULL OR card_window_start < $1::timestamptz
    THEN $2::timestamptz
    ELSE card_window_start
END
WHERE id = $3::uuid
RETURNING card_window_start
`

type SetPlanChangeCardWindowParams struct {
	ReanchorBefore time.Time `json:"reanchor_before"`
	WindowStart    time.Time `json:"window_start"`
	ID             string    `json:"id"`
}

// SetPlanChangeCardWindow stores the card intent's window anchor and returns
// the surviving value, so every retry seals the same digest — unless the
// stored anchor's window has already CLOSED (stored < @reanchor_before, the
// seal instant minus the execution window): an anchor a failed seal left
// behind, or one whose sealed document is dead anyway, is replaced rather
// than reused to seal a document that could never be collected.
func (q *Queries) SetPlanChangeCardWindow(ctx context.Context, arg SetPlanChangeCardWindowParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, setPlanChangeCardWindow, arg.ReanchorBefore, arg.WindowStart, arg.ID)
	var card_window_start pgtype.Timestamptz
	err := row.Scan(&card_window_start)
	return card_window_start, err
}

const settlePlanChangeCard = `-- name: SettlePlanChangeCard :execrows
UPDATE ms_billing.app_plan_changes
SET card_micros = $1::bigint,
    card_ref    = $2::text,
    status      = 'settled',
    settled_at  = $3::timestamptz
WHERE id = $4::uuid
  AND status = 'pending'
`

type SettlePlanChangeCardParams struct {
	CardMicros int64     `json:"card_micros"`
	CardRef    string    `json:"card_ref"`
	SettledAt  time.Time `json:"settled_at"`
	ID         string    `json:"id"`
}

// SettlePlanChangeCard records the card remainder's sealed intent and settles
// the row. WHERE status = 'pending' makes it idempotent: a retry after the
// settle affects 0 rows.
func (q *Queries) SettlePlanChangeCard(ctx context.Context, arg SettlePlanChangeCardParams) (int64, error) {
	result, err := q.db.Exec(ctx, settlePlanChangeCard,
		arg.CardMicros,
		arg.CardRef,
		arg.SettledAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
