// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhook.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const accountExistsByStripeCustomer = `-- name: AccountExistsByStripeCustomer :one
SELECT EXISTS (SELECT 1 FROM ms_billing.accounts WHERE stripe_customer_id = $1) AS account_exists
`

// AccountExistsByStripeCustomer disambiguates a 0-row InsertPaymentMethod
// (drift vs ON CONFLICT/dedupe no-op).
func (q *Queries) AccountExistsByStripeCustomer(ctx context.Context, stripeCustomerID pgtype.Text) (bool, error) {
	row := q.db.QueryRow(ctx, accountExistsByStripeCustomer, stripeCustomerID)
	var account_exists bool
	err := row.Scan(&account_exists)
	return account_exists, err
}

const duplicateFingerprintPM = `-- name: DuplicateFingerprintPM :one
SELECT id
FROM ms_billing.payment_methods_mirror
WHERE account_id = $1
  AND fingerprint = $2
  AND id <> $3
  AND deleted_at IS NULL
LIMIT 1
`

type DuplicateFingerprintPMParams struct {
	AccountID   string      `json:"account_id"`
	Fingerprint pgtype.Text `json:"fingerprint"`
	ID          string      `json:"id"`
}

// DuplicateFingerprintPM probes for ANOTHER active mirror row on the same
// account with the same fingerprint (resolve transaction step 2).
func (q *Queries) DuplicateFingerprintPM(ctx context.Context, arg DuplicateFingerprintPMParams) (string, error) {
	row := q.db.QueryRow(ctx, duplicateFingerprintPM, arg.AccountID, arg.Fingerprint, arg.ID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertPaymentMethod = `-- name: InsertPaymentMethod :execrows
WITH acct AS (
    SELECT id FROM ms_billing.accounts WHERE stripe_customer_id = $1
)
INSERT INTO ms_billing.payment_methods_mirror
    (account_id, stripe_payment_method_id, brand, last4, exp_month, exp_year, is_default, fingerprint)
SELECT acct.id, $2, $3, $4, $5, $6,
    -- ADVISORY first-card default (see header). Authoritative default is
    -- set by customer.updated → SetDefaultPaymentMethodByCustomer.
    NOT EXISTS (
        SELECT 1 FROM ms_billing.payment_methods_mirror p
        WHERE p.account_id = acct.id AND p.deleted_at IS NULL
    ),
    NULLIF($7, '')
FROM acct
WHERE NOT EXISTS (
    SELECT 1 FROM ms_billing.payment_methods_mirror p2
    WHERE p2.account_id = acct.id
      AND p2.deleted_at IS NULL
      AND p2.brand = $3
      AND p2.last4 = $4
      AND p2.exp_month = $5
      AND p2.exp_year = $6
)
ON CONFLICT (stripe_payment_method_id) DO NOTHING
`

type InsertPaymentMethodParams struct {
	StripeCustomerID      pgtype.Text `json:"stripe_customer_id"`
	StripePaymentMethodID string      `json:"stripe_payment_method_id"`
	Brand                 string      `json:"brand"`
	Last4                 string      `json:"last4"`
	ExpMonth              int32       `json:"exp_month"`
	ExpYear               int32       `json:"exp_year"`
	Column7               interface{} `json:"column_7"`
}

// InsertPaymentMethod mirrors a Stripe PM into payment_methods_mirror.
// First active card on the account becomes the default (NOT EXISTS).
// Skips when an active row already shares brand/last4/exp (best-effort
// insert-time dedupe). fingerprint stored via NULLIF($7,”). No RETURNING
// → :execrows; the Go layer disambiguates 0 rows via AccountExists.
//
// is_default on INSERT is ADVISORY (the first-card auto-default feature
// from #14): it gives a brand-new account a usable default without an
// explicit choice. It is NOT authoritative — customer.updated →
// SetDefaultPaymentMethodByCustomer is the single source of truth for
// which PM is default. This INSERT-time value matches #14's raw
// InsertPaymentMethod exactly (NOT EXISTS over non-soft-deleted rows);
// do not "promote" it to authoritative here.
func (q *Queries) InsertPaymentMethod(ctx context.Context, arg InsertPaymentMethodParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPaymentMethod,
		arg.StripeCustomerID,
		arg.StripePaymentMethodID,
		arg.Brand,
		arg.Last4,
		arg.ExpMonth,
		arg.ExpYear,
		arg.Column7,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markEventProcessed = `-- name: MarkEventProcessed :execrows

INSERT INTO ms_billing.webhook_events_processed (event_id, event_type)
VALUES ($1, $2)
ON CONFLICT (event_id) DO NOTHING
`

type MarkEventProcessedParams struct {
	EventID   string `json:"event_id"`
	EventType string `json:"event_type"`
}

// Queries backing internal/account/webhook.pgxStore (the Stripe webhook
// side-effect surface). All operate on the ms_billing schema.
// MarkEventProcessed records the event_id for idempotency. :execrows so
// the caller can map 1 row → firstTime=true, 0 → duplicate.
func (q *Queries) MarkEventProcessed(ctx context.Context, arg MarkEventProcessedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markEventProcessed, arg.EventID, arg.EventType)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const mirrorRowByStripePM = `-- name: MirrorRowByStripePM :one
SELECT id, account_id, fingerprint
FROM ms_billing.payment_methods_mirror
WHERE stripe_payment_method_id = $1 AND deleted_at IS NULL
`

type MirrorRowByStripePMRow struct {
	ID          string      `json:"id"`
	AccountID   string      `json:"account_id"`
	Fingerprint pgtype.Text `json:"fingerprint"`
}

// MirrorRowByStripePM looks up a just-mirrored row by Stripe PM id, for
// the resolve transaction (step 1). fingerprint is nullable.
// `AND deleted_at IS NULL` guards the resolve anchor: a soft-deleted
// mirror row (e.g. detached then a stale attached/setup_intent event
// replays) must never become the row the request resolves against.
func (q *Queries) MirrorRowByStripePM(ctx context.Context, stripePaymentMethodID string) (MirrorRowByStripePMRow, error) {
	row := q.db.QueryRow(ctx, mirrorRowByStripePM, stripePaymentMethodID)
	var i MirrorRowByStripePMRow
	err := row.Scan(&i.ID, &i.AccountID, &i.Fingerprint)
	return i, err
}

const resolveAddCardRequest = `-- name: ResolveAddCardRequest :exec
UPDATE ms_billing.add_card_requests
SET status = $2::ms_billing.add_card_request_status,
    payment_method_id = $3,
    resolved_at = now()
WHERE stripe_pm_id = $1 AND status = 'pending'
`

type ResolveAddCardRequestParams struct {
	StripePmID      pgtype.Text                   `json:"stripe_pm_id"`
	Column2         MsBillingAddCardRequestStatus `json:"column_2"`
	PaymentMethodID pgtype.UUID                   `json:"payment_method_id"`
}

// ResolveAddCardRequest is the terminal resolve (step 4): set status +
// payment_method_id + resolved_at on the still-pending request matched by
// stripe_pm_id. $2 is cast to the enum type.
func (q *Queries) ResolveAddCardRequest(ctx context.Context, arg ResolveAddCardRequestParams) error {
	_, err := q.db.Exec(ctx, resolveAddCardRequest, arg.StripePmID, arg.Column2, arg.PaymentMethodID)
	return err
}

const setAddCardRequestStripePM = `-- name: SetAddCardRequestStripePM :exec
UPDATE ms_billing.add_card_requests
SET stripe_pm_id = $2
WHERE setup_intent_id = $1 AND status = 'pending'
`

type SetAddCardRequestStripePMParams struct {
	SetupIntentID pgtype.Text `json:"setup_intent_id"`
	StripePmID    pgtype.Text `json:"stripe_pm_id"`
}

// SetAddCardRequestStripePM stamps the resolved Stripe PM id onto a
// still-pending request row matched by setup_intent_id.
func (q *Queries) SetAddCardRequestStripePM(ctx context.Context, arg SetAddCardRequestStripePMParams) error {
	_, err := q.db.Exec(ctx, setAddCardRequestStripePM, arg.SetupIntentID, arg.StripePmID)
	return err
}

const setDefaultPaymentMethodByCustomer = `-- name: SetDefaultPaymentMethodByCustomer :exec
UPDATE ms_billing.payment_methods_mirror
SET is_default = (stripe_payment_method_id = $2)
WHERE account_id = (
    SELECT id FROM ms_billing.accounts WHERE stripe_customer_id = $1
)
AND deleted_at IS NULL
`

type SetDefaultPaymentMethodByCustomerParams struct {
	StripeCustomerID      pgtype.Text `json:"stripe_customer_id"`
	StripePaymentMethodID string      `json:"stripe_payment_method_id"`
}

// SetDefaultPaymentMethodByCustomer marks one PM as default and unmarks
// all others for the account in a single UPDATE. Empty defaultStripePMID
// ($2) clears the flag everywhere (no row equals ”).
func (q *Queries) SetDefaultPaymentMethodByCustomer(ctx context.Context, arg SetDefaultPaymentMethodByCustomerParams) error {
	_, err := q.db.Exec(ctx, setDefaultPaymentMethodByCustomer, arg.StripeCustomerID, arg.StripePaymentMethodID)
	return err
}

const softDeleteMirrorByID = `-- name: SoftDeleteMirrorByID :exec
UPDATE ms_billing.payment_methods_mirror
SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

// SoftDeleteMirrorByID soft-deletes the just-mirrored duplicate row by id
// (resolve transaction step 3).
func (q *Queries) SoftDeleteMirrorByID(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, softDeleteMirrorByID, id)
	return err
}

const softDeletePaymentMethod = `-- name: SoftDeletePaymentMethod :execrows
UPDATE ms_billing.payment_methods_mirror
SET deleted_at = now()
WHERE stripe_payment_method_id = $1 AND deleted_at IS NULL
`

// SoftDeletePaymentMethod marks a mirror row deleted by Stripe PM id.
// :execrows → >0 means found.
func (q *Queries) SoftDeletePaymentMethod(ctx context.Context, stripePaymentMethodID string) (int64, error) {
	result, err := q.db.Exec(ctx, softDeletePaymentMethod, stripePaymentMethodID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAccountByStripeCustomer = `-- name: TouchAccountByStripeCustomer :execrows
UPDATE ms_billing.accounts SET updated_at = now() WHERE stripe_customer_id = $1
`

// TouchAccountByStripeCustomer bumps updated_at for the account matching
// a Stripe customer. :execrows → >0 means found.
func (q *Queries) TouchAccountByStripeCustomer(ctx context.Context, stripeCustomerID pgtype.Text) (int64, error) {
	result, err := q.db.Exec(ctx, touchAccountByStripeCustomer, stripeCustomerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
